scrapers/AMAMultimedia.yml

This is a mega-scraper encompassing 32 sites directly (even including 
the PornPros network)

Adds AMA Multimedia xPath Scrapper

---

SCENE-SCRAPABLE.md
scrapers/PlayboyTV.yml

Still debugging the image on this one. Doesn't seem to be working.

Adds PlayboyTV xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/GloryHoleSwallow.yml

I'd like some input on this one. I'm unclear why the date/image does not work in testing.

Adds GloryHoleSwallows xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/JulesJordan.yml

Tested and the scraper works on all the sites.
~The only field that doesn't seem to work is the "Movie" field. This is my first time using that field though so I'm not sure if I'm missing something there.~
All working now

Adds JulesJordan xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/NewSensationsMain.yml

~Same as Jules Jordan, everything seems to be working except the Movie field~
All working now

Adds NewSensation xPath scraper

---

README.md

Slight change in formatting to the recent addition so an image isn't expanded in line with text. A little nicer on the eyes

Update readme format

---

SCENE-SCRAPABLE.md
scrapers/RealityKings.yml

While working through the Gamma Entertainment site list there was a site using the Reality kings stylings. Adding it on.

Adds site to Reality Kings scraper

---

scrapers/NewFreeones.yml

Added changes from #66 and  also updated performer url, name in performer search to eliminate some invalid duplicates when searching

NewFreeones fixes

---

README.md
SCENE-SCRAPABLE.md
scrapers/SexVR.yml

This was fun putting together, really played around with the performer scrapers and the search features. The scraped performer images aren't the best out there, but pretty decent info overall.

Adds SexVR xPath scraper

---

scrapers/ManyVids.yml

ManyVids: Fix Twitter and Instagram links

---

SCENE-SCRAPABLE.md
scrapers/AngelaWhite.yml

Really not much useful metadata on this site but this fills a request from https://github.com/stashapp/CommunityScrapers/issues/73

Adds AngelaWhite xPath scraper

---

scrapers/NaughtyAmerica.yml

Fixes image scraping for some more cases as mentioned in discord
https://pastebin.com/aAU4fWzQ has the scenes that didn't work before

Fix image scraping in NaughtyAmerica xpath scraper

---

SCENE-SCRAPABLE.md
scrapers/IsThisReal.yml

As mentioned here https://github.com/stashapp/CommunityScrapers/pull/49#issuecomment-633166300 this PR is currently in a blocked state due to the quirks of these sites and post-processing limitations.
This is the currently done work on it though.

Adds IsThisReal xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/Firstanalquest.yml

Thanks again to hyde and halorrr for helping me with the subscraper

Adds Firstanalquest xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/Xtube.yml

This one was requested in #73.
In some premium scenes the uploader seems to be the performer or you can at least uniquely identify her/him, so I added the uploader for the performer. I have also added the categories to the tags, as stash does not distinguish between them and they are often times more concise than the actual tags.

Adds xtube xPath scraper

---

scrapers/Kink.yml

fixed description, tags, performers and date for kink.com

fixed kink.com

---

SCENE-SCRAPABLE.md
scrapers/Xnxx.yml
scrapers/Xvideos.yml

The xvideos scraper was requested in #73.
Both share the same Image selector.

Adds Xvideos and Xnxx xPath scrapers

---

SCENE-SCRAPABLE.md
scrapers/javlibrary.yml

Tested for the EN version, but should work for other (CN,TW,JA) since Div keep same name.
Using :
- ID as Title
- Title in Detail
- Maker as Studio
Wall preview:

Add Javlibrary xPath scene scraper

---

SCENE-SCRAPABLE.md
scrapers/AmateurAllure.yml

A scraper for AmateurAllure from MarshmallowKing through our discord channel.
Its the first site we encountered that needs a `referer` header  for the image get so latest dev stash build is required to download the scene image.

Add AmateurAllure xPath scene scraper

---

SCENE-SCRAPABLE.md
scrapers/Hucows.yml
scrapers/Xhamster.yml

A couple of scrapers from the request thread #73 
They use the new post-processing format that was commited to stash here -> https://github.com/stashapp/stash/pull/616

Add Hucows, Xhamster xPath scene scrapers

---

scrapers/Babepedia.yml

Fixes birthdate , missing performer image and uses the new postprocess and map features

Babepedia fixes

---

SCENE-SCRAPABLE.md
scrapers/DorcelClub.yml

As requested from https://github.com/stashapp/CommunityScrapers/issues/73

Add DorcelClub xPath scene scraper

---

README.md
scrapers/Xslist.yml

Writed "(JAV)" in name to warn people it's for JAV Performers.
Not sure about the format of Measurements.

Adding XsList Performer Scraper (JAV)

---

scrapers/Modelhub.yml

First pass at a modelhub scene, and performer scraper

Add Modelhub scraper

---

SCENE-SCRAPABLE.md
scrapers/GangBangCreampie.yml

scraper from discord channel by echo6ix

Add GangBangCreampie xPath scene scraper

---

scrapers/AdultDvdMarketPlace.yml
scrapers/AdultEmpire.yml
scrapers/Iafd.yml
scrapers/IafdStreaming.yml

Adds movie by URL scrapers for AdultEmpire, Iafd and IafdStreaming.

Add a couple of movie scrapers.

---

scrapers/GammaEntertainment.yml

One line change.
The others should probably be also enabled, but this needs to be tested.

GammaEntertainment: Enable AssholeFever performer scraper.

---

SCENE-SCRAPABLE.md
scrapers/PornDB.yml

Updated to the newest version of PornDB using **CDP**.
- Added a optional selector for performer, By default only take female performer name.
- Added a optional regex for image,
- Ignore the default image. This one:

Update PornDB.yml (Xpath)

---

scrapers/BigBootyTGirls.yml

Scraper for BigBootyTGirls.
Supported Site|Scraper|Content
------------- | ------------- | -------------
bigbootytgirls.com|BigBootyTGirls.yml|Trans

Add BigBootyTGirls.yml

---

scrapers/PornDB.yml

Sometimes PornDB is slow, so this fix it.

Adding Sleep CDP for PornDB.yml (xPath)

---

SCENE-SCRAPABLE.md
scrapers/PornDB.yml

Update url for PornDB Xpath

---

SCENE-SCRAPABLE.md
scrapers/Mylf.yml
scrapers/PaperStreetMedia.yml

The version of Mylf no longer worked on PaperStreetMedia.yml.

Changing Mylf Scraper (PaperStreetMedia.yml -> Mylf.yml)

---

scrapers/RealityKingsOL.yml

Updated the @class on Title, Name, and Image to reflect changes on the sites.

Update RealityKingsOL.yml xpath scraper

---

scrapers/Iafd.yml

Fixing the issue with gender by using `map`

Adding postProcess to Iafd.yml (+map)

---

SCENE-SCRAPABLE.md
scrapers/DreamTranny.yml

DreamTranny scraper. Originally created July 24, and site hasn't changed since, so pretty safe imho.
Retested again on several scenes September 14.
**For SCENE-SCRAPABLE.md:**
dreamtranny.com|DreamTranny.yml|Trans
Supported Site|Scraper|Content
------------- | ------------- | -------------
dreamtranny.com|DreamTranny.yml|Trans

Added DreamTranny scraper

---

SCENE-SCRAPABLE.md
scrapers/RealityKingsOL.yml

TransAngels work(all fields) with RealityKingsOL.yml.
Tested September 16th, with like 10 scenes, including newest and oldest scene on the site.
Supported Site|Scraper|Content
------------- | ------------- | -------------
transangels.com|RealityKingsOL.yml|Trans

TransAngels added to RealityKingsOL.yml

---

SCENE-SCRAPABLE.md
scrapers/WowPorn.yml

Adding allfinegirls.net and wowgirls.xxx
Fixed the performer xpath.
I used map to put the Studio in a better cases

Update WowPorn.yml (Add more site to it)

---

SCENE-SCRAPABLE.md
scrapers/RealityKingsOL.yml

Add Erito to RealityKingsOL scraper

---

SCENE-SCRAPABLE.md
scrapers/Lustery.yml

Adding Lustery xpath scraper

---

scrapers/Brazzers.yml

Look like the URL is `Scene` without `s` now

Update Brazzer Scraper (Matching URL)

---

scrapers/xbvrdb.py
scrapers/xbvrdb.yml

Adding python based scraper that uses the sqlite database used by the xbvr 3d porn manager
Copy the sqlite database main.db from xbvr and rename to xbvr.db
This needs python3 and the sqlite3 library.

Add scraper based on xbvr sqlite database

---

scrapers/Iafd.yml

They use Https now.
Still have minor issue... (maybe this exist before ?)
Sometime it won't find `Lexi Belle` , but `Lexi Bell` work. Sometimes everything work 🤷 
#123

Fixing IAFD

---

SCENE-SCRAPABLE.md
scrapers/SpankBang.yml

Knocking off one of the scrapers from https://github.com/stashapp/CommunityScrapers/issues/73

Add SpankBang xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/Motherless.yml

Knocking another tube site off of https://github.com/stashapp/CommunityScrapers/issues/73

Adds motherless xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/FilthyFamily.yml

Most of the work on this was done by greenie in discord. I just made a couple tweaks/additions

Adds FilthyFamily xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/Paco.yml

For the title i opted to use `Paco movie_id` like in the Heyzo scraper as most actual titles from the scenes are the performer's name

Add PacoPacoMama xPath scene scraper

---

SCENE-SCRAPABLE.md
scrapers/ExCoGi.yml

Of note, there are scene dates on the site but not on the scene page. I could not figure out a subscraper method to grab them.

Add ExCoGi xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/YouPorn.yml

Filling another request from https://github.com/stashapp/CommunityScrapers/issues/73

Add YouPorn xPath scraper

---

SCENE-SCRAPABLE.md
scrapers/WatchMyGF.yml

Filling another site request from https://github.com/stashapp/CommunityScrapers/issues/73

Add WatchMyGF xPath scraper

---

scrapers/FemDomEmpire.yml

Add FemDomEmpire Scraper. Need help with tags. They are available but I could not figure out how to scrape them.

Add FemDomEmpire Scraper

---

scrapers/TeamSkeet.yml

Switched the TeamSkeet scraper to use the CDP driver as it stopped working due to Cloudflare errors to fill a captcha.
This is the HTML the scraper requests were getting back prior to the CDP switch:
```HTML
<!DOCTYPE html><html class="no-js" lang="en-US"><head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass"/>
<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
<meta name="robots" content="noindex, nofollow"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection"/>
<style …
```

Switch TeamSkeet scraper to use CDP driver

---

scrapers/r18.yml

Adds the `Product  Description` part where available

Update details in r18.com scraper

---

scrapers/Clips4Sale.yml

Old image selector was broken, updated it to the new xPath

Updates the Image selector on Clips4sale scraper

---

scrapers/PervCity.yml

Add PervCity.com scraper

---

SCENE-SCRAPABLE.md
scrapers/Karissa-Diamond.yml

Adds a scene scraper for Karissa-Diamond.com. Uses fixed studio and performer as this is the performer's solo site.

add Karissa-Diamond.com xPath scene scraper

---

SCENE-SCRAPABLE.md
scrapers/Mypervyfamily.yml

```
- filthypov.com
- filthykings.com
```

Adding filthy site into Mypervyfamily.yml

---

SCENE-SCRAPABLE.md
scrapers/PaperStreetMedia.yml

- Adding map for better Name.
- Order URL
Thanks to Greenie on discord for suggesting this site 👍

Adding stayhomepov in PaperStreetMedia.yml

---

SCENE-SCRAPABLE.md
scrapers/21Roles.yml

I feel that the xPaths on this are all correct but when I tried to test it with this URL:
`https://21roles.com/game/DisplayPlayer/gameId/85358`
I get a GraphQL error:
`
GraphQL error: Get https://track.21roles.com/track/OC40NDEuNDEuOTEyMS4wLjAuMC4wLjA?whitesite=https://21roles.com/game/DisplayPlayer/gameId/85358: stopped after 10 redirects
`
Not sure how to get around this.

Adds 21Roles xPath scraper

---

scrapers/javlibrary.yml

I don't changed the note on my previous PR... 😅

Update javlibrary.yml (Note)

---

SCENE-SCRAPABLE.md
scrapers/PaperStreetMedia.yml

Thanks to Greenie for finding this site 👍

Adding TeenPies to PaperStreetMedia.yml

---

README.md
scrapers/Karissa-Diamond.yml

Adds gallery scraping support. Also adds a Gallery Scrapers section to the readme.

Update Karissa Diamond scraper

---

scrapers/FittingRoom.yml

Add Fitting-Room Scraper. Please review.

Add Fitting-Room Scraper

---

SCENE-SCRAPABLE.md
scrapers/AbbyWinters.yml

Adding abbywinters.com

---

README.md
SCENE-SCRAPABLE.md
scrapers/MPLStudios.yml

Adds scene and gallery xPath scrapers for MPLStudios.

add MPLStudios

---

scrapers/Carib.yml
scrapers/Heyzo.yml

Use of queryURLReplace  to construct the URLs for Heyzo and Caribbeancom from the filename.
Also includes an image fix for caribbeancom

Add sceneByFragment for Heyzo, Caribbeancom

---

README.md
scrapers/hentai2read.yml
scrapers/nhentai.yml

nhentai & hentai2read scraper
For hentai2read, the release date is only the Year, so i added 01-01 so we got a correct date.
Not sure about details (Alternative title ?) and studio (Artist or group ?)
Btw: there is nothing about galleries scraping in Stash wiki/help
Btw 2: In scraper page in Settings, there in galleries scraper table

Hentai site Galleries Scraper (xPath)

---

scrapers/Kink.yml

Add sceneByFragment support that gets the scene id from filename.
Currently detects ids from filenames with this form (lets say 12345 is the scene id)
```
12345_performer_other_data.mp4
studio - 2009-11-30 - performer - other - data (12345).mp4
````

add sceneByFragment for Kink

---

SCENE-SCRAPABLE.md
scrapers/AussieFelatioQueens.yml

Adding AussieFelatioQueens.com scraper

Adding AussieFelatioQueens.com scraper

---

SCENE-SCRAPABLE.md
scrapers/bruceandmorgan.yml

adding bruceandmorgan.com scraper

adding bruceandmorgan.com scraper

---

SCENE-SCRAPABLE.md
scrapers/AussieAss.yml

adding scraper for AussieAss.com aussiepov.com

adding scraper for AussieAss.com aussiepov.com

---

scrapers/FreeonesCommunity.yml

Look like `profile-image-container` became `dashboard-image-container `
So `//div[contains(@class,'image-container')]//a/img/@src` should work everytimes 😄

Update FreeonesCommunity.yml (Fix image)

---

SCENE-SCRAPABLE.md
scrapers/brandibelle.yml

Add brandibelle scene scrapper

Add brandibelle xPath scene scrapper

---

SCENE-SCRAPABLE.md
scrapers/infernalrestraints.yml

Add infernalrestraints scene scrapper

Add infernalrestraints xPath scene scrapper

---

scrapers/stash-sqlite.py
scrapers/stash-sqlite.yml

This adds a python based scraper for performers using the stash sqlite database.
requires python3 and sqlite3.
Note this does not include images as I would need to start a web server.

Adding a python based scraper for performers using the stash sqlite database.

---

README.md
SCENE-SCRAPABLE.md
scrapers/ClubSeventeen.yml

The site is a little difficult to search for a scene ( too many join links ) so a google site search for the performer is recommended.

Add ClubSeventeen xPath scene, gallery scraper

---

README.md
SCENE-SCRAPABLE.md
scrapers/HarmonyVision.yml

Add HarmonyVision xPath movie,scene scraper

---

scrapers/AEBN.yml

- optimize dates
- optimize image regex
✅ tested

AEBN: Optimize

---

scrapers/Clips4Sale.yml

- add studio
- use `common` for `.clipInfo` selector
- optimize date
- concat details by two empty lines
✅ tested

Clips4Sale: Update

---

scrapers/Pornhub.yml

searches for ph id ( phxxxxxx ) in the filename (should be separated by a non digit,plain char from the rest of the  filename) and uses that to construct the scene url

Add scene by fragment to Pornhub

---

SCRAPERS-LIST.md
scrapers/CombatZone.yml

- XPath scene scrapers for:
- `blackmarketxxx.com`
- `combatzonexxx.com`
- `fillyfilms.com`
- `smashpictures.com`
- XPath movie scraper for the catalog on `combatzone.us/distributor/`

Combat Zone

---

SCRAPERS-LIST.md
scrapers/Hegre.yml

As requested in the discord channel

Add Hegre xPath Scraper

---

SCRAPERS-LIST.md
scrapers/Wtfpass.yml

Add wtfpass xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/StudioFOW.yml

Add StudioFOW xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/MindGeek.yml

Tested with a few scenes/modles seems to work ok.

Add girlgrind to MindGeek

---

SCRAPERS-LIST.md
scrapers/mgstage.yml

JAV scraper, most of text is japanese.

Mgstage Scraper (Xpath + Cookie 🍪)

---

SCRAPERS-LIST.md
scrapers/KellyMadisonMedia.yml

Current XPath was incorrect, site changed recently ?
- Look like you don't need CDP anymore, should i remove it from the scraper and in `SCRAPERS-LIST.md` ?
But if you use it headless chrome, you already don't have problem with cookie so i guess it should stay.
So `useCDP:` should be in `False` or `True` by default ?
- I am not sure about the comment on top of file. Don't really know how to explain correctly.

Update KellyMadisonMedia.yml (Cookie Update)

---

SCRAPERS-LIST.md
scrapers/TeenMegaWorld.yml

Closes #101 
https://pastebin.com/4YhsdmWE

TeenMegaWorld XPath scene scraper

---

SCRAPERS-LIST.md
scrapers/javdb.yml

Performer, Studio, Director is always in Japanese (For jav scene) 😞

JavDB Scraper (Xpath + Json + Cookie)

---

SCRAPERS-LIST.md
scrapers/Penthouse.yml

Not sure about studio name, if it should be "Penthouse Gold" or "Penthouse" 🤷‍♂️

Penthouse Scraper (Xpath)

---

scrapers/Hegre.yml

Requested on Discord.
Tests:
```
https://www.hegre.com/massage/girl-girl-massage
https://www.hegre.com/films/ariel-slow-sexy-symphony  (for regression)
```

Hegre: Add `/massage`

---

SCRAPERS-LIST.md
scrapers/FetishNetwork.yml

Add fetishnetwork xPath scraper

---

validator/scraper.schema.json

Update scraper schema - support `driver.clicks`

---

SCRAPERS-LIST.md
scrapers/AssTraffic.yml
scrapers/DogFart.yml
scrapers/GroobyNetwork-Partial.yml
scrapers/MindGeek.yml
scrapers/OldGoesYoung.yml
scrapers/PaperStreetMedia.yml
scrapers/RealityKingsOL.yml
scrapers/SweetyX.yml

Also add familysinners, shewillcheat and groobyvr to existing scrapers

Add Oldgoesyoung (Covers trickyoldteacher and spoiledvirgins)

---

SCRAPERS-LIST.md
scrapers/GirlsOutWest.yml

Adding gallery scraper. To use go to the performer's page and find the gallery url.
This site now has an ok button before accessing the site so this needs the single click support.

Updating GirsOutWest scraper.

---

SCRAPERS-LIST.md
scrapers/Dickdrainers.yml

Add dickdrainers xPath scraper

---

scrapers/stash-sqlite.py

Updating the stash sqlite scraper to dump images from the database to a local directory and provide an image url.
This requires some configuration in stash to map this output directory to a custom folder in stash.
add the following to config.yml to map the image export directory to http://127.0.0.1:9999/custom/stash_sqlite/xxxx.jpg
custom_served_folders:
/stash_sqlite: /root/.stash/stash_sqlite

Updating the stash sqlite scraper to dump images from the database.

---

scrapers/javlibrary.yml
scrapers/r18.yml

Some words are not sure...
For Javlibrary:
- Changed the regex for JG
- Edited the regex for the date (I don't know why but yesterday the regex stopped working)
_RIP your debug log file if you use this scraper because 200 regex replace take some places 😋_

Update censor list for R18

---

SCRAPERS-LIST.md
scrapers/FreeonesStore.yml

Add store.freeones.com xPath scene and movie scraper

---

SCRAPERS-LIST.md
scrapers/insex.yml
scrapers/insexOL.yml

Added some URLs to insex.yml. 
I've tested it on a few scenes for each added URLs and didn't see any problems. 
insex.yml passes the project's validation.

Insex update

---

SCRAPERS-LIST.md
scrapers/chastitybabes.yml

added xpath scraper for chastitybabes.com

added scraper for chastitybabes.com

---

SCRAPERS-LIST.md

Due to the script's use of f-strings, it requires Python v3.6 as a minimum.

specify specific python version required

---

SCRAPERS-LIST.md
scrapers/LewRubens.yml

added xpath scraper for lewrubens.com

added scraper for lewrubens.com

---

scrapers/MindGeekAPI.py
scrapers/MindGeekAPI.yml

- You need to set the URL (You don't need to save, just be in the field.)
I am not sure about the UserAgent... (You don't need it to have the request work)
I guess the image can be wrong too... (Maybe if the scene is not full HD ?)
Tested on Python 3.9.1
Tested with Realitykings, Brazzers, DigitalPlayground
-------
If you want to save the JSON, write - logJSON in the .yml
```yaml
sceneByFragment:
action: script
script:
- python
- MindGeekAPI.py
- logJSON
```

MindGeek API (Python)

---

scrapers/Kink.yml

Best effort solution to descriptions with lists like mentioned in #123:
https://www.kink.com/shoot/5116

Best effort solution to descriptions with lists on thetrainingofo

---

scrapers/Teamskeet.yml
scrapers/TeamskeetAPI.py

- Renamed the script `JSON` to `API` (So it's look like other script that use a API) 
- Changed where the JSON is stocked (Now next to the "scraper" folder e.g: \.stash\scraperJSON\Teamskeet)

Update Teamskeet Script (Rename + Json Folder)

---

scrapers/Spizoo.yml

Performer wasn't working for firstclasspov, so found probably more safe selector.

Update Spizoo.yml (Perf & Tags Selector)

---

scrapers/Mylked.yml
validator/scraper.schema.json

- fix Mylked - missing `with` on regex replace
- support `ValueRandom` in cookies from recent PR (`https://github.com/stashapp/stash/pull/1122`)
- set required properties on objects and allow all properties when used as sub-objects

[meta] update schema

---

scrapers/AdultimeAPI.py
scrapers/AdultimeAPI.yml

Try to find your scene, work best with original file from this network. 
- Setting a URL can be inaccurate because the ID is different by site. If you get the wrong scene, try to remove the url (you can add it back when the scraping is done)

Adultime API scraper (Python script)

---

validator/scraper.schema.json

Support https://github.com/stashapp/stash/pull/1150

feat(schema): support url query replace

---

SCRAPERS-LIST.md
scrapers/SARJ-LLC.yml

<del>This needs a custom version `https://github.com/stashapp/stash/pull/1150` to work properly. (binaries here <https://github.com/stashapp/stash/actions/runs/595500176>)
I will update the list with a version req when thats available
If anyone wants to try with a `normal` version they would need to replace `{url}` with `{title}` in the scraper , paste the URL in the TITLE field in stash and do a scrape with</del>
Stash version >= v0.5.0-17 is required

Switch to a JSON scraper for SARJ-LLC (metartnetwork)

---

scrapers/MindGeekAPI.py

Using the homepage broke the script...

Revert MindGeekAPI.py

---

SCRAPERS-LIST.md
scrapers/1pondo.yml

Switches to a JSON based scraper.
Requires stash >= 0.5.0-17 for scene by URL to work
For the scrape with to work it expects the movie_id  to be present in the filename  (123456_123 or 123456.123 or 123456-123 are detected)

Switch to a JSON scraper for 1pondo

---

SCRAPERS-LIST.md
scrapers/lethalpass.yml

This site contains a lot of scenes as well as exclusive sites.
If you scrape an exclusive site scene it will show up in the scrape with the studio
If you scrape a scene which is a scene from a dvd the studio will be blank with the scrape.

add lethalpass.yml

---

SCRAPERS-LIST.md
scrapers/jpsites.yml
scrapers/karatmedia.yml

This covers off 17 different sites under the same network.
I have not mapped their names as they come out ok as is but if you would like me to map them then shout out.
If there is not a defined model the site lists them as Japanese AV Model , I have left it as that as the undefined models can then be grouped other than that it lists the actual model.

add karatmedia.yml  xPath scene scraper

---

validator/scraper.schema.json

Support https://github.com/stashapp/stash/pull/1132

[validator] support performer tags

---

SCRAPERS-LIST.md
scrapers/sapphix.yml

Include 4 sites under the same network, Sapphix network.

add sapphix.yml

---

SCRAPERS-LIST.md
scrapers/ATKExotics.yml

Add cookies for ATKExotics
Since i used the ValueRandom stash >= 5.0-3 is needed
If anyone wants to use it with an older version make sure to switch 
`ValueRandom: 43` with an actual random value `Value: actualrandomvalue_probablybettertobe43chars`

Fix atkexotics (add cookies)

---

.github/workflows/validate.yml
validator/index.js

Adds a super-simple GitHub Actions workflow to validate the scrapers on push to master branch and pull requests to master.
Actions might need to be enabled in the repository settings first in order for it to work.

[validator] add workflow

---

SCRAPERS-LIST.md
scrapers/bellapass.yml

Covers off 14 sites under the bellapass umbrella.
I have mapped some of the sites because they clashed with the name's but if you feel those mapped don't need to be just remove them.

add bellapass.yml

---

scrapers/PureTaboo.yml

was pulling incorrect scene title data

fix title in Puretaboo

---

SCRAPERS-LIST.md
scrapers/MindGeek.yml

Removes a lot of sites that now redirect to mofos, realitykings
Adds milfed.com
Uses data from a script selector where it is possible for the scene scraper

MindGeek fixes

---

SCRAPERS-LIST.md
scrapers/porncz.yml

tested 4 scenes from each site with it all working ok.
Good luck testing all the sites lol. :-)

add porncz.yml

---

scrapers/MissaX.yml

Update details and make a bit more unbreakable. (well maybe)

Update MissaX.yml 

---

SCRAPERS-LIST.md
scrapers/hussiemodels.yml

This combines [https://github.com/stashapp/CommunityScrapers/pull/432](url).
I did look at Dickdrainers that was mentioned but most of the layout is different.

add hussiemodels.yml

---

SCRAPERS-LIST.md
scrapers/HobyBuchanon.yml

Add HobyBuchanon xPath scraper

---

SCRAPERS-LIST.md
scrapers/Vip4K.yml
scrapers/vip4k.yml

Covers 10 sites out of 13 under the umbrella of vip4k.
Some have tags, performers some don't include them just Title, and description.
Have image pulled from all sites.
Slight variation in most of them for Title and or details but all are covered. 
You would think they could have kept them all standard.

add vip4k.yml

---

SCRAPERS-LIST.md
scrapers/MyDirtyHobby.yml

A scraper mostly from @djmuell 's xpaths in #452 
requested from #73

Add MyDirtyHobby xPath scene scraper

---

SCRAPERS-LIST.md

Scraper list fixes

---

scrapers/TexasBukkake.yml

Feel free to change anything if it is wrong. For example the studio title, which I just "fixed".
Works fine for me.

Added Texas Bukkake

---

SCRAPERS-LIST.md
scrapers/Catalina Cruz.yml

This is part of a 15 site umbrella but they are all different.

add CatalinaCruz.yml

---

SCRAPERS-LIST.md
scrapers/LexiDona.yml

This one is part of the puffy network but the layout is very different.

add LexiDona.yml

---

validator/scraper.schema.json

Adds support for https://github.com/stashapp/stash/pull/1273

[validator] add support for `driver.headers`

---

SCRAPERS-LIST.md
scrapers/Oldje.yml

A redo of this, Tested with old and new scenes on both sites and seems to work ok.
Date is present on one site but not the other.
In theory should be able to close the other PR of this site.

add Oldje.yml

---

SCRAPERS-LIST.md
scrapers/JoyBear.yml

At least its not multiple sites. lol

add Joybear.yml

---

SCRAPERS-LIST.md
scrapers/Jhdv.yml

10 sites that are the same layout under this umbrella.

add Jhdv.yml

---

SCRAPERS-LIST.md
scrapers/MaxHardcore.yml

Bit of a strange site this one. Sometimes it presents a video and other times it presents the preview images.
Some time's the preview image is large like below and sometimes small. Luck of the draw it seams sometimes.
[https://www.max-hardcore.com/video/vivanica-from-the-mall-gets-her-ass-violated-by-max-hardcore-act-one-4339.html](url)

add MaxHardcore.yml

---

SCRAPERS-LIST.md
scrapers/HollyRandall.yml

Not much  in the way of descriptions, some here and there.

add HollyRandall.yml

---

SCRAPERS-LIST.md
scrapers/Hotmovies.yml

This was put together based on a request.
May need a bit of refinement but its a start and does work although I have not done extensive testing
So it's a case of feel free to go nuts in making changes.

add Hotmovies.yml

---

SCRAPERS-LIST.md
scrapers/FFCSH.yml
scrapers/ffcsh.yml

Another multi site, have fun lol

add ffcsh.yml

---

scrapers/Babepedia.yml

Only select existing profile pictures from babepedia with option of pulling site logo if none exist

babepedia profile image selection

---

SCRAPERS-LIST.md
scrapers/BoppingBabes.yml

Could not find a way or figure out if it was possible to add a date.

add BoppingBabes.yml

---

SCRAPERS-LIST.md
scrapers/Cospuri.yml

No title that I am able to find.

add Cospuri.yml

---

SCRAPERS-LIST.md
scrapers/Pawged.yml

add Pawged.yml

---

SCRAPERS-LIST.md
scrapers/Hentaied.yml

Man what a crazy site with both content and layout.
Did the best I could and I think I have covered off everything , Have done a lot of testing and get results on all scrapes.

add Hentaied.yml

---

SCRAPERS-LIST.md
scrapers/MongerInAsia.yml

A requested site from [https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-834324532](url)

add MongerInAsia.yml

---

SCRAPERS-LIST.md
scrapers/ClubSeventeen.yml

add in clubsweethearts.com.
I didn't bother adding in the studio as it all references clubseventeen.  
Just add it in if you want to.

Clubseventeen update

---

SCRAPERS-LIST.md
scrapers/GASM.yml

This has Scene's from a lot of major sites.
I have put the studio from where the scene has come from if you prefer the studio to be GASM just change it :-)

add Gasm.yml

---

SCRAPERS-LIST.md
scrapers/Pinkoclub.yml

I know its short on details but does have some and may be useful if somebody needs it.

add Pinkoclub.yml

---

scrapers/SARJ-LLC.py
scrapers/SARJ-LLC.yml

Some improvements on the API based SARJ-LLC scraper. These are:
* Fixing "random" 404 errors when scraping a model
* Converting more information from a model to a performer
* Supporting searching models by name (kind of a hack, but seems to work fine)
Note that the combination of searching a performer by name / fragment doesn't properly work in combination with Tags. This as the tags aren't properly handled by stash which means they aren't converted to (possible) existing tags and thus are listed as new tags, but adding them by clicking the tag / + results in an error for the tag already existing. This is fixed in stashapp/stash#1387

Sarj llc improvements

---

SCRAPERS-LIST.md
scrapers/PegasProductions.yml

Their site layout sucks big time.

add Pegasproductions.yml

---

scrapers/LoveHerFeet.yml

The script this used to scrape from no longer exists. It is actually much simpler to scrape the image than it was before.

fix image on loveherfeet xml scraper

---

scrapers/Mylf.yml

They added tags to the scenes.
_Issue:_
There is a comma as tags (tried using replace regex, it will give you a blank tag)
-------------
Using regex replace for the image to get a HD image (1280x720) instead of mid quality (765x431)

Update Mylf.yml (Tags)

---

SCRAPERS-LIST.md
scrapers/FamilyTherapyXXX.yml

Add momcomesfirst to FamilyTherapyXXX

---

SCRAPERS-LIST.md
scrapers/AmateurAllure.yml

Add swallowsalon to AmateurAllure.yml

---

SCRAPERS-LIST.md
scrapers/TACAmateurs.yml

add TACAmateurs.yml

---

SCRAPERS-LIST.md
scrapers/MaxHardcore.yml
validator/scraper.schema.json

requires a specific stash version from [here](https://github.com/stashapp/stash/pull/1399)

Add date to MaxHardcore

---

SCRAPERS-LIST.md
scrapers/SissyPov.yml

add SissyPov.yml

---

SCRAPERS-LIST.md
scrapers/Madou.yml

This PR adds scraping support for an unofficial listing of content from Madou Media studio.

Add Madou Media scraper

---

SCRAPERS-LIST.md
scrapers/MVG.yml

The issue with this one is that some of the site's they have screwed the date up. On the scene's page it show the correct date but when you go into the actual scene they have the date as 1969-12-31.
If you want just cut out the date altogether.

add MVG.yml

---

SCRAPERS-LIST.md
scrapers/XConfessions.yml

Add XConfessions xPath scene, movie scraper

---

SCRAPERS-LIST.md
scrapers/InterracialPass.yml

InterracialPass.yml to use URL to scrape scene by scene

add InterrcialPass.com to html scene scrapers

---

scrapers/vixenNetwork.py

_Reported on Discord._
The location of the data was changed, kept the old one just in case (since I didn't check all sites under the Vixen umbrella).
Also added a stack trace in case of an exception.
Tested on `Deeper` and `Tushy Raw`.

Fix Vixen scraper

---

SCRAPERS-LIST.md
scrapers/POVR.yml

Request from #73 (end of thread)
Covers all 18 studios on the site.
I have not removed WankzVR or MIlfVR as they are sites on their own.
Date is a bit Janky but does work, Change it if you want a better way to pull it :-)

add POVR.yml

---

SCRAPERS-LIST.md
scrapers/IWantClips.yml

Create a new scraper for the IWantClips store

Add IWantClips to the scrapers.

---

scrapers/RealityKingsOL.yml

fixes image for transangels, reported from #123

Fix image part for transangels

---

scrapers/MyDirtyHobby.yml

Fixes MyDirtyHobby  from #123 
Now uses the `script` part to get all meta
It might need some more regex replaces for the html escaped chars in the  description

Fix MyDirtyHobby

---

scrapers/TeamskeetAPI.py

#123 Thanks PhantomEight for reporting it 😄 
Using to a regex to remove useless thing in the date because it's annoying to work with.

Fix date for Teamskeet

---

SCRAPERS-LIST.md
scrapers/GammaEntertainment.yml

`WickedMovies.yml` left as is, for scraping movies as scenes.

GammaEntertainment: support Wicked movies

---

SCRAPERS-LIST.md
scrapers/ATKHairy.yml

Add site atkpetites.com as per [https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-872711088](url)

Atkhairy update

---

SCRAPERS-LIST.md
scrapers/BabeArchives.yml

per request [https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-871906613](url)

add BabeArchives.yml

---

SCRAPERS-LIST.md
scrapers/PlayWithRae.yml

Most of the scenes don't have a description but a few do. This does pick them up
i.e [https://playwithrae.com/trailers/Shower-with-Jayln-Part-1-Video.html](url)

add PlayWithRae.yml

---

SCRAPERS-LIST.md
scrapers/DigitalDesire.yml

As requested [https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-871906613](url)

add DigitalDesire.yml

---

SCRAPERS-LIST.md
scrapers/Waybig.yml

As requested on discord.
Covers scenes and performers.

add Waybig.yml

---

SCRAPERS-LIST.md
scrapers/Only3xGirls.yml

I was going to update Only3xGirls but it appears I never submitted it in the  first place. So erm yeah dunno what happened there.
Anyway this adds that site and another.

add Only3xGirls.yml

---

SCRAPERS-LIST.md
scrapers/PaperStreetMedia.yml

Added freeusemilf.com to the list of website supported for this scrapper

PaperStreeMedia: Add FreeuseMilf

---

scrapers/AdultimeAPI.py

Should give URL scraping better result.

Update AdultimeAPI scraper (byURL)

---

SCRAPERS-LIST.md
scrapers/GirlsUnderArrest.yml

This is the one you fixed up that I put on discord :-)

add GirlsUnderArrest.yml

---

SCRAPERS-LIST.md
scrapers/SubspaceLand.yml

Added xpath scraper for subspaceland.com

Subspaceland

---

scrapers/JavLibrary_python.py
scrapers/JavLibrary_python.yml
scrapers/r18.yml

Yet more censor word for JAV

---

SCRAPERS-LIST.md
scrapers/DevilsTgirls.yml

Requested on Discord. I also added in gallery and movie as well, It did have performers but not really enough info worth getting.

add DevilsTgirls.yml

---

SCRAPERS-LIST.md
scrapers/CruelGirlfriend.yml

xPath scraper for CruelGirlfriend (cruelgf.com) scenes

Add CruelGirlfriend xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/CollegeUniform.yml

add CollegeUniform

---

scrapers/ManyVids.yml

The current implementation fails when there's a link or the little star icons that manyvids lets models put in their text. This pulls a cleaned version from the meta description tag.
Also currently the profile url loses the protocol and host, this fixes it.

Manyvids fix profile url and description

---

SCRAPERS-LIST.md
scrapers/SwallowBay.yml

add SwallowBay.yml

---

scrapers/JavLibrary_python.py
scrapers/JavLibrary_python.yml

Instead of having a single mirror, it will run a check of all site to get the one without Protection.
Probably need some more test just be sure.

Update Jav Python

---

scrapers/r18.yml

They updated their movie page, if you want to use Xpath i think you need CDP now.
Anyways using their API so changed the scraper into a JSON one. 
Only the movie page is changed atm. Search, serie still work as before

Update r18.yml (Using API)

---

SCRAPERS-LIST.md
scrapers/NakedSword.yml

As per requested on Discord.
Covers Scenes and Movies.
Look and no following-sibling::text() , hahahahahaha

add NakedSword

---

scrapers/vixenNetwork.py
scrapers/vixenNetwork.yml

Changed how the json result was made to prevent error. 
Look like tag are removed atm. (at least on Vixen)

Update Vixen python

---

SCRAPERS-LIST.md
scrapers/GroobyNetwork-Partial.yml

Grooby: Add TGirls.porn

---

SCRAPERS-LIST.md
scrapers/GymRotic.yml

add GymRotic

---

SCRAPERS-LIST.md
scrapers/MenAtPlay.yml

add MenAtPlay.yml

---

SCRAPERS-LIST.md
scrapers/SmokingMina.yml

add SmokingMina.yml

---

SCRAPERS-LIST.md
scrapers/TrikePatrol.yml
scrapers/TukTukPatrol.yml
scrapers/VegasDreamsLLC.yml

- Add TrikePatrol.yml xPath scene/performer scraper
- Add TukTukPatrol.yml xPath scene/performer scraper
There is a combined scene scraper for these sites already, but it doesn't include performer scrapers.

Add TrikePatrol.yml / TukTukPatrol.yml xPath scene/performer scrapers

---

scrapers/pornworld.yml

Not sure for title if we keep the `featuring [MALE ACTOR]`
Edit: Just saw that there is already a PR about Pornworld (#649) so idk what to do 🤷

Update pornworld.yml (Xpath)

---

SCRAPERS-LIST.md
scrapers/AdultimeAPI.py
scrapers/AdultimeAPI.yml

- Dropped the local support
- Probably better result using fragment
- Look better 😄

Rework AdultimeAPI scraper

---

scrapers/MindGeekAPI.py
scrapers/MindGeekAPI.yml

- Dropped local support
- Look better

Rework Mindgeek Scraper

---

scrapers/ThePornDB.yml

Fixing ThePornDB.yml (Perf scene)

---

scrapers/Babepedia.yml

Update Babepedia.yml (Death date)

---

SCRAPERS-LIST.md
scrapers/MilfTugs.yml

- Add MilfTugs.yml xPath scene/performer scraper

Add MilfTugs.yml xPath scene/performer scraper

---

SCRAPERS-LIST.md
scrapers/LustReality.yml

add LustReality

---

SCRAPERS-LIST.md
scrapers/TabooHeat.yml

This was a request I only got around to and I forgot where it came from.
If you requested this sorry its taken some time but better late than never

add TabooHeat.yml

---

validator/index.js
validator/scraper.schema.json

Support https://github.com/stashapp/stash/pull/1712

validator: support `sceneByName`

---

SCRAPERS-LIST.md
scrapers/vixenNetwork.yml

Slayed is Vixen Network's latest site. The existing scraper still works for existing sites in addition to the new one.

add slayed to vixen scraper

---

SCRAPERS-LIST.md
scrapers/Fit18.py
scrapers/Fit18.yml

Switched to python/cloudscraper as Fit18 now uses CF bot detection
(edit: to get scene urls access the sites `/models` page first)

Switch to python for Fit18

---

SCRAPERS-LIST.md
scrapers/ThePornDB.yml

Using the PornDB `_id` to prevent having duplicate title and get ignore by Stash.

Update ThePornDB.yml (SearchByName)

---

SCRAPERS-LIST.md
scrapers/VRHush.yml
scrapers/VirtualTaboo.yml
scrapers/WankzVR.yml

Now with scene scraper and movie scraper. Basically all info is successfully extracted.

Update VirtualTaboo.yml, WankzVR.yml and VRHush.yml

---

SCRAPERS-LIST.md
scrapers/JavLibrary.yml

- Update the mirror list too
Btw should we keep the CDP here ? it's not really useful against cloudflare...

Update JavLibrary.yml (SearchByName)

---

scrapers/AdultimeAPI.py
scrapers/AdultimeAPI.yml

Update AdultimeAPI (SearchByName)

---

SCRAPERS-LIST.md
scrapers/JavLibrary_python.py
scrapers/JavLibrary_python.yml

Only search on Javlibrary not r18.

Update Javlibrary Python (sceneByName)

---

SCRAPERS-LIST.md
scrapers/TeenMegaWorld.yml
scrapers/TmwVRnet.yml

The old twmvrnet entry from TeenMegaWorld.yml doesn't work.
It includes scene scraper and movie scraper.

Added TwmVRnet.yml

---

SCRAPERS-LIST.md
scrapers/CzechVR.yml

It used to retrieve too many tags. Some are repetitions. Cover image fixed.
Added movie scraper for who like to manage files with movies instead of scenes.

Fix tags and image problems, added movie scraper (CzechVR).

---

SCRAPERS-LIST.md
scrapers/PaperStreetMedia.yml

Also small syntax fix for momswap.

Adding pervtherapy and sisswap to PaperStreetMedia.yml

---

README.md

Not sure about the 
> the button will be active

Update README.md (For latest dev)

---

scrapers/IMDB.yml

Adding IMDB scraper, they do have some adult performers there.

Adding IMDB scraper, they do have some adult performers there.

---

SCRAPERS-LIST.md
scrapers/PremiumBukkake.py
scrapers/PremiumBukkake.yml

add premiumbukkake.com scraper. It uses the `free.premiumbukkake.com` domain to get scene data

add premiumbukkake scrapper

---

SCRAPERS-LIST.md
scrapers/Nubiles.yml

add brattymilf

---

SCRAPERS-LIST.md
scrapers/Z-Filmz-Originals.yml
scrapers/zfilmzoriginals.yml

add z-filmz-originals

---

SCRAPERS-LIST.md
scrapers/PornhubPremium.yml

add pornhubpremium.com scraper.
I had thought of adding pornhubpremium.com to the existing pornhub.yml scraper, however i couldn't get to differentiate the SceneByFragment between pornhub and pornhubpremium.

add pornhubpremium scraper

---

scrapers/LetsDoeIt.yml

The regex to remove the appended text on the title is now fixed

Fix removal of suffix text on letsdoeit

---

SCRAPERS-LIST.md
scrapers/TheScoreGroup.yml

Tested with galleries under all child sites except pornmegaload.com - could not locate gallery on that site, but assuming since all other sites in this scraper have the same layout, it should be compatible there too.

Added gallery support to TheScoreGroup.yml

---

scrapers/LetsDoeIt.yml

I've only encountered one of them so far, and as regex can be time consuming, only implemented this one.

Add decoding of some character on letsdoeit details

---

scrapers/xbvrdb.py
scrapers/xbvrdb.yml

Adding gallery support for the xbvr scraper.
Some sites can include a gallery of images with the scene so I have updated the scraper to also include gallery metadata.
This works for virtualtaboo.com, wankzvr, milfvr etc and may be useful for others.

Xbvr scraper support  for galleries 

---

scrapers/CopyFromScene.py
scrapers/CopyFromScene.yml

This is useful when there is a scene with an included zip file.
In stash get the metadata for the scene, add a gallery and save the scene.
Then go to the gallery and use this scraper to fetch the metadata for that scene.

This gallery scraper will copy metadata from a linked scene.

---

scrapers/IFeelMyself.py
scrapers/IFeelMyself.yml

- Use standard library `re` instead of 3rd party `regex` and fix some regex patterns.
- Tested `sceneByURL`.
- Rename `ifeelmyself.yml` ➡️ `IFeelMyself.yml`
- Remove unused imports
- Remove trailing spaces
- Update `sceneByFragment` logic to fix search feature.
- Tested with a `f15701-21227.mp4` title (like the regex suggests).

IFeelMyself fixes

---

scrapers/MilfVR.yml
scrapers/NaughtyAmerica.yml

Added static studio for MilfVR
Improved image scraping for VR Scenes from NaughtyAmerica

Added Studio to MilfVR and aditional image extraction from NaughtyAmerica for VR scenes

---

SCRAPERS-LIST.md
scrapers/Babes&Stars.yml

- performerByURL: Fixed url to include https://
- Fixed cup replace method
- Added description
This website is not updated but it contains measurements and cup sizes for former performers I couldn't find in IAFD.

Added Babesandstars.com

---

SCRAPERS-LIST.md
scrapers/AVE.yml

As stated in the scraper the search by id is a bit picky. It needs the exact id eg `XXX-01`

AVEntertainments xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/VirtualPorn.yml

VirtualPorn.com XPath scene scraper

---

SCRAPERS-LIST.md
scrapers/FuckedHard18.yml

Adds a FuckedHard18.com scraper as requested in #73.
The scraper is tested and validated. However, this is the first scaper that I add to the repo so if someone could double-check that would be appreciated.

FuckedHard18 Scraper

---

README.md

I'm not really happy with the term i used... So help me 🥲

Update README.md (Update Stable/Dev)

---

SCRAPERS-LIST.md
scrapers/Nympho.yml

Fix swallowed, mentioned in #123

Fix swallowed.com details (Nympho.yml)

---

SCRAPERS-LIST.md
scrapers/GammaEntertainment.yml

Genderx name fix

---

SCRAPERS-LIST.md
scrapers/Danni.yml

Another site to add to the growing list :-)

add Danni.com

---

SCRAPERS-LIST.md
scrapers/MindGeek.yml
scrapers/RealityKingsOL.yml

Move TransAngels to MindGeek.yml

---

scrapers/ThePornDB.yml

Add missing date field to scene search results to simplify the selection of the correct scene.

[ThePornDB] Add date to search results at sceneSearch

---

scrapers/AdultEmpire.yml
scrapers/Pornhub.yml

Adds sceneByName searches for AdultEmpire.

Adultempire sceneByName Searching

---

scrapers/Traxxx.yml
scrapers/traxxx_interface.py

Various traxxx interface fixes and enhancements
- removed box module (not included in official docker and not needed)
- added performers in scenes
- fixed issues when handling empty tags
- removed tags from scene search results as they took too much space
- added studio and performers in scene search results

Traxxx fixes

---

scrapers/HelixStudios.yml

Adds sceneByName and performerByName functionality to Helix Studios scraper
Improves description scraping so that some descriptions are not missed
Adds canonicalURL field to scenes and performers

Improve HelixStudios scraper

---

SCRAPERS-LIST.md
scrapers/GammaEntertainment.yml

im not sure if this is the correct way to do it, but it works ;-)

add famedigital.com movies

---

SCRAPERS-LIST.md
scrapers/VRLatina.yml

For website vrlatina.com, it has 3 xpath scrapers: scene, movie and performers. When scrape a scene with a URL, it can add a movie and the performer with their URLs. Then later you can scrape the movie and performer by URLs.
It seems their website format is pretty consistent. Scraped a few scenes and saw nothing wrong.

Add VRLatina.yml

---

SCRAPERS-LIST.md
scrapers/ComicInfoXML.py
scrapers/ComicInfoXML.yml
scrapers/py_common/graphql.py

No idea if this belongs here or in another repo as it is a local XML file scraper rather than a site scraper so feel free to redirect me to the right place!

Local ComicInfo.xml file

---

scrapers/Algolia.py
scrapers/Algolia_Adultime.yml
scrapers/Algolia_disruptivefilms.yml
scrapers/Algolia_mypervyfamily.yml
scrapers/Algolia_touchmywife.yml
scrapers/Algolia_zerotolerancefilms.yml
scrapers/py_common/graphql.py

Should prevent user to try to do `pip install py_common`

[Algolia] Explain py_common (Catch error)

---

SCRAPERS-LIST.md
scrapers/GammaEntertainment.yml
scrapers/NaughtyAmericaVR.yml

hi,
a little help whit the tiltle-regex would be realy nice (im to dumb).
At the Studioname im not sure if with spaces in the name or without....
Rest seems to work fine.

Add new Site: NaughtyAmericaVR.com

---

SCRAPERS-LIST.md
scrapers/Czechav.yml
scrapers/JapanHDV.yml

#https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-1000327498_

Added Czecgav sites

---

scrapers/HimerosTV.yml

Himeros fix

---

SCRAPERS-LIST.md
scrapers/UltraFilms.yml

Add UltraFilms

---

SCRAPERS-LIST.md
scrapers/Fit18.py
scrapers/Fit18.yml

Requested in discord
Scraper by @Belleyy

Add Thicc18 support to Fit18 scraper

---

scrapers/vixenNetwork.py
scrapers/vixenNetwork.yml

Now uses the graphql endpoint for all sites

Fix vixenNetwork scraper

---

SCRAPERS-LIST.md
scrapers/Williamhiggins.yml

Original was pasted in the discord channel
Image part was updated as 2 sites use relative urls for the image part

Update WilliamHiggins (Add more sites)

---

README.md

Reverts stashapp/CommunityScrapers#868

Revert "Update Readme"

---

SCRAPERS-LIST.md
scrapers/GotFilled.yml
scrapers/KBProductions.py
scrapers/KBProductions.yml

- Content is dynamically loaded, so it needs to use CDP
- There is an "age > 18" prompt on the website, it's bypassed using the `gotfilled_warning_ok` cookie

Add GotFilled

---

scrapers/ManyVids.yml

* update title xpath to correct failures
fixes #876

Update manyvids scraper to fix titles not coming through

---

SCRAPERS-LIST.md
scrapers/Kink.yml

It seems that kink now detects and 403s the plain scraper
Switching to CDP seems to work ok

Update Kink, switch to CDP

---

scrapers/ATKExotics.yml

Mentioned and tested in the discord channel

Fix image pp in ATKExotics scaper

---

SCRAPERS-LIST.md
scrapers/PornstarPlatinum.yml

Not the best way to get a performer name...

PornstarPlatinum scraper (Xpath)

---

scrapers/MindGeek.yml

Fixes an issue with tags and commas mentioned in #123

Fix tags pp in MindGeek scraper

---

scrapers/JacquieEtMichelTV.py
scrapers/JacquieEtMichelTV.yml

Updated the selectors to work again.

Fix JacquieEtMichelTV scraper

---

SCRAPERS-LIST.md
scrapers/GammaEntertainment.yml

Add activeduty as supported performer Url to GammaEntertainment.yml

---

SCRAPERS-LIST.md
scrapers/SARJ-LLC.py
scrapers/SARJ-LLC.yml

This adds support for Domai and GoddessNudes (SARJ sites).
It also fixes an incorrect UUID for Erotic Beauty.

Add Domai and GoddessNudes support

---

SCRAPERS-LIST.md
scrapers/FFCSH.yml

Thanks to BNKAI from discord to notice it works

Added  interracialpovs.com

---

SCRAPERS-LIST.md
scrapers/CorbinFisher.yml

validator passes
tested on a couple pages

Add performer support to CorbinFisher scraper

---

SCRAPERS-LIST.md
scrapers/SexMex.yml

Date scraping is bit iffy, but seems to work pretty well. 
It uses subscraper to find the date from the search results by using the scene title and selecting the first item

Add SexMex xPath scene and gallery scraper

---

SCRAPERS-LIST.md
scrapers/javdb.yml

Look like 9 has been replaced by 36

[XPath] Update javdb.yml (URL)

---

scrapers/kinkyfamily.yml

Fix kinkyfamily image

---

SCRAPERS-LIST.md
scrapers/Cospuri.yml

Performer page can now be scraped for some info.
Changing URL's accepted in line 5 and 10, so performer URL will not attempt to be scraped for a scene, vice versa.
My first time doing this, so hopefully this is fine.

Adding performer scraping in Cospuri.com

---

SCRAPERS-LIST.md
scrapers/TeasePOV
scrapers/TeasePOV.yml

There is probably a simpler way to do the scene date, but I'm a newbie.

Scene support for TeasePOV

---

SCRAPERS-LIST.md
scrapers/Killergram.yml

Requested from #73 
The title is mostly a hack, it seems to work though. Not sure if there is a better alternative

Add Killergram xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/YummySofie.yml

add YummySofie.com

---

scrapers/dc-onlyfans.py
scrapers/dc-onlyfans.yml

This is an extension on the work of @DefinitelyNotSpicy in https://github.com/stashapp/CommunityScrapers/pull/906, i just added more media types and seperated the sql querys for better debugging.
Thanks @DefinitelyNotSpicy for your work!
This PR makes https://github.com/stashapp/CommunityScrapers/pull/906 obsolete

changed dc-onlyfans for all possible media types

---

SCRAPERS-LIST.md
scrapers/JavHub.yml

The site seems to have duplicate scenes with different dates
Titles seem to be also performer names for most of the scenes  so for the search i list the duration (in the place of details) so that matching a scene is easier

Add JavHub xPath scene scraper

---

scrapers/Killergram.yml

Tweak map values according to comments from #913

Update Killergram.yml (tweak map values)

---

SCRAPERS-LIST.md
scrapers/MyCherryCrush.yml

This is my first time making a scraper let me know if there's anything that can be done better!

Add MyCherryCrush XPath Scene Scraper

---

SCRAPERS-LIST.md
scrapers/CrashpadSeries.yml

This is a fixed version of #925 . Sorry, screwed git up a bit there. I closed the other pull request and will remove that branch.
All previous comments addressed.

Add scraper for crashpadseries.com

---

scrapers/Teamskeet.yml
scrapers/TeamskeetAPI.py

From discord it seems that the api endpoint used by teamskeet uses now cloudflare
I replaced requests with cloudscraper, it will need some testing though

Use cloudscraper for Teamskeet

---

SCRAPERS-LIST.md
scrapers/TwoTGirls.yml

Tweaked version of a scraper pasted in discord channel

Add TwoTGirls xPath scene scraper

---

scrapers/Nympho.yml

Some of the sites have commas returned in the performer names.
Added a pp replace to fix the issue

Fix performer names for Nympho.yml

---

scrapers/ArchAngelVideo.yml

Fixed the scraper to work correctly on the site. Looks like the site may have changed none of the old links worked.

Fix ArchAngelVideo.yml

---

scrapers/CherryPimps.yml

pulls series name from scene/gallery URL, opted to prefix the series with `CherryPimps - ` as some of the series names are very short and could be mistaken for other things i.e. "Ginger"

add series name as studio name (CherryPimps.yml)

---

SCRAPERS-LIST.md
scrapers/DollsHub.yml

One of these sites was requested, it's made up of a few other sites under the same banner so thought I might as well add the lot of them.

add DollsHub

---

SCRAPERS-LIST.md
scrapers/FragileSlave.yml

Adds support for urls from fragileslave.com (title, date, img, tags, details).
Since it's my first scraper, please review a little bit more carefully :-)

add fragileslave.com url scraper

---

SCRAPERS-LIST.md
scrapers/EastBoys.yml

* Add EastBoys Scraper
* Update Scrapers List

Add EastBoys Scraper

---

SCRAPERS-LIST.md

Added blackmassivecocks, youngermommy, cumswappingsis and mom4k

Added numerous sites

---

SCRAPERS-LIST.md
scrapers/ZentaiDolls.yml

Requested on Discord. Early scene's have no performer listed.

add Zentai Dolls

---

SCRAPERS-LIST.md
scrapers/MatureNL.yml

Includes scene and gallery scraping.

Add Mature.nl

---

SCRAPERS-LIST.md
scrapers/KBProductions.yml

After beginning to poke at setting up a unique scraper for this, I realized the page matches up with the overall HTML structure of GotFilled, so I added the the URLs to the YML file locally and my test scrapes worked. If there's anything more in-depth I should investigate, please let me know.

Add inserted.com

---

SCRAPERS-LIST.md
scrapers/KBProductions.yml
scrapers/WillTileXXX.yml

I missed updating the last-updated date in #958. If that should be a separate PR to keep merges clean, let me know and I'll remove it from this PR and open a separate one.
As far as the date handling, the HTML element with the date has erroneous data that, as best I can tell, I'd need to regex out in order to pass into `parseDate` so it seemed like it'd make sense to cut out the step of passing it into the parser. If there's benefit to throwing into that postprocessor regardless, please let me know.

Add WillTileXXX

---

scrapers/data18.yml

Fixes various selectors/post processing

Update data18 scraper (fixes)

---

SCRAPERS-LIST.md
scrapers/xSinsVR.yml

Combined scene and gallery scrapers for xsinsvr.com and billiestar.com

Add xSinsVR scraper

---

scrapers/AdultEmpireCash.yml

Mentioned in #123 
Elegant Angel, severesexfilms and thirdworldxxx use anchors instead of spans for the  studio name

Fix studio selector for AdultEmpireCash

---

scrapers/LoveHerFeet.yml

now this one can be usable per item

add sceneByFragment to LoveHerFeet

---

SCRAPERS-LIST.md
scrapers/MariskaX.yml
scrapers/mariskax.yml

Add sceneByUrl and performerByUrl scraper for Mariskax.com

Add scrapers for mariskax.com

---

scrapers/PlumperPass.yml

Fixes details/title for plumberpass, mentioned in #123

Fix plumberpass

---

SCRAPERS-LIST.md
scrapers/RealityLovers.py
scrapers/RealityLovers.yml
scrapers/VegasDreamsLLC.yml

Adding a scraper for RealityLovers

Reality lovers

---

scrapers/r18.yml

If the item is in sold, the xpath wasn't correct.

Update r18.yml (Fix sale series)

---

scrapers/NaughtyAmericaVR.yml

Image selector now grabs a horizontal poster instead of a vertical one.

Updating Image selector for NaughtyAmericaVR

---

SCRAPERS-LIST.md
scrapers/JapornXXX.yml

Except for the image everything works from my testing. Any assistance is greatly appreciated.

Add xPath scraper for japornxxx.com

---

SCRAPERS-LIST.md
scrapers/LadyboyGold.yml
scrapers/VegasDreamsLLC.yml

Performer scraper for Ladyboy Gold

Add Ladyboygold scraper

---

scrapers/MenAtPlay.yml

fixes MenAtPlay mentioned in #123 
Found the updated scraper locally(only changed the details selector and date), dont remember where i got it from...

Fix MenAtPlay scraper

---

scrapers/py_common/graphql.py

Update graphql.py (Fix)

---

scrapers/UltraFilms.yml

Use a field with just the title instead of the title plus performs and video type.
Fix studio name to match Stashdb.

[UltraFilms] Fix title and studio

---

SCRAPERS-LIST.md
scrapers/AShemaleTube.yml
scrapers/VegasDreamsLLC.yml

performerByURL and sceneByURL using Xpath scrapers.

Adding scraper for ashemaletube.com

---

scrapers/Hegre.yml

Their site now lists scenes at /films instead of /movies, and the title text has a new class on it.
Added perform bio scraping.

[Hegre] Fix scene URL

---

SCRAPERS-LIST.md
scrapers/LustCinema.yml

Add LustCinema scrapper

---

SCRAPERS-LIST.md
scrapers/Freshmen.yml

Re-posting from Discord user @mankey123's post.

freshmen.net xPath scraper

---

SCRAPERS-LIST.md
scrapers/ChristianXXX.yml
scrapers/GroobyClub.yml

* fix broken pure-ts image selector
* improve groobyclub image selector
* add more compatible sites to GroobyClub.yml

improve groobyclub, purets image selectors

---

SCRAPERS-LIST.md
scrapers/Jeedoo.yml

Provides scene scraper & search, plus movie scraper.
Useful for older and obscure DVD and VHS releases not covered by adultempire or hotmovies

Add xPath scraper for Jeedoo.com

---

scrapers/ManyVids.yml

Manyvids changed their site a bit, changed the selector for the cover image

Minor fix to get the cover image on Manyvids

---

SCRAPERS-LIST.md
scrapers/AEBN.yml

Performer scraper for AEBN. 
Requested on Discord.

AEBN xPath performer scraper

---

scrapers/NewSensationsNetworkSites.yml

Mentioned by JustAnotherGuy in the discord channel

Add mapping for FOH in NSNS scraper

---

scrapers/JavLibrary_python.py
scrapers/JavLibrary_python.yml

#123 
The image from the XPath already contains the protocol

[Javlibrary python] fix image using search

---

SCRAPERS-LIST.md
scrapers/Hypnotube.yml

Add scene url scraper for hypnotube.com
Contains mostly Hypnosis, JOIs, PMVs, Feminization, Sissification and Bimbofication videos
Scrapes : 
- Title
- Details
- Image (From curated thumbnail, as shown in the search section of the site)
- Studio
- Name (poster's username)
- URL (poster's hypnotube profile url)
- Date
- Tags (From both Tags and Categories sections on the page)

Add hypnotube.com xPath scene scraper

---

scrapers/StasyQ.yml

Site changes, so I updated this to make it work...

Updated StasyQ works for Scenes and Performer scraping

---

SCRAPERS-LIST.md
scrapers/LoveHerFeet.yml

- BTS scenes have no video element *(& main scenes have no img)*
- added OR in image selector to handle eaither
- also this studio has rolled another site: LoveHerFilms
- which seems to be all their sites rolled into one place

LHF images for BTS + new URL

---

scrapers/dc-onlyfans.py
scrapers/dc-onlyfans.yml

This adds scraping for DC-Onlyfans galleries.
Works for me on Windows 11. I'm not sure if it would work on Unix cause I'm querying with the full path of the gallery using `.as_posix()`

[dc-onlyfans] Add gallery scraping

---

SCRAPERS-LIST.md
scrapers/PinkLabelTV.yml

Adds new scraper for pinklabel.tv, which hosts many 'indie' adult movies found nowhere else
Provides scene and movie scrapers

add scraper for pinklabel.tv

---

scrapers/WillTileXXX.yml

incorporated feedback from Belley, deleted recursive branch and submitted new PR.

Updated xpath for willtilexxx.com

---

SCRAPERS-LIST.md
scrapers/IWantClips.yml

Adding a performer scraper to the iWantClips scraper.
Scrape performer by:
- URL
- NAME
Fetches:
- Name (of profile)
- URL
- Profile Image
Sadly IWC doesn't provide much else in the way of information, but there are some performers which only seem to have a presence on IWC.

Iwantclips performers

---

SCRAPERS-LIST.md
scrapers/Xevunleashed.yml

Add scraper for https://xevunleashed.com/
Works as intented in all my tests.
Only thing I couldn't get better was the list of performers.
Unfortunately the performers are never listed in the page itself, only in the tags...
So either:
1. performers list = tags list 
2. no performers
I chose option 1 (similar to existing behaviour in Clips4sale scraper)

Add Xevunleashed

---

SCRAPERS-LIST.md
scrapers/GammaEntertainment.yml
scrapers/hussiemodels.yml

Added hotandtatted to hussiemodels.yml and scrapers-list

Hotandtatted

---

scrapers/ManyVids/ManyVids.py
scrapers/ManyVids/ManyVids.yml

Tweak id_match as mentioned in discord

ManyVids - Tweak id_match

---

SCRAPERS-LIST.md
scrapers/Putalocura.yml

[YML] Create Putalocura scraper

---

scrapers/Clips4Sale.yml

Add search scenes by name to Clips4sale.
Haven't touched the existing scene scraper.

Add search to Clips4sale

---

scrapers/SexBabesVR.yml

Fix date, studio name and details not being pulled

SexbabesVR scraper - fix date, desc ,studio

---

SCRAPERS-LIST.md
scrapers/VirtualRealPorn.yml

Fixed title naming  -  strip out VR Porn Video and vice versa from the other sites fro mthe network
+ added one more site VirtualRealAmateur to scraper

Update virtualrealporn network scraper

---

scrapers/JavLibrary_python.py
scrapers/JavLibrary_python.yml

return None if it gets no match so Hide unmatched scenes works

tagger change for JavLibrary Python

---

scrapers/LetsDoeIt.yml

*details xpath fix
+regex to remove Studio name at the end of a description
*image parse xpath fix

LetsDoeIt scraper fixes

---

scrapers/Clips4Sale.yml

applies the fix that @bnkai found on Discord

fix clips4sale images

---

SCRAPERS-LIST.md
scrapers/EliteBabes.yml

New Elite babes scraper

---

SCRAPERS-LIST.md
scrapers/LoveHerFeet.yml

_LH**Filmes**_ is like _3in1_ for LHF(eet), LHB & SLB, 
- added performer search & parse
- tested with 3 random f/ each site. 
- also LHB scene images have a different img selector ( _this is how or works_ )

LHF: performer search/scrape

---

SCRAPERS-LIST.md
scrapers/BondageCafe.yml

BondageCafe xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/BrandNewAmateurs.yml

Minimum information is available on the site. 
Requested here https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-1175113261

BrandNewAmateurs xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/JimWeathersArchives.yml

JimWeathersArchives xPath scene/performer scraper

---

SCRAPERS-LIST.md
scrapers/AmateureExtreme.yml

Adding `01-01` to the date since the website only provides the year. 
Requested here https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-1186344468

AmateureExtreme xPath scene scraper

---

SCRAPERS-LIST.md
scrapers/BJRaw.yml
scrapers/KBProductions.yml

Fixes KBP scraper reported in #1133
Switch back to a separate CDP scraper for BJRaw/GotFilled

Fix BJRaw/Gotfilled/KBP scrapers

---

scrapers/ThePornDB.yml

Adds `Details`, `Birthdate`, `Country`, `HairColor` and `Weight` to `ThePornDB`'s performer scraper
Weird that these items has been missing.

[ThePornDB/Performer] Add details, birthdate, country, haircolor and weight

---

scrapers/AShemaleTube.yml

Adding performerByName, sceneByName, and sceneByQueryFragment for Ashemaletube.

Ashemaletube search

---

SCRAPERS-LIST.md
scrapers/MindGeek.yml

RealityKings hasn't been scrape-able in a bit. After doing some testing, it appears to Just Work:tm: with the MindGeek scraper.

Fix Reality Kings scraping

---

SCRAPERS-LIST.md
scrapers/TransModelDatabase.yml

Supports performerByName and performerByUrl.  
tramsmodeldatabase only supports a mixed performer and scene search.  The performer search filter is based on the tease-model class.  Only the first page of results is processed.

Adding scraper for transmodeldatabase.com

---

SCRAPERS-LIST.md
scrapers/AssumeThePositionStudios.yml

CDP based scraper for assumethepositionstudios.com

Scraper for assumethepositionstudios.com

---

SCRAPERS-LIST.md
scrapers/MrBigFatDick.yml
scrapers/SexLikeReal.yml

Fix SexLikeReal description for some scenes.
Add URL to the output in case SexLikeReal redirects ours (for example slr/sceneId gets redirected to slr/title-sceneId)
Added YML schema comment at the top to enable VSCode (and some other editors) to validate while typing and offer suggestions.
See: [https://developers.redhat.com/blog/2020/11/25/how-to-configure-yaml-schema-to-make-editing-files-easier#schema_association_without_a_file_name_pattern](url)

Add MrBigFatDick. Fix SexLikeReal description for some scenes.

---

SCRAPERS-LIST.md
scrapers/XVirtual.yml
scrapers/xVirtual.yml

I sorted the scrapper list and it changed a few lines.
If not desired, I'll revert those changes and update the PR

Add xVirtual scrapper

---

scrapers/SpankBang.yml

Update to Spankbang to include scrapping upload date, and fix on the Studio

Add date to SpankBank

---

SCRAPERS-LIST.md
scrapers/Noodledude.yml

New scraper for https://www.noodledude.io/

Adding PMV creator NoodleDude's website

---

SCRAPERS-LIST.md
scrapers/Cockhero.yml

scrape title, date, studio/author, cover and tags from cockhero.info

Add scene scraper for cockhero.info

---

SCRAPERS-LIST.md
scrapers/FootFetishDaily.yml

new scraper (i am using to fill in [this studio](https://stashdb.org/studios/2bf9f72f-6a83-486c-a7f4-4ff70a1bb842) @ stashDB)

new FFD scraper

---

scrapers/SARJ-LLC.py
scrapers/SARJ-LLC.yml

- Adds director field for the scenes
- Use py_common
- Set `Unknown` performer country to None
- Minor fixes that should? cover what was mentioned in #123

Add director for SARJ-LLC scraper, minor tweaks fixes

---

scrapers/LegalPorno.yml

Regex examples https://regex101.com/r/RHyMTe/2

Add Code selector for LegalPorno.yml

---

SCRAPERS-LIST.md
scrapers/Rule34.yml
scrapers/Rule34Video.yml

The search by name only returns the results from the first page

Add Rule34Video xPath scene scraper

---

scrapers/LegalPorno.yml

In https://github.com/stashapp/CommunityScrapers/pull/1192 I forgot to solve the case where it grabs the full title if no code is available.

Update Code selector for LegalPorno.yml

---

scrapers/SexLikeReal.yml

This adds an alternate tags xpath, e.g. as seen in https://www.sexlikereal.com/trans/rock-hard-and-ready-to-roll-623

Improve sexlikereal

---

scrapers/ManyVids/ManyVids.py
scrapers/ManyVids/ManyVids.yml

Use higher res scene cover for ManyVids

---

SCRAPERS-LIST.md
scrapers/MeanBitches.yml

Adding a Mean Bitches scraper.
Scrape performer by:
- URL
Performer details:
- Name
- Image
Scrape scene by:
- URL
Scene details:
- Title
- Details
- Studio (fixed name & url)
- Performer
- Image
- Date
The performer was probably overkill but I wanted the practice and it was a nice to have.

Meanbitches scraper

---

SCRAPERS-LIST.md
scrapers/CzechVR.yml

This adds czechvrnetwork.com to the existing CzechVR scraper
Note:
- with the existing scraper, I get a 403 for https://www.czechvr.com/detail-1607-tending-garden
- with this change, I can scrape the corresponding scene URL https://www.czechvrnetwork.com/detail-1607-tending-garden

add czechvrnetwork.com

---

SCRAPERS-LIST.md
scrapers/ColbyKnox.yml

Submitting at the [request](https://discord.com/channels/559159668438728723/651418567475986432/1055009885865136179) of @dongfengweixiao 
Tested the scene scraper and everything works.

Add xPath scene scraper ColbyKnox.yml

---

SCRAPERS-LIST.md
scrapers/GroobyNetwork-Brazilian.yml

This adds a new scrapers for the Grooby Brazilian sites:
- brazilian-transsexuals.com
- braziltgirls.xxx
These sites share a common page structure that is different to the existing other Grooby site scrapers

add brazilian-transsexuals.com and braziltgirls.xxx

---

SCRAPERS-LIST.md
scrapers/Pinkoclub.yml

adds pinkotgirls.com scene scraper, e.g. https://www.pinkotgirls.com/videotrans/6575-due-giovani-culi-per-il-grosso-cazzo-di-renata-molina.php

add pinkotgirls.com

---

scrapers/CruelGirlfriend.yml

Fixes issues mentioned in #123

Fix CruelGirlfriend scraper

---

scrapers/Lustery.yml

I have fixed the issues with title, description, and performers, but tags, although work on Firefox console, are still not working in stash. Any help would be greatly appreciated.

Update class names of Lustery

---

SCRAPERS-LIST.md
scrapers/Strokies.yml

Request from https://github.com/stashapp/CommunityScrapers/issues/73#issuecomment-1397017274

Add Strokies.yml CDP scene scraper

---

scrapers/Xvideos.yml

Fix xvideos scene scraper

---

scrapers/MatureNL.yml

Fetch also the hidden tags behind a click.

Fetch all tags from Mature.nl

---

SCRAPERS-LIST.md
scrapers/Oreno3d.yml
scrapers/oreno3d.yml

oreno3d is a more polished frontend for ecchi.iwara.tv with some more detailed information.

Add scene scraper for oreno3d.com

---

scrapers/BelAmi.yml

Image Regex: Replacing with "Thumbnail8.jpg" gives the image resolution 484x272, "Thumbnail6.jpg" is a resolution of 960x540
Tags: pull down.
Code: Extract the studio code from a form field (it matches what is in the URL).

Update BelAmi.yml - change to larger image, add tags & studio code

---

scrapers/Clips4Sale.yml

Minor edits to get images working again on this scraper. Left the `clips4sale.com/search/clip` stuff alone since I honestly have no idea what this is for or how to use it, so I couldn't test it to make updates. Can make a further commit to fix that if anyone lets me know how to use it. :)

Fix Clips4Sale images on scene scraper and search

---

scrapers/HelixStudios.yml

Scene Image: use regex to switch the pulled image to a larger version.
Scene Director: pulled from the director class.
Scene Studio Code: extracted from the title image URL (Helix name all media files with the studio code), using regex to remove everything else in the URL.

HelixStudios.yml - Scene Scraper - increase image size, add director, add studio code

---

SCRAPERS-LIST.md
scrapers/LadyboyGold.yml

Add scene scraper that works on tour pages, e.g. https://ladyboygold.com/tour/show_video.php?galid=6635&section=1552&nats=MC4wLjYuNi4wLjAuMC4wLjA

add scene scraper for ladyboygold.com and tsraw.com

---

scrapers/Xvideos.yml

- Added sceneByFragment support
- Added scene Date field scraping
- Added scene Url field scraping
- Added more domains
- Fixed scene Studio scraping
- Capitalized scraper name

Improve Xvideos scraper

---

SCRAPERS-LIST.md
scrapers/DoTheWife.yml

Added dothewife.com scene scrapper for
- Title
- Performers
- Scene cover
- Tags
- Details

Added DoTheWife.com scene scraper

---

SCRAPERS-LIST.md
scrapers/ThisVid.yml

Gets title, image, tags and description. Date is not scraped as it's only publicly displayed relatively, and very vaguely at that (x years ago, x months ago etc.)

Add ThisVid xPath scene scraper

---

scrapers/PlayboyPlus.yml

Added ability to scrape pages behind paywall using "pbp-ma.playboy.com" formatted URL.

Added ability to scrape pages behind PlayboyPlus paywall

---

SCRAPERS-LIST.md
scrapers/LordAardvark.yml

This adds a scene and gallery scraper for lordaardvark.com which is requested in #73 
Scenes are listed at https://lordaardvark.com/films/
Scene examples:
- https://lordaardvark.com/films/overbreed-episode-0
- https://lordaardvark.com/films/maid-to-facefuck
Galleries are listed at https://lordaardvark.com/html/galleries.html
Gallery examples:
- https://lordaardvark.com/html/galleries.html?type=comic&gallery=comic_futashep_n3_2022
- https://lordaardvark.com/html/galleries.html?type=comic&gallery=comic_frozen_curvy

Add lordaardvark.com scraper

---

SCRAPERS-LIST.md

Corrected a few small items in scrapers list:
- Removed extraneous '.com' from masqulin.com entry.
- Added "Gay" note for noirmale.com and seancody.com

Small fixes in scrapers list

---

scrapers/DorcelClub.yml

Added the director field to the scene scraper.  The existing director logic in the movie scraper section also works for scenes.

Add director field to DorcelClub scene scraper

---

SCRAPERS-LIST.md
scrapers/BoyFun.yml

Add new scraper for boyfun.com and updated scrapers list accordingly.

Add BoyFun scraper

---

scrapers/Traxxx.yml
scrapers/traxxx_interface.py

+ add studio code
+ bugfix from using dot notation with Box
+ cleanup indent blocks with single line loops

[Traxxx] add studio Code

---

scrapers/SARJ-LLC.py
scrapers/SARJ-LLC.yml

added studio code to the media scraping output
changed "Sex Art" and "Met Art" to match stashdb's formatting

SARJ-LLC minor imporovements

---

scrapers/Hypnotube.yml

Apologies for the first botched PR - not very familiar with Git.
- Added search-by-name functionality to the Hypnotube scraper.
- Amended URL scene scraper to fix an issue where the URL was not being scraped.

Update Hypnotube.yml to add search functionality, fix issue with URL scraping

---

scrapers/ManyVids/ManyVids.py
scrapers/ManyVids/ManyVids.yml

Added Studio Code, Url and studio name to the scene’s informations.
Disclaimer : the search engine is garbage.

ManyVids : Added search via sceneByName

---

SCRAPERS-LIST.md
scrapers/YesGirlz.yml

XPath Scraper for Yes Girlz: their site is Wordpress with pretty terrible structure, but this has worked for every scene I've tried it on. Provides title, performers, image, studio and (optional) details

Add scene scraper for YesGirlz.com

---

scrapers/hanime.yml

Update hanime scraper to scrape by filename

Update hanime scraper to scrape by filename

---

scrapers/vixenNetwork.py
scrapers/vixenNetwork.yml

Adding Kayden's new jewel of the crown

Add Milfy to Vixen Media Group scraper

---

SCRAPERS-LIST.md
scrapers/Hentaied.yml

Child Site of Hentaied.yml using same site Template. Added URL to existing Hentaied.yml to enable site Support

Add Support for parasited.com

---

SCRAPERS-LIST.md
scrapers/TeenyTaboo.yml

Not an incredibly well structured site but this has worked for every scene on the site so far

Add scene scraper for TeenyTaboo.com

---

SCRAPERS-LIST.md
scrapers/Xrares.yml

A very simple one as most the info is contained in the web page's `<meta>` tags.
All upload dates are in the format of "x days ago".
Using video ID for studio code.

Added xPath sceneScraper for Xrares

---

SCRAPERS-LIST.md
scrapers/EroProfile.yml

This will handle both the desktop and mobile websites despite their completely different HTML.
Here's a randomly selected video URL (obviously very NSFW) you can test it with both desktop and mobile versions:
```
https://www.eroprofile.com/m/videos/view/ggsdgbZNXB
https://m.eroprofile.com/p/videos/view/ggsdgbZNXB
```

Added XPath scene scraper for EroProfile

---

scrapers/FetishPro.yml

The existing scraper doesn't seem to work on any scene URL I've tried, so I've updated it to match the current site layout.

Update FetishPros scraping for current site layout

---

scrapers/MenAtPlay.yml

Oof, that will teach me not to run validation when "I'm sure it's all correct." 😞 This time, change passes validation. Sorry about that!

Fix MenAtPlay validation failure

---

SCRAPERS-LIST.md
scrapers/AniDB.yml

Store this file in the ~/stash/scrapers/AniDB.yml (If the scrapers directory is not there it needs to be created).
This step is only necessary to access 18+ content.
Access the anidb.net website > login > right button > inspect > find cookies storage
Copy the "Value" of "adbsess" and "adbuin" and replace in the cookies category of this document.
If your account is new, you need to access any NSFW anime and confirm that you want to see 18+ content.
Do not change the order of the columns, as it can make it stop working.
I recommend creating a new account just for this.
Go to your Stash > Settings > Metadata Providers > Scraping > Scraper User Agent
Use the User Agent of your choice.
I'm currently using: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
The scene …

Add support for anidb.net

---

scrapers/Babepedia.yml

Minor change, fix the aliases to make sure they are properly populated in Stash

Babepedia - Aliases are now split correctly

---

SCRAPERS-LIST.md
scrapers/CocksureMen.yml

New scraper for CocksureMen (cocksuremen.com), with the URL added to the scrapers list.

Add scraper for CocksureMen

---

SCRAPERS-LIST.md
scrapers/Kink.yml

I've tested as much as I can, and it seems to pass validation. That being said, XPath is not exactly my forte so always open to improvements.

Add performer scraping to Kink scraper;

---

SCRAPERS-LIST.md
scrapers/Futanarica.yml

New scraper for Futanarica.com
Description is not perfect, didn't find a way to get the full text consistently, each page manages the description with a different path...
Image has the "Play button" watermark but that is the official image 🤦

New scraper: Futanarica

---

SCRAPERS-LIST.md
scrapers/LoveHerFilms.yml

Also rename the YAML file to LoveHerFilms.yml to match the network name.
Essentially recreating #1374

Fix name formatting for LoveHerFeet.com

---

scrapers/data18.yml

Fixed front cover not importing on movie scrapes.
Added Age Verification Captcha that occurs during certain geo locations. (Thanks Maista6969)

Updated Data18.com

---

scrapers/Kink.yml

Noticed that Kink have some new channels but also a lot of third party partners they distribute for: I'm still unsure if we want these in the Kink scraper, but I'm leaning towards keeping them here because people can certainly buy their scenes from here and they should be able to scrape them even if their information is not authoritative for StashDB
Also disabled CDP to speed things up and avoid [this crash](https://discord.com/channels/559159668438728723/559159668912553989/1134798833302384762) reported on Discord

Kink update

---

scrapers/Bang.yml

Fixes a bunch of outdated fields in the Bang scraper. 
The performer twitter field was removed as I can't see any performers with this field populated. The movie and studio fields come out uncapitalised.

Update Bang scraper

---

scrapers/insex.yml

The insex.yml currently doesn't work anymore. Above is a fix that clicks the "i agree" button on the splash screen.
As an alternative we could also set a cookie:
Name: consent
Value: yes
But i don't know how to achieve that per domain. Do we need to define a Cookie for each supported domain? Or is there placeholder/variable support?
This may discards the requirement of cdp

Fix insex.yml

---

SCRAPERS-LIST.md
scrapers/CzechVR.yml

This ensures that even if you scrape your scene from CzechVRNetwork.com you'll still get the correct studio name (Czech VR, Czech VR Fetish, Czech VR Casting  or VR Intimacy)
It also adds their new site, VR Intimacy

Always get correct studio for Czech VR Network sites

---

scrapers/Loyalfans/Loyalfans.py
scrapers/Loyalfans/Loyalfans.yml
scrapers/Loyalfans/requirements.txt

Adding a new scraper for Loyalfans video store content. I have tested this on a few videos with success, but caveat emptor.
Re-submitted as I had forgotten to add a 'Last Updated' date to the YML.

Add new scraper for Loyalfans links

---

SCRAPERS-LIST.md
scrapers/Tenshigao.yml

tested with https://tenshigao.com/model/haruka-fuji/ and https://tenshigao.com/model/mao-haneda/

Add performer scraper to Tenshigao.yml

---

SCRAPERS-LIST.md
scrapers/TadpolexStudio.yml

As requested by @gurgles-1 in #73

Add XPath scraper for tadpolexstudio.com

---

scrapers/LittleCapriceDreams.yml

Now correctly scrapes the series as the studio name!

Update LittleCapriceDreams for new layout

---

scrapers/Loyalfans/Loyalfans.py

Also ran this through the Black formatter

Fix for LoyalFans scenes that do not have preview images

---

SCRAPERS-LIST.md
scrapers/NaughtyNatural.yml

This creates a scene and gallery scraper for naughtynatural.com
The scraper does not scrape a scene image. The xPath scene scraper correctly parses the scene's jpg file, however the server returns the following:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>W708A9V1FYCYGYMP</RequestId>
<HostId>Zxrl4lZH6o9mKpN2kJeAaWPpigw21xFcNk9sH7TIkQdf2fZnOoOKzrGdZ/xdCIzFm+WybHr8img=</HostId>
</Error>
```
This is beyond my scope of expertise. Perhaps someone with more advanced skills can figure it out, if anyone even uses this scraper.

Created Naughty Natural scraper

---

SCRAPERS-LIST.md
scrapers/Algolia.py
scrapers/Algolia_FalconStudios.yml
scrapers/Algolia_RagingStallion.yml
scrapers/GammaEntertainment.yml

Moves (some of) Falcon Studios from the Gamma scraper to the Algolia scraper
Tested with scenes from falconstudios, ragingstallion, and hothouse.

Add Algolia scraper for Falcon Studios

---

SCRAPERS-LIST.md
scrapers/AdultSiteRunner.yml

A small network of mostly gay sites whose structures were similar enough that I put them all in the same file
Tested with the following links:
* [BlackBoyAddictionz.com - Craving Kilo](https://www.blackboyaddictionz.com/scene/542-craving-kilo)
* [BlacksOnDaddies.com - Silvio Is On Edge](https://www.blacksondaddies.com/scene/707-silvio-is-on-edge)
* [BoundJocks.com - Bob Hager Tops Dolan Wolf](https://www.boundjocks.com/scene/76-bob-hager-tops-dolan-wolf) - Does not provide release date
* [BoysHalfwayHouse.com - Always Root For The Winner](https://www.boyshalfwayhouse.com/scene/320-always-root-for-the-winner) - Does not provide release date
* [ColtStudioGroup.com - Hard Drive Scene 3](https://www.coltstudiogroup.com/scene/50-hard-drive-scene-3) - Does not provide release date
* …

Add AdultSiteRunner

---

SCRAPERS-LIST.md
scrapers/CarnalPlus.yml

XPath scraper for the following sites:
| Site name | Example scene |
| --------- | ------------- |
| American Muscle Hunks | [example scene](https://americanmusclehunks.com/videos/manhole-joey-d-jack-hunter.html) |
| Bang Bang Boys | [example scene](https://bangbangboys.com/videos/rafael.html) |
| Bareback+ | [example scene](https://barebackplus.com/videos/mike-edge-and-declan-gray-chapter-3_vids.html) (same as Raw Fuck Boys scene) |
| Bound Twinks | [example scene](https://boundtwinks.com/videos/tyler-tanner-benji-dawsten-encounter-2.html) |
| Boy For Sale | [example scene](https://boyforsale.com/videos/the-grooming-boy-aidan-chapter-1.html) |
| Carnal+ | [example scene](https://carnalplus.com/videos/boy-massage-hung-uncle-tape-2_vids.html) (same as the Gaycest scene) |
| Dirty Boy …

Add Carnal+ and FTM+ networks along with their 16 subsites

---

scrapers/Pornhub.yml

Updates to make pornhub scraper work again

Fix PornHub sceneScraper

---

SCRAPERS-LIST.md

sorry this should have been included in #1472 but it slipped my mind at the time

add to scrapers-list

---

SCRAPERS-LIST.md
scrapers/PaperStreetMedia.yml

updated scraper list as well, tested with a few urls I have from the site, not much data scraped from these sadly

Add pervprincipal.com

---

scrapers/SpunkWorthy.yml

This PR adds support for [SpunkWorthy](https://www.spunkworthy.com)
- sceneScraper (XPath)
- Title
- Performers
- Name
- URL
- Details
- Image
- Studio (fixed: SpunkWorthy)
- Tags
- performerScraper (XPath)
- Name
- Gender (fixed: male)
- Weight
- Height
- Image

feat: add scraper for SpunkWorthy

---

scrapers/AVJiali.yml

Noticed work on an AV Jiali scraper stalled out over 2 years ago.
Created this from the Tenshiago.yml scraper as the sites are very similar, but there are some code differences for performer name and tags that caused the Tenshiago scraper to not quite work with avjiali.com

Create AV Jiali scraper

---

SCRAPERS-LIST.md

Fixing underscore on heavy_check_mark

Update SCRAPERS-LIST.md to fix heavy_check_mark on avjiali.com

---

SCRAPERS-LIST.md
scrapers/EnglishLads.yml

This PR adds a scraper for [English Lads](https://www.englishlads.com)
Scraper implements:
- sceneScraper
- Title
- Date
- Performers
- Name
- URL
- Details
- Tags
- Image
- Studio (fixed: English Lads)
- performerScraper
- Name
- Gender (fixed: male)
- Height
- Measurements
- Waist (in)
- Chest (in)
- PenisLength
- Circumsized
- Details
- Image
- galleryScraper
- Title
- Date
- Performers
- Name
- URL
- Details
- Tags
- Studio (fixed: English Lads)

feat: :sparkles: add scraper for English Lads

---

SCRAPERS-LIST.md
scrapers/ChickPass.yml

Added a Performer scraper to Chickpass.yml and updated SCRAPERS-LIST.md to reflect that all Chickpass sites now have a Performer scraper

Added Performer scraper to Chickpass.yml and updated SCRAPERS-LIST.md 

---

scrapers/AdultEmpireCash.yml

Tested and seemingly work perfectly out of the box atleast on the movie side.

Added data18.empirestores.co support

---

SCRAPERS-LIST.md
scrapers/vTubie.yml

Add performer scraper for [vTubie](https://vtubie.com/), a VTuber database. Example usecase: MMD Videos

Add performer scraper for vTubie

---

SCRAPERS-LIST.md
scrapers/Baberotica.yml

Added performer scraper and fixed scene scraper issues with Baberotica.yml and updated SCRAPERS-LIST.md to add the check mark for Performer scraper to Baberotica sites.

Added performer scraper and fixed scene scraper issues with Baberotica.yml, added 2 new sites, and updated SCRAPERS-LIST.md

---

SCRAPERS-LIST.md
scrapers/TeenMegaWorld.yml

Fixed an issue with Image scraping on some sites and added performerScraper + updated SCRAPERS-LIST.md to check P for all TeenMegaWorld sites.

Fixed an issue with Image scraping added performerScraper + updated SCRAPERS-LIST.md

---

SCRAPERS-LIST.md
scrapers/DartTechStudios.yml

xPath scraper for darttechstudios.com

Added xPath scraper for darttechstudios.com

---

SCRAPERS-LIST.md
scrapers/Baberotica.yml

Added new site, Nu Cosplay, to the Baberotica scraper and updated SCRAPERS-LIST.md

Added new site, Nu Cosplay, to the Baberotica scraper and updated SCRAPERS-LIST.md

---

scrapers/Hentaied.yml

Update to hentaied

---

SCRAPERS-LIST.md
scrapers/DirtyFlix.yml

only useful data for these sites is really with the members site, seems like this site is mostly defunct now as they haven't uploaded in 6 months but still has a large amount of data that can be scraped.

add scraper for dirtyflix members site

---

scrapers/Private.yml

this is the studio code that a few scenes on the db have, if it's preferred to use the end of the URL I can change to that instead.
Went with this since there was quite a few scenes that used this format

add studio code scraping for private.com

---

scrapers/dc_onlyfans_fansdb/README.md
scrapers/dc_onlyfans_fansdb/dc_onlyfans_fansdb.py
scrapers/dc_onlyfans_fansdb/dc_onlyfans_fansdb.yml

This PR adds support for scraping Fansly metadata from `user_data.db` files and improves upon a few other things.

feat: dc_onlyfans_fansdb Fansly support

---

scrapers/Tenshigao.yml

Fixed issues with performer names/details, and scene details scraping.
Also set Country/Ethnicity/Gender to fixed values.

Fixed issues with performer names/details, and scene details scraping

---

scrapers/Sayuncle.yml

Add tag scraping for Sayuncle scenes.
IMO, they tag excessively, but someone may want (some of) them.

Add scraping for tags for Sayuncle.yml

---

scrapers/AVJiali.yml
scrapers/Tenshigao.yml

Updated AVJiali.yml and Tenshigao.yml with sceneByName scrapers and cleaned up the code

Updated AVJiali.yml and Tenshigao.yml with sceneByName scrapers and cleaned up the code

---

scrapers/IWantClips.yml

Scrape Studio name instead of fixed "IWantClips"
Fix scraping of description when it has multiple paragraphs (ignored and squashed before, not anymore)

Update IWantClips Scraper

---

scrapers/ShokoAPI/ShokoAPI.py
scrapers/ShokoAPI/ShokoAPI.yml
scrapers/ShokoAPI/config.py

use py_common.graphql and move config options into a separate file

[shokoapi] use py_common.graphql and move config options.

---

scrapers/HeavyOnHotties.yml

The leading 'Performer In:' is not part of the title. 
Currently it scrapes: Performer In: 'Title of this scene'
Title should be 'Title of this scene'

Fix title scraping for HeavyOnHotties

---

SCRAPERS-LIST.md
scrapers/Hentaied.yml

Added Site freeze.yml support for issue #1548

Added Support for freeze.xxx to Hentaied.yml

---

scrapers/TheScoreGroup/TheScoreGroup.py
scrapers/TheScoreGroup/TheScoreGroup.yml

Added PerformerByName to TheScoreGroup.yml and associated python script to handle it.

Updated TheScoreGroup scraper

---

scrapers/Minnano-AV/Minnano-AV.py
scrapers/Minnano-AV/Minnano-AV.yml

Minnano-AV.com enabled HTTPS across their site

Minnano-AV.yml: allow HTTPS

---

scrapers/SCRAPERS-LIST.md

Adding sites to the scrapers-list, that were forgotten to add when scraper was added.
[collectivecorruption.com](https://github.com/stashapp/CommunityScrapers/commit/b7085059dfba2251190caaaea3d4c28a60fcdb13)
[girlgirlxxx.com](https://github.com/stashapp/CommunityScrapers/commit/2d403db3d7f24822b1faa7cf09bfffa7f8b7d3bf)
[newgrounds.com](https://github.com/stashapp/CommunityScrapers/commit/8b065b3bd97911384d4d287cf3630a8acbc6f624)

Adding sites to the scrapers-list, that were forgotten to add when scraper was added.

---

scrapers/IAFD/IAFD.py

Added function to IAFD scraper to return director(s), if there any, for scenes

Added function to IAFD scraper to return director(s), if there any, for scenes

---

SCRAPERS-LIST.md
scrapers/Nubiles.yml

Added lilsis.com to URL scene scraper, as the site is part of the Nubiles network.

Add lilsis.com to Nubiles scraper

---

scrapers/OopsFamily/OopsFamily.yml

Tested on several scenes to validate.  Special thanks to Maista on Discord for the pointers on image handling.

New scraper for oopsfamily.com

---

scrapers/CopyFromScene/CopyFromScene.py
scrapers/CopyFromScene/CopyFromScene.yml
scrapers/CopyToGallery/CopyToGallery.py
scrapers/CopyToGallery/CopyToGallery.yml
scrapers/py_common/graphql.py

Adding Copying Studio Code from Scene or Gallery
Changes:
1. Add code field to GraphQL getScene
2. Add code field to GraphQL getGalley.scenes
3. Add code to update gallery for CopyFromScene and CopyToGalley

Support for Copy Scene Code after 0.24 stashapp

---

SCRAPERS-LIST.md
scrapers/HobbyPorn.yml

New scraper for hobby.porn
It's my contribution. Would be happy about some feedback about my work.

Add HobbyPorn

---

scrapers/pornworld.yml

Updated scraper to pull data correctly now.  Commented out Studio Code as it was configured to use the scene title which I didn't think was correct but have no idea what to add there now.

PornWorld scapper was not pulling just about anything correctly.

---

scrapers/TesteDeFudelidade.yml

Scraper that I made mostly to learn how to make it

Add TesteDeFudelidade.yml

---

scrapers/Private.yml

Fix the broken Movie Title on Private.com
I'm not an XPath expert, so there might be better ways to do this.

Fix private.com Movie Title

---

scrapers/vixenNetwork/vixenNetwork.py
scrapers/vixenNetwork/vixenNetwork.yml

There are also some additional error handling features that may or may not be wanted

Add support for loading markers for Vixen Media Group content

---

scrapers/IncestFlix.yml

Basic scene info, since this site doesn't really display much to scrape.  Wanted to take a crack at knocking one off the list on [https://github.com/stashapp/CommunityScrapers/issues/73](https://github.com/stashapp/CommunityScrapers/issues/73) .
This populates :
- Studio (not the actual one, they are inconsistent with naming formats)
- Title
- Performers
- Tags
- Image

incestflix.com SceneByUrl scraper

---

scrapers/BelAmi.yml

Add mappings for Tags to match those used in StashDB. 
Added condition in Performers to prevent "Show more actors" link from matching

BelAmi.yml - Tag mapping and performer tweak

---

scrapers/ManyVids/ManyVids.py

This pull request fixes ManyVids scene information scraper.
ManyVids changed the scene endpoint today (2024-01-15).

Fix ManyVids scene scraper

---

scrapers/BradMontana.yml

Fixed description, title and actor list not being scraped

Fixed bradmontana scraper

---

scrapers/FileMetadata/FileMetadata.py
scrapers/FileMetadata/FileMetadata.yml

Scrapes the primary video file metadata for a scene: the title, date, artist (can be a studio or performer), description/details, and the URL from the comment field.

File Metadata scraper

---

scrapers/Hotmovies.yml

This fixes the HotMovies scraper.
Note that AdultEmpire provides the same data as HotMovies with a different UI.
The AdultEmpire scraper currently searches for dvds and this HotMovies scraper searches for clips which i feel is a good split.

Fix HotMovies Scraper

---

scrapers/MissMedeaMortelle.yml

Add Miss Medea Mortelle scene scraper https://www.missmortelle.com/

Add Miss Medea Mortelle scene scraper

---

scrapers/Alterpic.yml

Add Alterpic scene scraper https://alterpic.com/

Add Alterpic scene scraper

---

scrapers/javdb.yml

Before: details = studio code
After: details = title
Also scrape director

javdb: use title for details, scrape director

---

scrapers/TopWebModels/TopWebModels.py
scrapers/TopWebModels/TopWebModels.yml

Studios weren't scraping. Tested this on a few random scenes, all now scraping studios.

Small Fix for TopWebModels

---

scrapers/Nympho.yml

Updated Nympho scraper to retrieve larger images, tags and studiocode

Updated Nympho scraper

---

scrapers/CopyToImages/CopyToImages.py
scrapers/CopyToImages/CopyToImages.yml
scrapers/py_common/graphql.py

This is a copy of "Copy to Gallery" intended to push Gallery metadata down to the attached Images. I've made an attempt at making it configurable; I couldn't find an example of a config.ini in use so hopefully this is implemented correctly!

Gallery to image Gallery scraper

---

scrapers/Adultime/Adultime.yml

URL lezbebad.com/en/video/ added.

Add lezbebad to Adultime

---

SCRAPERS-LIST.md
scrapers/Spritzz.yml

New URL scene scraper for spritzz.com (gay site).

Add scraper for spritzz.com

---

SCRAPERS-LIST.md
scrapers/BringMeABoy.yml

New URL scene scraper for bringmeaboy.com (gay site).

URL scene scraper for Bring Me A Boy (bringmeaboy.com)

---

scrapers/PureMedia.yml

Pure Media updated their website, updated scraper.
Unfortunately [pornstarbts.com](https://pornstarbts.com/tour/) do not list performers (yet), everything else is there.

Updated Pure Media scraper

---

SCRAPERS-LIST.md
scrapers/CutlersDen.yml

New URL scene scraper for Cutler's Den, cutlersden.com (gay site).
Site added to scraper list
New YML file to handle scraping

Add URL scene scraper for Cutler's Den (cutlersden.com)

---

scrapers/PMVHaven/PMVHaven.py
scrapers/PMVHaven/PMVHaven.yml

- Updated yml file to include sceneByFragment block using python scraper.
- Updated python scraper to handle fetching data using fragment. Requires video ID be in included in video title.

Added sceneByFragment to PMVHaven scraper

---

scrapers/GIGA.yml

Added scraper for GIGA studio site ( www.akiba-web.com )

Added GIGA scraper

---

scrapers/Czechav.yml

Implemented some improvements to the CzechAV scraper:
- Added powerfetish.com as a source
- Fixed broken title scraper
- Added performer scraper
- Added date scraper
Tested on a mix of older and newer releases I have on my local machine from their different sub-studios

Improve czechav scraper

---

scrapers/GIGA.yml

Added fixed studio name
Sorted field names alphabetically

Update Giga scraper

---

scrapers/TheScoreGroup/TheScoreGroup.yml

Specifically extracting from PornMegaLoad but I didn't find that it created any issues for other sites.

Improved Tag extraction for TheScoreGroup.yml

---

scrapers/RealityLovers/RealityLovers.py
scrapers/RealityLovers/RealityLovers.yml

- date not scraped
- title scraped includes " VR Porn Video" at the end on tsvirtuallovers.com
- cover image is naively scraped, so can be the smallest size offered
- scrapes date from `releaseDate` in JSON
- " VR Porn Video" is removed from title
- use the largest cover image (determined by filename ending)
- for scenes shot from "Voyeur" perspective, add "Voyeur" and "Non-POV" tags
- add "Virtual Reality" tag to all scenes
Confirmed as working correctly with the following scenes:
- https://realitylovers.com/vd/180285648/MILF-Boss
- https://tsvirtuallovers.com/vd/24955513/TS-Cuckold-Story
- https://tsvirtuallovers.com/vd/24171103/TS-Psychotherapist
- https://tsvirtuallovers.com/vd/24984545/Anal-Soccer-Room
- https://tsvirtuallovers.com/vd/25257945/TS-Surprise-in-Christmas

fix/improve RealityLovers

---

scrapers/AdultEmpire.yml

The current solution only scrapes for the movie as a whole. I've added an additional scraper to scrape a clip from the movie as well.  I've found the image on the page is in an iFrame so I tried to do a subscraper.  From the debug I can see it is finding the correct URL but no image is scraped out, not sure if you can provide any insight there.

Adult empire single sceene rather than entire movie

---

scrapers/Milovana.yml

Fix issue from https://github.com/stashapp/CommunityScrapers/issues/123#issuecomment-1979488006
Adding user agent or cookies might also fix this. CDP is slower, but easiest fix.

Fix Milovana.yml

---

scrapers/TMDB.yml

Unsure why/when we lost the TMDB scraper.  Very useful for movies.  This has been updated to new schema on the site and pre-scrape the artwork into the created movie object.

Adding TMDB for new schema

---

SCRAPERS-LIST.md
scrapers/SlaveMouth.yml

Adds a sceneByURL xPathScraper for SlaveMouth.com

Add SlaveMouth scraper

---

scrapers/TheScoreGroup/TheScoreGroup.yml

Now extracting Date correctly. Tested with 3/9 sites.

Addressed Date extraction issue for TheScoreGroup

---

scrapers/3rdDegreeFilms/3rdDegreeFilms.yml
scrapers/Algolia/Algolia.py

I do not have a gallery to test with so I've left that bit commented out.

New scraper using Algolia for 3rd Degree Films

---

scrapers/dc-onlyfans/dc-onlyfans.py

Fix for this error
DeprecationWarning: The default timestamp converter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes

Update Timestamp converter

---

scrapers/dc-onlyfans/dc-onlyfans.py

Reverts stashapp/CommunityScrapers#1693

Revert "Update Timestamp converter"

---

scrapers/MissAV/MissAV.yml

make a scraper for MissAV.com
search by name

add scraper for MissAV

---

scrapers/X-artcom.yml

As stated in the title, this PR expands the current X-Art scraper enabling scraping of galleries from x-art.com.

Added X-Art gallery scraping

---

SCRAPERS-LIST.md
scrapers/AdultEmpireCash.yml

- add braziliantransgirls.com scene and movie scraping by URL
- add transationalfantasies.com scene and movie scraping by URL
- https://www.braziliantransgirls.com/433465/brazilian-trans-girls-bianca-hills-2-solo-streaming-scene-video.html
- https://www.transationalfantasies.com/shop/1863283/bianca-hills-2-porn-videos.html
- https://www.braziliantransgirls.com/637254/brazilian-trans-girls-nubile-brazilian-beauty-yasmin-dornelles-looks-sexy-in-her-braces-and-black-lingerie-she-licks-her-huge-breasts-before-sucking-on-her-large-glass-dildo-streaming-scene-video.html
- https://www.braziliantransgirls.com/2580346/yasmin-dornelles-streaming-porn-videos.html
- https://www.transationalfantasies.com/shop/612421/transational-fantasies-yasmin-dornelles-streaming-scene-video.html
- …

AdultEmpireCash: add braziliantransgirls.com and transationalfantasies.com

---

scrapers/Newgrounds.yml

I also added URLs to the scraper.

Fixed issue with regex where scraping would not work for video with brackets in name.

---

SCRAPERS-LIST.md

Added GIGA studio (akiba-web.com) to scraper list.

Added GIGA (akiba-web.com) to SCRAPERS-LIST.md

---

SCRAPERS-LIST.md
scrapers/RoyalFetishFilms.yml

New YML scene scraper for Royal Fetish Films.

Add scene scraper for Royal Fetish Films (royalfetishxxx.com)

---

SCRAPERS-LIST.md
scrapers/BadPuppy.yml

New YML scraper for sites in the BadPuppy network, of which currently I know two:  badpuppy.com and clubamateurusa.com.

Add scrapers for BadPuppy Network

---

SCRAPERS-LIST.md
scrapers/AD4X.yml

New YML scene scraper for AD4X (ad4x.com).

Add scraper for AD4X

---

SCRAPERS-LIST.md
scrapers/AdultDoorway.yml

New YML scene scraper for sites in the AdultDoorway network.

Add AdultDoorway network scraper

---

SCRAPERS-LIST.md
scrapers/AdultDoorway.yml

Added 4 new sites to the AdultDoorway scraper:
blackonblackcrime.com
ghettodoorway.com
pornaddict.com
povhotel.com

Additional sites for AdultDoorway scraper

---

scrapers/IFeelMyself/IFeelMyself.py

Older videos still use the img tag for videos isntead updating to video tag. They also sometimes use a different class for the date. Appears to work correctly on both old and new videos.

Fixes for older IFM videos

---

SCRAPERS-LIST.md
scrapers/AkiraLaneProductions.yml

Added AkiraLaneProductions.yml scene scraper for akiralane.com, akiralanebound.com and pantyhoselane.com and updated scrapers list.

Akira lane productions

---

.github/workflows/validate.yml

```
> node .\validate.js
Validation passed!
> node -v
v20.12.0
> yarn -v
1.22.21
```

bump ubuntu, actions

---

scrapers/AbbyWinters.yml

There is a nsbp in as part of the date format. Hopefully this is uploaded correctly or will cause issues.

Updates AbbyWinters Scraper to pull date

---

SCRAPERS-LIST.md
scrapers/VRBangers.yml

Added new site blowvr.com to URL list and studio map for VRBangers.yml.
Added blowvr.com to scrapers list.

Add Blow VR to VRBangers scraper

---

SCRAPERS-LIST.md
scrapers/EnjoyX.yml

Added YML scene scraper for EnjoyX (enjoyx.com).
Added enjoyx.com to scrappers list.

Add scraper for EnjoyX

---

SCRAPERS-LIST.md
scrapers/LetThemWatch.yml

New YML scene scraper for Let Them Watch (letthemwatch.com).
Added letthemwatch.com to scrapers list.

Add scraper for LetThemWatch

---

SCRAPERS-LIST.md
scrapers/Glamose.yml

Add URL YML scene scraper for a number of sites that fall under the Glamose network:
- damselsinperil.com
- femmefight.com
- f-f-fights.com
- lethallipstick.com

Add scraper for glamose sites

---

SCRAPERS-LIST.md
scrapers/Slim4k.yml

Added YML scene and performer URL scraper for Slim4k (slim4k.com)
Updated scrapers list with entry for slim4k.com.

Add YML scene and performer URL scraper for Slim4k

---

SCRAPERS-LIST.md
scrapers/Mousouzoku.yml

New YML URL scene scraper for JAV studios in the Mousouzoku network.

Add scraper for Mousouzoku JAV network

---

SCRAPERS-LIST.md
scrapers/VenusAV.yml

New scraper for the Venus AV network (venus-av.com).
Added venus-av.com to scrapers list using VenusAV.yml.

Add scraper for Venus AV network

---

SCRAPERS-LIST.md
scrapers/CruisingPorn.yml

New scene and performer URL scraper for CruisingPorn (cruisingporn.com).
Added cruisingporn.com to scrapers list, using CruisingPorn.yml.

Add scraper for cruising porn

---

SCRAPERS-LIST.md
scrapers/NakedSword.yml

Added compatible sites to NakedSword scraper:
- trailertrashboys.com
- trentonducati.com
Added entries for above sites to scrapers list.

Add compatible sites to NakedSword scraper

---

SCRAPERS-LIST.md
scrapers/TheScoreGroup/TheScoreGroup.yml

Added Autumn Jade (autumn-jade.com) to scraper for TheScoreGroup.
Added autumn-jade.com to scrapers list, using TheScoreGroup.yml.

Add Autumn Jade to TheScoreGroup scraper

---

SCRAPERS-LIST.md
scrapers/Andomark.yml

Added DreamGirls Clips (dreamgirlsclips.com) to scene URL scraper.
Added dreamgirlsclips.com to scrapers list, using Andomark.yml.

Add DreamGirls Clips to Andomark scraper

---

scrapers/RealityLovers/RealityLovers.py
scrapers/RealityLovers/RealityLovers.yml

Fetch the same image as the search API.
The image filename is always `00-Main-photo-Large.jpg`

Fetch proper cover image for RealityLovers

---

SCRAPERS-LIST.md
scrapers/Andomark.yml

New Andomark site, Nice Feelings (nicefeelings.com), added to Andomark scraper.  
Scrapers list updated for nicefeelings.com, using Andomark.yml.

Add nice feelings to andomark scraper

---

SCRAPERS-LIST.md
scrapers/Hentaied.yml

Added vored.com to Hentailed scraper.
Added vored.com to scrapers list, using Hentaied.yml.

Add vored.com to Hentaied scraper

---

SCRAPERS-LIST.md
scrapers/KBProductions/KBProductions.py
scrapers/KBProductions/KBProductions.yml

Added sites hardwerk.com (HardWerk) and legendaryx (Legendary X) to KBProductions scraper.  
Modified studio maps and updated scrapers list with new entries.

Add HardWerk and Legendary X to KBProductions scraper

---

scrapers/HeavyOnHotties.yml

Small fix for title scraping
Changed fixed studio name to reflect how it is [displayed ](https://stashdb.org/studios/f37de225-7f7d-4160-a437-b6f58ed260da)on stashdb.org

Fix title scrape Heavy On Hotties

---

scrapers/Algolia/Algolia.py

checks if movie covers are valid links and if the images at the urls are the same
In some instances the `back_image` url will be an invalid link and will cause issues when trying to save after scraping, this resolves that issue by checking both links are valid before passing the urls off to stash
It is is also somewhat common for the  `back_image` to be the same image as the front, this performs a simple check of parsing both images as base64 and checking if they are the same before passing the `back_image` to stash

[Algolia] Movie covers checks

---

SCRAPERS-LIST.md
scrapers/Shy-Girls.yml

New YML URL scene scraper for Shy-Girls (shy-girls.com), with site added to scrapers list.

Add scraper for Shy-Girls (shy-girls.com)

---

SCRAPERS-LIST.md
scrapers/AnatomikMedia.yml

New URL YML scene scraper for AnatomikMedia (anatomikmedia.com).
Added anatomikmedia.com to scraper list, using AnatomikMedia.yml.

Add scraper for AnatomikMedia (anatomikmedia.com)

---

scrapers/AmateurAllure.yml

Updated Amateur Allure

---

SCRAPERS-LIST.md
scrapers/TheNude.yml

Srape galleries and scenes form TheNude.
I wish there was a way to detect and rotate the horizontal scene covers properly.

TheNude gallery and scene scrape

---

SCRAPERS-LIST.md
scrapers/MVG.yml

Updated selectors in MVG scraper to work with the network's latest layout.
Added several new URLs to the scraper, and updated scrapers list.
New URLS:
- amaraw.com
- blackcockpassion.com
- gogayguy.com
- iluvmilfs.com
- iluvteens.com
- myslutwifegoesblack.com
- oblackgirls.com
- oblowjobs.com
- upshemale.com

Update MVG scraper for new layout and new URLs

---

scrapers/VRPorn.yml

Correct issue with xpath change for title pull.  Also added a sceneByName function.

Correct issue with VRPorn xpath change for title pull.

---

SCRAPERS-LIST.md
scrapers/Andomark.yml

Added Drea Morgan (dreamorgan.com) to Andomark URL scraper.
Added dreamorgan.com to scraper list using Andomark.yml.

Add Drea Morgan (dreamorgan.com) to Andomark scraper

---

scrapers/Penthouse.yml

Updating Title scraper for Penthouse Gold

Update Penthouse Title

---

SCRAPERS-LIST.md
scrapers/VelvetEcstasy.yml

New URL scene and gallery scrapers for velvetecstasy.com (Velvet Ecstasy), with url added to scrapers list.

Add URL scene and gallery scraper for Velvet Ecstasy (velvetecstasy.com)

---

SCRAPERS-LIST.md
scrapers/AdultEmpireCash.yml

Added 18lust.com to AdultEmpireCash scene URL scene scraper.
Added 18lust.com to scraper list, using AdultEmpireCash.yml.

Add 18Lust (18lust.com) to AdultEmpireCash URL scene scraper

---

SCRAPERS-LIST.md
scrapers/BlackMaleMe/BlackMaleMe.py
scrapers/BlackMaleMe/BlackMaleMe.yml

Python scene scrapers for Black Male Me (blackmaleme.com) using AyloAPI.
The site doesn't appear to have movies, galleries or performer information available, so only scene scrapers are implemented at this time.

Add scraper for BlackMaleMe (blackmaleme.com)

---

SCRAPERS-LIST.md
scrapers/TheFlourish.yml

Milf Candy (milfcandy.com) added to TheFlourish scraper and scrapers list.

Add MilfCandy to TheFlourish scraper

---

SCRAPERS-LIST.md
scrapers/Pornbcn.yml

Add Pornbcn (pornbcn.com) URL Scene scraper.
Add pornbcn.com to scrapers list using Pornbcn.yml.

Add url scene scraper for Pornbcn (pornbcn.com)

---

scrapers/pornworld.yml

Pornworld.com was not scrapping any longer for me.  I updated the scraper and tested on several scenes.

Recagigered scraping for pornworld.com.

---

SCRAPERS-LIST.md
scrapers/RichardNailder.yml

Scene and URL scrapers for the sites under the Richaird Nailder family:
bringmeyoursister.com
glassmannequin.com
realcoloradogirls.com
richardnailder.com

Add scene and performer URL scrapers for RichardNailder network sites

---

scrapers/data18.yml

Improved title parsing for Data18 scenes to exclude things like "/w jane doe" and the year "(dddd)" and " | DATA18"

Data18 scene title

---

SCRAPERS-LIST.md
scrapers/BigAssTease.yml

New URL scene and performer scrapers for BigAssTease (bigasstease.com).  Site added to scrapers-list.

Add scene and performer scene scrapers for BigAssTease

---

SCRAPERS-LIST.md
scrapers/BlackGirlFetish.yml

URL Scene scraper for blackgirlfetish.com, a network that includes:
Black Girls Fetish
Black Femdom Goddess
Bondage Fantasy Camp
Diamond Orgega
Fresh Flesh Amateurs
There's some excellent info for performers, but unfortunately their layout is a complete mess with no set format, so no performer scraper at this time (if ever...)

Scraper for black girl fetish network

---

SCRAPERS-LIST.md
scrapers/CDGirls.yml

New Scene and Performer scraper for CD Girls and their network subsites:
- First Timers
- Just Barely 18
- Luxury Lesbians
- Fucked By A Machine
- Sybian Orgasms
- VR Body Shots
Added cdgirls.com to scrapers list.

New URL scene and performer scraper for CDGirls network

---

SCRAPERS-LIST.md
scrapers/JacquieEtMichelStars.yml

New URL scene scraper for Jacquie et Michel Stars (jacquieetmichelstars.com), with entry added to scrapers list.

New URL scene scraper for Jacquie et Michel Stars

---

SCRAPERS-LIST.md
scrapers/ModelCentroAPI/ModelCentroAPI.py
scrapers/ModelCentroAPI/ModelCentroAPI.yml

Added mechanism to provide default tags based on studio.
Updated studio map and default performer list for increased accuracy as necessary.
Added kendrasinclaire.com to scraper and scrapers list.  Removed some sites that are no longer scrapable.

ModelCentroAPI scraper updates

---

SCRAPERS-LIST.md
scrapers/Nubiles.yml

Added realitysis.com (Reality Sis) to URL scene and gallery scrapers in Nubiles.yml, and to scrapers list.

Add Reailty Sis (realitysis.com) to Nubiles.yml

---

SCRAPERS-LIST.md
scrapers/SmutPuppet.yml

Added sites to that are compatible with the URL scene scraper SmutPuppets.yml, plus scrapers list:
- maturefucksteen.com
- porn-uk.com

New sites for SmutPuppets.yml

---

scrapers/vogov.yml

Update studio in scene scraper to match how the studio name appears in the HTML of the site's landing page (and how it appears in StashDB).
Added performer URL scraper.

Update vogov.yml for studio name and add performer URL scraper

---

SCRAPERS-LIST.md
scrapers/Andomark.yml

Added new sites compatible with Andomark scraper, and added to scrapers list:
- sexykarenxxx.com
- xratedwife.com

Add new sites to Andomark.yml

---

SCRAPERS-LIST.md
scrapers/FuxersNetwork.yml

New URL Scene scraper for FuxersNetwork (fuxersnetwork.com).
Added fuxersnetwork.com to scrapers list.

Add URL scene scraper for FuxersNetwork

---

SCRAPERS-LIST.md
scrapers/TheScoreGroup/TheScoreGroup.yml

Added Chicks On Black Dicks (chicksonblackdicks.com) to TheScoreGroup scraper and scrapers list.

Add chickson black dicks to the score group

---

SCRAPERS-LIST.md
scrapers/Hentaied.yml

Added voodooed.com to Hentaied.yml and scrapers list.

Add Voodooed to Hentaied.yml

---

scrapers/RagingStallion/RagingStallion.yml

Add proper url to videos. '/scene/' also works fine, so leave it there for now

Fix RagingStallion.yml scene url

---

SCRAPERS-LIST.md
scrapers/bibian-av.yml

Scraper for bibian-av.com, the official website of JAV studio Bibian. The website is Japanese-only, thus scraped data are in Japanese as well.

Add bibian-av.yml

---

scrapers/ATKGirlfriends/ATKGirlfriends.py

Some times not all elements are present. I have added try catch code for the missing elements I have come across in testing. So far the Height can be missing inches or not available and the scene description can also be missing. This as fixed all errors I have encountered so far and appears to not affect functionality
I have also added handling of compilation scenes. It returns no model in this case but it functions. Determining the model will have to be left to the user.

ATKGirlfriends Try Catch Addition for Missing Elements

---

SCRAPERS-LIST.md
scrapers/ModelCentroAPI/ModelCentroAPI.py
scrapers/ModelCentroAPI/ModelCentroAPI.yml

Added   Mugur Porn (mugursworld.com) to ModelCentroAPI.
- site added to URL scraper in ModelCentroAPI.yml.
- studio map added to ModelCentroAPI.py
- site added to scrapers list

Add Mugur Porn (mugursworld.com) to ModelCentroAPI

---

SCRAPERS-LIST.md
scrapers/Spizoo.yml

Added Goth Girlfriends (gothgirlfriends.com) to URL list and studio map for Spizoo.yml.
Added gothgirlfriends.com to scraper list, using Spizoo.yml.

Add Goth Girlfriends to Spizoo scraper

---

scrapers/ManyVids.yml

Added postprocess step for scene title/details, to replace ``&amp;`` to ``&`` and ``&quot;`` to ``"``
Tested on this [url](https://www.manyvids.com/Video/5219667/Live-Action-Hentai-Comic-2B-9S-NieRAutomata/
)

Add postprocess step for scene title/details Manyvids

---

scrapers/Pornbox.yml

Added postprocess step to scene details to fix linebreaks ``<br><br/>`` to ``\n``, tested on this [url](https://pornbox.com/application/watch-page/693183)

Fixing linebreaks in scene details Pornbox

---

scrapers/BellesaPlus/BellesaPlus.py

After scraping all bellesahouse, this should be close to the conclusive set of tags and replacements

add new tag replacements

---

scrapers/PMVHaven/PMVHaven.py

The current scraper automatically grabs a low-quality image, updating it to select the full quality image

PMVHaven - Select the HQ image

---

SCRAPERS-LIST.md
scrapers/Nubiles.yml

Added Cheating Mommy (cheatingmommy.com) to URL scene and gallery scrapers for Nubiles.yml.
Added cheatingmommy.com to scrapers list, using Nubiles.yml for scenes and galleries.

Add Cheating Mommy to Nubiles URL scene and gallery scrapers

---

SCRAPERS-LIST.md
scrapers/GuyBone.yml

Created URL scene and performer scrapers for GuyBone (guybone.com) and added guybone.com to scrapers list.

Add scraper for GuyBone scenes and performers

---

scrapers/ManyVids.yml

Replace HTML tags in title/description

Update ManyVids scraper

---

scrapers/MyDirtyHobby.yml

JAR Cookie couldn't get set due to wrong Domain for German URL

fix: Mydirtyhobby, change Domain for Cookie of German Site

---

scrapers/PassionPOV.yml

https://passionpov.com/videos/alina-is-a-tease
https://passionpov.com/videos/lilly-gets-a-cum-bath
New Scraper

add PassionPOV.com scraper

---

scrapers/FetishNetwork.yml

- [819_1 URL](https://www.fetishnetwork.com/t2/showgal.php?g=content/flash/p0019_s0108/p0019_s0108_0003_riley_star_video/40400/819_1)
- [816_1 URL](https://www.fetishnetwork.com/t2/showgal.php?g=content/flash/p0019_s0108/p0019_s0108_0003_riley_star_video/40380/816_1)
Support .../816_1 URL paths.

Support Additional View [FetishNetwork] [sceneByURL]

---

scrapers/PMVHaven/PMVHaven.py

- Fixed out of bounds read in getVideoIdFromDownloadHash function
- Fixed unhandled null in getIMG function

Bug fixes for PMVHaven Scraper

---

SCRAPERS-LIST.md
scrapers/TheBattleForEarth.yml

- [ x] sceneByURL
https://www.thebattleforearth.com/tbosat
https://www.thebattleforearth.com/bemg
This adds basic URL scraping for thebattleforearth.com

Add URL scraper for thebattleforearth.com

---

scrapers/ClubDom.yml

Merge changes from 
closes https://github.com/stashapp/CommunityScrapers/pull/1073 and closes https://github.com/stashapp/CommunityScrapers/pull/1095
Resolved differences, merged any notable differences in. Tested searching and URL but no filename search

ClubDom and SubbyHubby split and update

---

scrapers/Tokyohot/Tokyohot.yml

[scene url](https://my.tokyo-hot.com/product/20005/?lang=en)
Replace ``&quot;`` to ``"``
Replace ``&amp;`` to ``&``
Replace ``&#039;`` to ``'``

Fix for Tokyo-Hot html entities scene details

---

scrapers/VirtualRealGay.yml
scrapers/VirtualRealPorn.yml
scrapers/VirtualRealTrans.yml

There's a convenient `<link rel="shortlink">` element that contains the studio code.

Fetch studio code from Virtual Real Porn sites

---

scrapers/GIGA.yml

SPSB-45
SPSC-29
Added missing code selector to sceneSearch

GIGA - added missing code selector to sceneSearch

---

scrapers/Eporner.yml
scrapers/WhoresHub.yml
scrapers/Xnxx.yml

Add Whoreshub, update XNXX, EPorner

---

scrapers/FemdomEmpire.yml

Supercedes #1072
because I could not figure out how to push to a PR'd fork

Femdom Empire scene search by name

---

scrapers/DogfartNetwork/DogfartNetwork.yml

Add downlowboys to DogfartNetwork.yml

Add downlowboys to DogfartNetwork.yml

---

scrapers/Xslist.yml

Raised in https://github.com/stashapp/CommunityScrapers/issues/1294 but not implemented

add CDP to XsList by default

---

scrapers/BabestationTV.yml

https://www.babestation.tv/girls/page/1?search=georgie%20darby
https://www.babestation.tv/girls/georgie-darby
Supercedes #1245

Add Babestation.tv performer scraper

---

scrapers/BabestationTV.yml

Fairly basic performer scraper for Babestation.tv

Add performer scraper for Babestation TV

---

scrapers/javdb_zh.yml

- supercedes #1201
- supercedes #1312
Merges updates from JavDB, add director and other fields from #1201

merge javdb_zh changes and improvments

---

scrapers/JavLibrary_cn.yml

add JavLibrary_CN, add improvements to EN version

---

scrapers/KBProductions/KBProductions.py
scrapers/KBProductions/KBProductions.yml

Adds trailer.jpg support (gives >1080p quality)
worked on my machine, but unsure of it's history

[KBProductions] add high-res trailer.jpg

---

scrapers/IWantClips.yml

Updating Image Selector to grab cover

[IWantClips] Update Image Selector

---

scrapers/HentaiDude.yml

https://hentaidude.com/shoujo-senki-soul-eater/
https://hentaidude.com/doukyo-suru-neneki-episode-2/
Supercede #2003
removed movie scraping because it is inconsistent across the site

hentaidude.com

---

scrapers/HentaiDude.yml

https://hentaidude.com/yarakashi-episode-1/
Yarakashi - Episode 1
https://hentaidude.com/imaizumin-chi-wa-douyara-gal-no-tamariba-ni-natteru-rashii-episode-1/
Imaizumin-chi wa Douyara Gal no Tamariba ni Natteru Rashii - Episode 1
Added scrapper for hentaidude.com

Added scrapper for hentaidude.com

---

scrapers/Fit18/Fit18.yml

https://fit18.com/models/ashley-tee
https://thicc18.com/models/angel-youngs
Add xPath performer scraper for Fit/Thicc18

Fit18 performer scraper

---

scrapers/Teamskeet/TeamskeetAPI.py

fix TeamSkeet scraping with new endpoint

[TeamSkeet] Fix API endpoint

---

scrapers/Teamskeet/Teamskeet.yml

thans to itgorman for the reminder

add swappz to YML defenition

---

scrapers/LoveHerFilms.yml

[Scene url](https://www.loveherboobs.com/tour/trailers/Say-Wow-Out-Loud-Tanya-Virago-Nelson-Mandingo-boobs.html)
[Scene url](https://www.loveherfeet.com/tour/trailers/A-Toe-Curling-Option-Sahara-Sky-Lucas-Frost-feet.html)
Previously it only grabbed the first paragraph. Fixed so it scrapes all paragraphs

LoveHerFilms Fix details scraping

---

scrapers/Traxxx/Traxxx.yml
scrapers/Traxxx/traxxx_interface.py

switch Traxxx gql to old.traxxx.me

---

scrapers/SexLikeReal.yml

Add "Kinky Girls Berlin" to sexlikereal scraper.  The map value will match the StashDB studio https://stashdb.org/studios/7d892a03-dfbe-4476-917d-4940be13fb24 instead of the scraped code "KinkyGirlsBerlin"
NSFW
https://www.sexlikereal.com/scenes/best-way-to-cheer-you-up-in-the-morning-35816
https://www.sexlikereal.com/scenes/no-netflixx-22277
https://www.sexlikereal.com/scenes/how-do-you-like-my-festival-outfit-47064

Add Kinky Girls Berlin.

---

scrapers/Teamskeet/TeamskeetAPI.py

Resolves https://discord.com/channels/559159668438728723/559159931505213440/1289330428473245789

add new image trial/ parsing logic for TeamSkeet

---

scrapers/PaperStreetMedia.yml

PaperstreetMedia scraper was not working for me on a couple sites so I did some updates.  I've tested on AnalMom, pervdoctor, and dadcrush but not the entire list.  Hope this helps.

Tested and working on AnalMom.com

---

scrapers/Waybig.yml

Adding URL when using performer search

Add Waybig URL for performer

---

scrapers/ManyVidsClub.yml

https://www.manyvids.com/Post/G_imANUFcVVW
https://www.manyvids.com/Post/Z483RIukmymk
FansDB tailored scraper, that uses specific studio template.

Add scraper for ManyVids club posts

---

scrapers/TabooHandjobs.yml

adding scraper for TabooHandjobs (similar to TabooPOV and Jerk off Instructions).

add scraper TabooHandjobs.yml

---

scrapers/SexPOV.yml

add scraper for SexPOV (similar to TabooPOV, TabooHandjobs and JerkOffInstructions).

add SexPOV.yml

---

scrapers/Ersties/Ersties.py

Shoot: https://ersties.com/shoot/6677
Scene: https://ersties.com/shoot/6677#play-8235-comments
Ersties updated their site to now group scenes into "shoots". There were some api updates that came along with this that needed to be update in the script.

Update Ersties.py to match new scene and shoot site format

---

scrapers/Ersties/Ersties.py

https://ersties.com/shoot/7200#play-8073-comments
Pull in Group/shoot when scraping scene

Added group info to scene scraper

---

scrapers/Ersties/Ersties.py

https://ersties.com/shoot/7135#play-1708-comments
Added performer scraping to scene scraper to create missing performers. Also added group url to group scraper in scene scraper.

Shark lasers58 scene update

---

scrapers/Putalocura.yml

update Putalocura url scraper to get studio code

[Putalocura] add Studio Code

---

scrapers/EvilAngelStore.yml

- Driver config
[Newer](https://store.evilangelvideo.com/1698610/evil-angel-jennifer-white-overload-sc2-airtight-streaming-scene-video.html)
[Older](https://store.evilangelvideo.com/560056/evil-angel-dark-haired-beauty-bobbi-starr-sucks-his-cock-streaming-scene-video.html)
Add the required cookie ageConfirmed.

EvilAngelStore Add Required Cookie

---

scrapers/UltraFilms.yml

https://www.ultrafilms.xxx/category/movies/
Fixed release date scraping

Update ultrafilms.xxx scraper

---

scrapers/MFVIdeoXXX.yml

Add `sceneByURL`, `sceneByName`, `sceneByQueryFragment` and `sceneByFragment`
sceneByURL example :
- https://mfvideoxxx.com/i-get-horny-and-i-cum-in-her-mouth
- https://mfvideoxxx.com/lesbian-milf-vs-teen-18-vol-341-milf-kailane-vs-teen-18-bianca-belly
SceneByFragment/sceneByQueryFrament/sceneByName example :
- Facesitting Cum In Your Face
- `Catfight – Vol #262 – Jenny vs Bianca Belly`
Describe the general changes

Add MFVIdeoXXX scraper

---

scrapers/Coomer/Coomer.py

Added coomer tags to scrape results when available

Update Coomer to return tags

---

scrapers/fc2ppvdb.yml

4076594
https://fc2ppvdb.com/articles/4076594

Add fc2ppvdb.com scraper

---

scrapers/nhentai.yml

Updates nhentai scraper to include "Parodies" as Tags.

[nhentai] Add Parodies into Stash Tags.

---

scrapers/ManyVidsClub.yml

- https://www.manyvids.com/Post/c0875183e76e
- https://www.manyvids.com/Post/G_imANUFcVVW
Fallback to studio + date when no title is available

ManyVids Club update

---

scrapers/scrapeCoverFromFile/scrapeCoverFromFile.py
scrapers/scrapeCoverFromFile/scrapeCoverFromFile.yml

Any scene with  a image file with the same name or a cover name in the same dir as the scene file
"scrapes" an image file from the local file system into stash

[scrapeCoverFromFile] add

---

scrapers/Coomer/Coomer.py

Lookup performer name by id and use it to return correct performer/studio name and performer url
Also removed a debug line from url lookup which always showed an error when there wasn't any

Update Coomer to get correct performer information

---

scrapers/FuckPassVR.yml

- https://www.fuckpassvr.com/vr-pornstars/savannah-bond-vr
- https://www.fuckpassvr.com/vr-pornstars/pristine-edge-vr
- https://www.fuckpassvr.com/video/kangaroo-style-in-melbourne
- https://www.fuckpassvr.com/video/the-traveling-model
Adds `performerByURL` and `sceneByURL` scrapers for fuckpassvr.com

Add FuckPassVR.com

---

scrapers/ModelCentroAPI/ModelCentroAPI.yml

Added aikoprincess.com to the list of sites supported by ModelCentroApi.

Add aikoprincess.com to ModelCentroAPI.yml

---

scrapers/ShokoAPI/ShokoAPI.py

Scrapes for the Studio and gets the image/logo too if available but Stash can't handle it right now, maybe in the future this will be fixed so it will not only import the studio name but also the image.

Add Studio to ShokoAPIScraper

---

scrapers/ShokoAPI/ShokoAPI.py

- fixed scenes with no studio crashing
- more robust filename handling with normalizing and encoding, so all special characters should work and scenes in Shoko should be all found and identified correctly
- more robust handling of missing fields overall

fixed bugs

---

scrapers/Babepedia.yml

https://www.babepedia.com/babe/Keeley_Hazell
Closes #2171 
- Image is still being blocked.

Add user-agent header to Babepedia.yml

---

scrapers/Got2Pee/Got2Pee.yml
scrapers/Got2Pee/got2pee_scraper.py

https://got2pee.com/videos/video-in-the-stand/
https://got2pee.com/videos/video-victoria-will-pee-anywhere/
https://got2pee.com/videos/video-knee-highs/
As this scraper did not yet exist i made one using mainly ChatGPT. I know that the python script isn't perfect and anyone that can code can do it better but it works.

Add Got2Pee scene scraper

---

scrapers/AShemaleTube/AShemaleTube.py
scrapers/AShemaleTube/AShemaleTube.yml

- https://www.ashemaletube.com/videos/855461/kiana-vi-self-facial/
- https://www.ashemaletube.com/videos/791747/pmv-non-stop-cums/
- https://www.ashemaletube.com/videos/975426/kinkpmv-sissy-dildo-ride/
Uses the same Cloudflare bypass technique as previously successful for performerByURL
fixes #2076

fix sceneByURL at AShemaleTube

---

scrapers/BondageJunkies.yml

https://bondagejunkies.com/updates?s=Rachel+vs.+An+Inch+Too+Far
https://bondagejunkies.com/updates?s=Hana+vs.+Her+Addiction
https://bondagejunkies.com/updates?s=Sage+vs.+Orgasm+Lockdown

Add BondageJunkies.yml

---

scrapers/MilitaryClassified/MilitaryClassified.py
scrapers/MilitaryClassified/MilitaryClassified.yml

| URL | Expected Results |
| --- | --------------- |
| https://militaryclassified.com/dt/classic/Movies/CAYDEN-TJ.html | Title: "Cayden & TJ: Blowjob Anal" <br> Performers: Cayden, TJ <br> Studio: Military Classified <br> Director: Rob Navarro |
| https://militaryclassified.com/dt/classic/Movies/EVERETT2.html | Title: "Everett 2: Handjob Massage" <br> Performers: Everett <br> Studio: Military Classified <br> Director: Rob Navarro |
| https://militaryclassified.com/dt/classic/Movies/MAJOR-MARCO2.html | Title: "Major & Marco 2: Blowjob Duo" <br> Performers: Major, Marco <br> Studio: Military Classified <br> Director: Rob Navarro |
| https://militaryclassified.com/dt/classic/Movies/JJ.html | Title: "JJ: Anal" <br> …

feat: add Military Classified scene URL scraper

---

scrapers/VRBangers.yml

- https://arporn.com/model/linda-lan/
- https://arporn.com/video/safe-haven/
This adds scene and performer by URL scraping for arporn.com to the existing VRBangers scraper

add arporn.com to VRBangers

---

scrapers/POVR.yml

- https://povr.com/vr-porn/pretty-petite-6355525
- https://www.wankzvr.com/cubbi-s-jubblies-6355861
Can use scene URLs for corresponding photo sets

add galleryByURL to POVR

---

scrapers/NaughtyAmerica.yml
scrapers/NaughtyAmericaVR.yml

- https://www.naughtyamerica.com/scene/sexy-student-cubbi-thompson-takes-on-a-big-cock-to-get-that-a-grade-32868
- https://www.naughtyamerica.com/scene/pornstar-cubbi-thompson-meets-up-to-fuck-in-my-hotel-room-32764
- https://www.naughtyamericavr.com/scene/pornstar-cubbi-thompson-meets-up-to-fuck-in-my-hotel-room-32764
Use scene URLs for galleries (the photo sets appear on the scene page, so the info is the same)

add galleryByURL to NaughtyAmerica

---

scrapers/GroobyClub.yml

- https://www.asianamericantgirls.com/tour/trailers/The-Woman-In-Black.html
- https://www.canada-tgirl.com/tour/trailers/Your-Maid-Ruby.html
- https://www.euro-tgirls.com/tour/trailers/Deep-Satisfying.html
- https://www.hazel-tucker.com/tour/trailers/hazel-tucker-pin-up-girl.html
- https://www.krissy4u.com/tour/trailers/Krissy4u-Slutty-Striped-Schoolgirl.html
- https://www.russian-tgirls.com/tour/trailers/Snow-White-In-Red.html
- https://www.tgirl40.com/tour/trailers/The-Confident-Majestic.html
- https://www.tgirlbbw.com/tour/trailers/Big-Girl-Energy.html
- https://www.tgirlpornstar.com/tour/trailers/Kelly-Mello-Guy-Tavares.html
- https://www.tgirlpostop.com/tour/trailers/Foons-Poon.html
- https://www.transexdomination.com/tour/trailers/celestetsd.html
- …

add galleryByURL to GroobyClub

---

scrapers/ModelCentroAPI/ModelCentroAPI.py
scrapers/ModelCentroAPI/ModelCentroAPI.yml

Just adding Amirah Adara to ModelCentroAPI
Tested against https://amirahadaraxxx.com/scene/7126282/amirah-adara-pleasured-by-a-stranger

Add Amirah Adara to ModelCentroAPI

---

scrapers/danbooru.yml
scrapers/gelbooru-json.yml
scrapers/gelbooru-xpath.yml
scrapers/realbooru.yml
scrapers/rule34-us.yml

update danbooru
add gelbooru-xpath/ gelbooru-json
- closes #2273
- closes #2279 
add rule34-us and realbooru as custom gelbooru scraper

more boorus

---

scrapers/danbooru-api.yml
scrapers/derpibooru.yml
scrapers/moebooru.yml
scrapers/okebooru.yml
scrapers/shimmie2-graphql.yml
scrapers/shimmie2-xpath.yml

adds moebooru - closes #2277
rename danbooru to danbooru-api
add derpibooru - closes #2278 
add shimmie2 - closes #2274
add okebooru as an exception to shimmie2

finish adding boorus

---

scrapers/LadyboyGold/TSRaw.py

- Spit Roasted By 2 Hung TS, Creampied & Fed
- Itty Bitty Titties & Armpit Lick Creampie
The area ID appears to have changed to a UUID, this updates to the value seen in browser requests. The description text is now trimmed of leading and trailing whitespace.

fix area ID; strip leading/trailing whitespace

---

scrapers/GammaEntertainment.yml
scrapers/xEmpire/xEmpire.yml

- Chloe Surreal
- Slimthick Vic
- https://www.allblackx.com/en/pornstar/view/Amari-Anne/63102
- https://www.darkx.com/en/pornstar/view/Kasey-Warner/34754
- https://www.eroticax.com/en/pornstar/view/Molly-Little/106966
- https://www.hardx.com/en/pornstar/view/Dana-DeArmond/24549
- https://www.lesbianx.com/en/pornstar/view/Khloe-Kapri/57555
- https://www.xempire.com/en/pornstar/view/Chloe-Surreal/94643
- Wild Elevator Ride
- Closing The Distance
- https://www.allblackx.com/en/video/allblackx/Amaris-Amazing-Attributes/258838
- https://www.darkx.com/en/video/darkx/Ella-Gets-Extra-Workout-At-He-Gym/259079
- https://www.eroticax.com/en/video/eroticax/Closing-The-Distance/259070
- https://www.hardx.com/en/video/hardx/Wild-Attraction/258840
- …

migrate xEmpire to AlgoliaAPI.py

---

scrapers/NastyDaddy.yml

https://nastydaddy.com/tour/updates/My-Boss-Has-a-Big-Dick.html
https://nastydaddy.com/tour/updates/Tattooed-Muscle-Fuck.html
https://nastydaddy.com/tour/updates/Power-Suits-2.html
New URL Scene Scraper for NastyDaddy (nastydaddy.com)

Add URL Scene Scraper for NastyDaddy (nastydaddy.com)

---

scrapers/sgvideo.yml

[Link](https://www.sg-video.com/details/kissing-extreme-erotic-domination---the-inked-mega-giant---without-camera-stop-by-top-giant-girl-vicky-wild-and-freckles-girl-lia-louise/2008)
- name: Kissing Extreme Erotic Domination - The Inked Mega Giant - Without Camera Stop By Top Giant Girl Vicky Wild And Freckles Girl Lia Louise
- Details: Top brandnew dominatrix and mega inked giant Vicky Wild in her first domination erotic movie with the sweet small freckles girl Lia Louise in one extra long kissing erotic domination scene without camera stop! Can you imagine to kiss more then 20 minutes with one girl? And i mean without stop and real wild kisses! Because this girls made it in this kissing movie, they kiss without stop …

Add scraper

---

scrapers/RimTeens.yml

Scrapes info from scene and performer.  Attempted image extraction, but I guess I'm too dumb to get image for scene/performer.  Everything else works fine.
Tested against:
https://rimteens.com/model/alexis-crystal/
https://rimteens.com/members/alexis-crystal-tastes-ass-juice/

New studio: RimTeens

---

scrapers/ModelCentroAPI/ModelCentroAPI.py
scrapers/ModelCentroAPI/ModelCentroAPI.yml

Add Rebecca Lord Productions.  Since she isn't in every scene, didn't add her as a fixed performer.  API is already scraping females so it should be fine.

Add Rebecca Lord Productions

---

scrapers/JulesJordan.yml

Simply adds two more sites with DVDs to Jules Jordan scraper

Add more movie scrapers for Jules Jordan

---

scrapers/AdultTime/AdultTime.py
scrapers/AdultTime/AdultTime.yml

- https://adulttime.com/en/video/20-Random-Questions-with-Vanna-Bardot/170856
- https://ageandbeauty.com/en/video/ageandbeauty/Sorry-For-Your-Loss/258899
- https://members.adulttime.com/en/video/BetweenTheSheets/Between-The-Sheets-with-Alison-Rey-Lena-Paul--Troy-Francisco/186276
- https://www.femboyish.com/en/video/femboyish/BF-Takes-Control-Of-Femboys-Hole-With-Vibrating-Buttplug/259932
- https://members.adulttime.com/en/video/grinders-channel/Grinders---Part-4/207188
- https://members.adulttime.com/en/video/howwomenorgasm-channel/Hailey-Rose-Loves-To-Be-Creampied/247904
- https://joimom.com/en/video/JOIMom/Stepson-Seduction/172016
- https://ladygonzo.com/en/video/ladygonzo/Lady-Gonzo--Joanna-Angel--Whitney-Wright/135383
- https://oopsie.com/en/video/oopsie/Game-Day-Grind/255672
- …

improve AdultTime - add more custom matching to scrape correct studio names

---

scrapers/SexLikeReal.yml

- https://www.sexlikereal.com/scenes/stepsisters-intimate-desires-58197
- https://www.sexlikereal.com/trans/rock-hard-and-ready-to-roll-623
Some of the fields were not being scraped, this fixes the xpath expressions

fix sceneByURL in SexLikeReal

---

scrapers/NaughtyAmerica.yml
scrapers/Tonightsgirlfriend.yml

https://www.naughtyamerica.com/scene/alura-tnt-jenson-seduces-her-sons-friend-25237
https://www.tonightsgirlfriend.com/scene/alura-jenson-18899
Regex to get Studio Code from URL for Naughty

NA & Tonight's Girlfriend Studio Code

---

scrapers/ehentai.yml

Cherry pick commit from #2391  as animeCharacterDB scraper pulls the wrong entries

add cosplayer as performer in ehentai scraper

---

scrapers/DeviantArt.yml

https://www.deviantart.com/tuoqiaooo/art/Spring-breeze-1189980637
https://www.deviantart.com/femboyartz/art/Dizzy-1076715983
Notably does not work at all with VPNs connected but flawlessly without

[DeviantArt] add

---

scrapers/TheNude.yml

https://www.thenude.com/cover/stunning18/1041590/natasha-s-in-natasha---delicatessen-by-thierry-murrell
Added image by url

Added image scraper by URL

---

scrapers/DorcelClub.yml

Scraping bigger images from Dorcel Club
https://www.dorcelclub.com/en/scene/261567/the-initiation-of-vicki-chase
https://www.dorcelclub.com/en/scene/264735/the-next-step
https://www.dorcelclub.com/en/scene/261607/the-awakening-of-desire
https://www.dorcelclub.com/en/scene/264855/mariska-muse-of-the-wild-nights
With crop:
https://public27-content.cdn-medias.com/pics/scene/16/07/261607_1_scenedefaultsoft_1_773_515_crop_fbb69b79.webp
Without crop:
https://public27-content.cdn-medias.com/pics/scene/16/07/261607_1_scenedefaultsoft.jpg

Scrape big/original image from Dorcel Club

---

scrapers/TheBroNetwork.yml

Add performer scraper to TheBroNetwork.yml

---

scrapers/BelAmi.yml
scrapers/Freshmen.yml

Add performer scraper for both BelAmi and FreshMen scrapers

BelAmi & FreshMen Performer scraper

---

scrapers/luxeplayhouse.yml

This is a new xpath scraper for luxeplayground.  I tested this scraper against four scenes, and things looked good imo.
Tested against:
- https://luxeplayhouse.com/trailers/the-mechanic.html
- https://luxeplayhouse.com/trailers/what-do-you-do-for-a-living-02.html
- https://luxeplayhouse.com/trailers/the-boss.html
- https://luxeplayhouse.com/trailers/what-do-you-do-for-a-living-04.html

Add scraper for luxeplayhouse

---

scrapers/TheSensitiveSpot.yml

https://thesensitivespot.com/updates/hotel-rendezvous
https://thesensitivespot.com/updates/sensual-bondage-domination-pt-ii-josie
https://thesensitivespot.com/updates/gg-legwarmers
Added a scene scraper by URL for TheSensitiveSpot.com

Added TheSensitiveSpot.com scene scraper

---

scrapers/BrokenLatinaWhores/BrokenLatinaWhores.py
scrapers/BrokenLatinaWhores/BrokenLatinaWhores.yml

- https://brokenlatinawhores.com/models/beba.html
- https://brokenlatinawhores.com/models/Rosie.html
- https://brokenlatinawhores.com/models/camila2.html
Improves performer age detection; the previous method was unreliable

Improve BrokenLatinaWhores scraper

---

scrapers/RealjamVR/RealJamVR.py
scrapers/RealjamVR/RealJamVR.yml

Boobed Star Shalina Devine
Ivy Ireland’s Cheating Solution
Anal Stream with Haley Spades
Added Scene by Name requiring some Python code. Added minimal required SceneByQueryFragment and added URL extraction for SceneByURL.

RealJamVR scene by name
