stashapp/CommunityScrapers

- scrapers/ManyVids.yml
ManyVids doesn't include the year in their dates, so the date scrapper will always end up spitting out dates like `0000-01-01` for example with a blank year. Should I leave the date scrapper in? Or remove it?
> Adds ManyVids xPath scrapper

- SCENE-SCRAPABLE.md
- scrapers/NewSensationsNetworkSites.yml
Of note the `/tour` part of these links is important, which is why I left it in for the site list.
i.e.
`newsensations.com/tour_ns/` is completely different from `newsensations.com/tour_rs/` with how they have set things up (and thus why they need to be in separate scrapers)
> Adds NewSenstations Network Sites xPath scraper

- scrapers/Clips4Sale.yml
In practice I found my Clips4Sale scraper would fail in certain scene descriptions if they had icons in them after the description like `https://www.clips4sale.com/studio/47321/5246239/milf-jerk-wmv` This fixes that issue.
> Tweak Clips4Sale xPath scraper

- scrapers/BangBros.yml
This fixes an issue with the BangBros scraper pulling dead image links.
If you look at the page source on a video like `https://bangbros.com/video24949/the-afro-fuck` the source for the `img` isn't actually the scene image. The proper one is linked in the `video` though.
> Fix image scraping in BangBros scraper

- SCENE-SCRAPABLE.md
- scrapers/XXXPawn.yml
Had a bit of an interesting use of the subscraper for this one. One domain has the scene date, and one doesn't, so I used the subscraper to be able to pull the scene date regardless of which domain is used. (One site also has better images, so I doubled down and used it there too)
I'm sure I'm missing something silly here but I do seem to be having a date parsing issue:
`
Warning Error parsing date string 'March 5th, 2017' using format 'January 2nd, 2006': parsing time "March 5th, 2017" as "January 2nd, 2006": cannot parse "th, 2017" as "nd, "
`
I'm not sure what I'm doing wrong with the parse format.
> Adds XXXPawn xPath scraper

- scrapers/XXXPawn.yml
Realized after the fact that the .com version has useful tags in the meta.
> Add tags to xxxpawn

- templates/SceneScraperTemplate.yml
I personally would find this useful to have, figured others might as well.
Currently when I create a scene scraper, I duplicate an existing one, then clear out all the existing paths. This adds a blank template that can quickly be duplicated and ready to start building on.
> Add a blank template for url scene scraper

- SCENE-SCRAPABLE.md
- scrapers/Bang.yml
- scrapers/PureTaboo.yml
Adds scrapers for PureTaboo and Bang.com
Since they use CDP latest dev version of stash is required.
For using a a headless chrome instance https://hub.docker.com/r/chromedp/headless-shell/ is recommended
> Add PureTaboo, Bang.com xPath scene scrapers

- scrapers/GammaEntertainment.yml
- scrapers/JulesJordan.yml
This patch set adds performer scrapers to Gamma Entertainment and Jules Jordan.
GE was only tested with Evil Angel, but works well. I also just scrapes the photo and name, which is enough for my needs.
Jules Jordan currently gets the wrong height in imperial units. To fix this I am going to write a post process in go that converts that at some point.
> Add performerByURL and movieByURL scrapers to Gamma Entertainment and Jules Jordan

- scrapers/AssTraffic.yml
- scrapers/LegalPorno.py
- scrapers/LegalPorno.yml
This pull request adds performer support to the LegalPorno scraper. It implements a fragment scraper for scenes that retrieves the correct scene title and URL if a valid scene ID was found. This can be then scraped with the scene by URL parser.
Furthermore this PR contains a scene and performer scraper for AssTraffic.com.
> Improve LegalPorno. Add AssTraffic.

- scrapers/Babepedia.yml
- scrapers/Xslist.yml
Edited the Measurement for performers to be **00x-00-00**.
Some babepedia info contains the cup size some not, this edit change this by always adding the cup size.
Exemple for different format:
```
https://www.babepedia.com/babe/Lexi_Belle (Measurements: 32C-24-33)
https://www.babepedia.com/babe/Piper_Perri (Measurements: 32-18-25)
```
For XsList, sometime the info don't exist so it will use what he have (32-18-25 or only the cup "C")
> Editing measurement format for performer scraper.

- scrapers/RealityKings.yml
RealityKings.com was apparently updated. I needed these changes to make
it work again.
This patch uses the contains function to only look for relevant
obfuscated class, and be more fault tolerant.
> RealityKings: Update to match site again.

- scrapers/Tonightsgirlfriend.yml
This fixes the titles in TG scenes as they were previous coming in with `HD Porn` on the end of their titles.
While I was in here I added a fixed value for the Studio and grabbed canonical URLs (sometimes the URL from navigating to the scene are weird and have extra parameters on them, this cleans up the one we keep on file. EX `https://www.tonightsgirlfriend.com/scenes/tngf_phoenixjohnny2-19253/?&nats=4.10025.58.80.2.0.0.0.0` VS the canonical `https://www.tonightsgirlfriend.com/scenes/phoenix-marie-19253`)
_And added a last updated date_
> Tonights Girlfriend - Fix titles, set studio, and grab canonical URLs

- scrapers/GloryHoleSwallow.yml
The URL for this site switched from `newtour` to just `tour`, I ended up just making the URL more general this time around.
They also redid their layout so I've redone the classes. Doesn't seem to be a way to get the date anymore though
> GloryHoleSwallow update url

- scrapers/AdultDvdMarketPlace.yml
I don't know how you get the `adultdvdmarketplace.com/xcart/adult_dvd/dvd_view.php?adult_dvd_id=` URL.
> Adding Url Matching for AdultDvdMarketPlace.yml 

- scrapers/Babepedia.yml
Fixing exact matches being broken. Description of the problem I'm addressing from Discord:
Made a video of the behaviour https://monosnap.com/file/e519XntdraxzPLyrABnUg8Lc7BEihQ
`Lexi Bell` will return `Lexi Belle`
but
`Lexi Belle` returns `None`
Testing the URL on the actual site it looks like they now redirect exact matches to the model page, thus breaking the scraper if the match is exact.
Partial Example: 
https://www.babepedia.com/search/Lexi%20Bell
Exact Example:
https://www.babepedia.com/search/Lexi%20Belle
---
To resolve this I have the Name field also match against the Name field from a regular performer page, and the URL field also match the `og:url` meta property (luckily not contained on partial search pages)
> Fix Babepedia exact matches

- scrapers/Trans500.yml
- scrapers/Trans500espanol.yml
Found that if you go to the espanol version. e.g. `/tourespanol/` instead of `/tour/` or `/tour3/` in the URL, there is more metadata showing at the scene-page. Here's both versions, since studio is then missing on the espanol part...
Supported Site|Scraper|Content
------------- | ------------- | -------------
trans500.com/tour/|Trans500.yml|Trans
trans500.com/tour3/|Trans500.yml|Trans
trans500.com/tourespanol|Trans500espanol|Trans
Perhaps using Subscraper, could combine them into one, and support the "standard url path" with all fields from both.
> Trans500 normal and espanol scraper of their site

- SCENE-SCRAPABLE.md
- scrapers/GirlsRimming.yml
Things of note:
- The performer names are listed below each video in related videos and on the performer pages like `https://www.girlsrimming.com/tour/models/alessa-savage.html`, however I could not find a want with a subscraper to get there
- Anything that is part of a series has a date listed on here `https://www.girlsrimming.com/tour/series/series.html` but again, couldn't find a way to get what I need with a subscraper
- Most video has their tags properly listed in the keywords metafield. There are a few poorly entered scenes though like `https://www.girlsrimming.com/tour/trailers/Switch-Me-On-Ep2-Rim-the-Realtor.html` where for some reason the tags field contains a copy of the scene description instead.
> Adds GirlsRimming xPath scraper

- README.md
- SCENE-SCRAPABLE.md
- scrapers/StasyQ.yml
Of note, all the regex steps that use the schema data have a second step to return a blank result in the case of missing data. Like for example this model `https://www.stasyq.com/m/SalsaQ` where the majority of info is missing.
> Add StasyQ xPath scraper

- scrapers/NewSensationsMain.yml
FYI The weird regex around the date is because the site in not consistent with their date formatting. 
Example:
`https://www.newsensations.com/tour_ns/dvds/ScoobyDooAXXXParody.html`
vs
`https://www.newsensations.com/tour_ns/dvds/in-the-room---family-affairs.html`
Luckily their oldest DVD is 2009 so we can construct the year always starting with `20`
> Adds movie scraper to NewSensations

- scrapers/javlibrary.yml
I guess it's useful if you are too lazy to remove yourself the extension and other thing...
If you use the `sceneByFragment` and your title is incorrect, it will remove common word, thing that can appear in file.
You still need to save after...
So:
sceneByFragment (Incorrect title) -> Save -> sceneByFragment -> Save
> Adding a way to correct the Title for Javlibrary

- scrapers/AdultEmpire.yml
Updating AdultDVDEmpire to also function as a scene scraper. This allows for movies that might be a single file to be scraped easily. As well as allows for performer and tag scraping.
I tweaked the Synopsis portion as well as it left out multiple paragraphs as well as words that had been bolded, italicized, etc (example `https://www.adultdvdempire.com/47239/taboo-porn-movies.html`).
Also made it scrape the URL so that all the query parameters normally on a URL from this site can be cleaned away.
Trying to figure out how to get the Rating scraping to work too
> Allow AdultDVDEmpire to also function on scenes + tweaks

- scrapers/javlibrary.yml
https://regex101.com/r/0JCwtY/2
Not exactly same regex that Bnkai posted in comment of the PR
Note: You will need the latest develop version (October 22)
> queryURLReplace for JavLibrary

- scrapers/ChristianXXX.yml
There was a problem with Image, the protocol was missing (`//www.pure-ts.com/tour/content/contentthumbs/12462.jpg`) so the image don't scraped correctly in stash.
This regex shouldn't break thing, it replace the `//` at start with `https://`
> Fix ChristianXXX.yml

- scrapers/FrolicMe.yml
- scrapers/Mypervmom.yml
- scrapers/VNAGirls.yml
Fixes invalid scraper configurations on:
- `FrolicMe.yml`: `parseDate` was inside `replace`.
- `Mypervmom.yml`: Odd tag name selector. Sites don't seem to list tags so I just removed the selector.
- `VNAGirls.yml`: Duplicate URL.
> Fix invalid scrapers

- scrapers/vixenNetwork.yml
The second class is no longer present on images. The  selector appears to be their primary selector for images.
> adjust vixen cover selector

- SCRAPERS-LIST.md
- scrapers/javlibrary.yml
Since more and more scrapers have been running into issues with Cloudflare I did some reading up on how their scraper protection actually functions.
You can see the sample error JAV was getting here: https://github.com/stashapp/CommunityScrapers/issues/123#issuecomment-706771764
Basically Cloudflare spends 5 seconds testing javascript to make sure it works as a scraper prevention method.
So anytime we get a response like this on a scraper:
It can be fixed by adding CDP with a 5 second sleep to the scraper.
```YAML
driver:
useCDP: true
sleep: 5
```
If a CAPTCHA is hit, that is a whole other story, but this Javascript challenge page is apparently the most common Cloudflare page that scrapers run into. (Info source https://github.com/Anorov/cloudflare-scrape)
> Remove Cloudflare errors from JAVLibrary

- scrapers/Hucows.yml
Changes:
Images: Grab the banner image instead of the screenshot 
Tags: Grab relevant tags instead of all the tags
> update image and tags for hucows scraper

- scrapers/ThePornDB.yml
The query URL passed to the URL downloader must be a valid one.
Process the filename to replace non valid characters
> Fix ThePorndDB filename parsing

- validator/index.js
- Fix: Should count as failed if the YAML could not be parsed.
- Verify that the URLs in each `[type]ByURL` are unique.
```yml
sceneByURL:
- action: scrapeXPath
scraper: sceneScraper
url:
- bar.com/
- foo.com/
- action: scrapeXPath
scraper: sceneScraper2
url:
- foo.com/  # <<< Error
- quux.com/
```
- New option to check if the URLs are sorted (most of them are not).
> [Meta] Update validator

- SCRAPERS-LIST.md
- scrapers/Nubiles.yml
Add missing sites + sort:
- `familyswap.xxx` (scene + gallery) - Closes #287 
- `girlsonlyporn.com` (scene + gallery)
- `hotcrazymess.com` (scene) - Supersedes #128
- `nubilesporn.com` (scene + gallery)
The latter need slightly different Studio Name selectors,
because the non Nubiles-Porn network sites don't have the site name below the video / gallery
and the page title selector can be incorrect for Nubiles-Porn.
I think the same selector for scenes needs to be used for galleries on the Nubiles-Porn but I haven't tested it yet.
The "DRY" (Don't Repeat Yourself) scraper is **an idea**.
I asked for objections on Discord and got none, but I do feel like this **might be** a bit too complex.
The idea behind it is to have less duplicate selectors for sites that are close enough but not exactly …
> Update Nubiles scraper

- scrapers/SARJ-LLC.yml
This pull request does the following two things:
1. Previously for scenes it pulled the portrait cover.  After talking to a few people in Discord it sounded like wide covers would be preferred.  The URL for the wide cover is embedded inside an attribute with other text, but if you take the 'cover' url and replace 'cover' with 'wide' it points to the same place.  So I just used a regex to do that.
2. With 0.4.0 galleryByURL was added.  I've tested this on several galleries both recent and from way back at the sites inception and it seems to work.  I've only tested it on one of the listed sites but it stands to reason that if the scene code works across sites the gallery likely will as well since it's all the same backend.
I did run the validator and it checked out as well.
> Update SARJ-LLC to pull wide scene covers and allow galleryByURL

- SCRAPERS-LIST.md
- scrapers/shagmag.yml
Some things to note for this one.
- The title is always a date in the format of `MMMM YYYY` (eg. `January 2020`)
- There is only one upload per month, so we assume the first of the month so we can get a usable date (in reality it can come at any point in the month)
- "Julia Rose" is present on all uploads however her name is not listed on any except the very first so we manually add her
- This causes a small problem where she gets added twice to that very first one but it doesn't break anything
- None of the other content on this site has dedicated pages so none of the videos are scrape-able.
> add shagmag gallery scraper

- validator/index.js
I don't know how I managed to miss this.
```
~\.stash\CommunityScrapers\validator\index.js:337
const cookies = data && data.driver.cookies;
^
TypeError: Cannot read property 'cookies' of undefined
```
> Fix validator error

- scrapers/Clips4Sale.yml
I've tested the details selector for over two weeks. It seems better than it was, but there is no magic/catch-all solution for Clips4Sale. Descriptions are user-generated content and Clips4Sale allow their users to use HTML as they please within that `//div[@class="clip"]/div[1]` element, so one clip's description markup can be wildly different than the next one.
This selector will probably scrape more text than it does currently (as opposed to less 😉)
but it should keep the line breaks for most of it, which will help make the text more readable and easier to trim down when scraping.
The image selector is just a simple fix.
> Update Clips4Sale image and details selectors

- SCRAPERS-LIST.md
- scrapers/GangBangCreampie.yml
Gloryholesecrets was requested in #73 
All pages use the same layout, with the exception of aziani, where the host part is missing from the thumbnail urls.
Since, as far as I know, it is not possible to dynamically compose the URL, I used YAML anchors, which makes it faster, and in my opinion more readable, than a big replace. So in the best case you only have to change the xPath in one place if the layout changes.
> Add aziani and gloryholesecrets to gangbangcreampie xPath Scraper

- SCRAPERS-LIST.md
- scrapers/trafficpimps.yml
There are quite a few changes here. CDP is required to get the cover image.
Just a couple notes regarding the URL changes:
- The pimp.xxx, family.xxx, and petite.xxx URLs redirect to cherrypimps.com and are thus pointless.
- The wildoncam.com URL got commented out as the site has not updated to the new layout that is present on cherrypimps.com and thus none of the selectors will work. Wild On Cam scenes _are_ present on cherrypimps.com however so if they need to be scraped, use the CherryPimps site.
> Fix TrafficPimps Scraper

- SCRAPERS-LIST.md
- validator/index.js
It seems merge keys do work as long as the map key is unique
(see `GangBangCreampie.yml`)
https://github.com/stashapp/CommunityScrapers/blob/d5fe4e6d2cc884d260ec00dfa323bc1d4f9275f4/scrapers/GangBangCreampie.yml#L54-L59
What I tried to do with `Nubiles.yml` (#288) still produces an error:
```
Error loading scraper CommunityScrapers\\scrapers\\Nubiles.yml: yaml: unmarshal errors:
line 187: key "Studio" already set in map
```
```yml
xPathScrapers:
nubileFilmsMultiScraper:
scene:
<<: *sceneScraper
Studio:
Name: //div[@class="studio"]  # example
```
> Enable merge key support in validator

- scrapers/r18.yml
Same regex as Javlibrary but added 1 more step because R18 search is worst than Javlibrary
- It doesn't know PPPD148 but PPPD-148.
For the xpath, it compare the search text to the name of the Movies to avoid mistake
-  HNDS-057 != HND-057 (https://www.r18.com/common/search/searchword=HND-057/)
Changed the name to warn people it's for JAV, because "R18" is not really explicit.
> Update R18 (sceneByFragment + censor)

- SCRAPERS-LIST.md
- scrapers/javlibrary.yml
Got blocked by Cloudflare, so time to update the mirror list. 😋 
```      
- m45e.com/
- g46e.com/
```
No longer exist but redirect to a other mirror (b49t) so if you have old mirror URL in stash, it will still work.
But normally the scraper replace the URL with javlibray.com so you shoudn't have URL with.
Then should i remove these sites ?
> Update javlibrary mirror

- scrapers/javlibrary.yml
Decided to create a mix between Javlibrary and R18.
R18 have a better details/description and can have a different date.
Note: If you are using CDP for this scraper, you will wait **way longer** (15-30sec).
How it works:
- It go to the URL to purchase the movie given by Javlibrary, (`www.r18.com/common/search/searchword=NTRD-085`) 
- Using regex to add the current URL of javlibrary to it by using the `?lg` (language option). (`https://www.r18.com/common/search/searchword=NTRD-085?lg=javmezjhta`)
- If it find the movie on R18, go to the movie page. If not, get back to the javlibrary page by searching into the URL.
- Scrape
-------------
For `queryURLReplace`: Adding a regex to remove "-JG5 or -JG6", file that come from JavGuru, having this broke the next regex so stash don't manage to find …
> Update javlibrary.yml (Subscraper R18)

- scrapers/performer-image-dir.py
- scrapers/performer-image-dir.yml
Adding a plugin to search for performer images in a folder.
This is designed to work with projects like https://github.com/Trizkat/actress-pics.git where there is a folder pattern /performer/image.jpg.
Query returns a folder name and fetch returns the best match image based on user preference.
This scraper requires python.
To use this clone actress-pics to a folder under the scrapers directory.
Update the stash configuration to export this folder to a custom path.
update performer-image-dir.py to use a different folder path, url prefix or image preference.
> Adding a plugin to search for performer images in a folder.

- scrapers/Clips4Sale.yml
A quick fix, needs testing with more scens/studios
I removed the `performers` since i couldnt find scenes with the performers in tags as stated in the original scraper.
> Clips4sale fix

- SCRAPERS-LIST.md
- scrapers/vixenNetwork.py
- scrapers/vixenNetwork.yml
This commit replaces the old XPath scraper with a new script scraper. This eliminates the need for the CDP.
The script performs faster than the existing scraper (due to no CDP) and even includes scene tags.
Python v3.3 or later is required.
> Update vixen scraper

- SCRAPERS-LIST.md
- scrapers/LegalPorno.py
- scrapers/LegalPorno.yml
Legal Porno have moved to a new domain: analvids.com. Their branding is still as LegalPorno so I didn't see the need to change the name of the scraper or the file name, but the URLs needed to be updated.
> Update Legal Porno scraper to new domain

- scrapers/torrent.py
- scrapers/torrent.yml
- scrapers/torrent_parser.py
This is a python scraper to read torrent files for metadata.
If the title field contains the filename of a file downloaded or a .torrent file.
It will look through the configured path for torrent files and see if there are metadata tags for description, tags etc.
This uses https://github.com/7sDream/torrent_parser under the MIT licence (included as torrent_parser.py)
> This is a python scraper to read torrent files for metadata.

- scrapers/MindGeekAPI.py
Fixed regex to correctly match scene ID from scene URL.
Current regex fails to match scene ID if scene name starts from number
E.g: https://regex101.com/r/tEuW9c/1/
Fixed regex should correctly match scene ID no matter the scene name
E.g: https://regex101.com/r/Pt7KxT/1
> Fix found_scene_id extraction from scene URL

- scrapers/vixenNetwork.py
- scrapers/vixenNetwork.yml
Moves the default JSON save location to outside of the scrapers directory.
> Move VixenNetwork default JSON save location

- SCRAPERS-LIST.md
- scrapers/Brazzers.yml
Not fully tested yet
scene changes only
- uses CDP now to get performers 
- the title and date from men was messed up so i used a script selector instead
- added a fallback for the studio when no subsite is present (mainly brazzers)
- added a fallback for the image from a script selector ( mainly for men)
- added scene URL
Also very important
For `brazzers` users must make sure the video URL has the title after the id otherwise we get redirected to the main page
If the user only has till the id part  for the url he needs to add an extra char after it eg for `https://www.brazzers.com/video/123456/` -> `https://www.brazzers.com/video/123456/a` to get to the scene page and then scrape ( thats were the scraped URL is needed)
> Brazzers fix, now CDP is required

- scrapers/performer-image-dir.py
- scrapers/performer-image-dir.yml
As reported on Discord.
~~Fixed to work with Windows paths (by converting them to POSIX paths before making the image URL)~~
Removed the need to set up and use the `custom_served_folders` config option.
Instead the script reads the image data and converts it to a [base64-encoded data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).
I don't use this regularly, but I did ~~2~~ multiple tests with this and it seems to work as intended.
@ me if this needs further work.
> Update performer image scraper

- scrapers/stash-sqlite.py
- scrapers/stash-sqlite.yml
Same concept as #453:
Use `data:image/<type>;base64,<data>` URLs instead of `custom_served_folders` for the performer images.
(slightly different method of obtaining the type of the image)
> Update stash-sqlite scraper to use data image URLs

- scrapers/GloryHoleSwallow.yml
Was previously scraping only the first paragraph of scene description, now all available text will be concatenated, providing a full scene description.
> Fix GloryHoleSwallow Details concat multiple paragraphs

- scrapers/ThePornDB.yml
- validator/scraper.schema.json
Adds authentication to ThePornDB scraper via http headers and an API key.
Make sure to uncomment the `Authorization` header and replace the placeholder `zUotW1dT5ESmpIpMnccUNczf8q4C9Thzn07ZqygE` key with a valid one.
Needs a specific stash version https://github.com/stashapp/stash/pull/1273
> Add headers/authentication to ThePornDB JSON scraper

- scrapers/ZeroTolerance.yml
their SEO wonkiness means sometimes its /better/videos and sometimes its just /videos/
> added alternate url scheme

- scrapers/AMAMultimedia.yml
A higher resolution image is returned by removing the `?imgw=<number>&imgh=<number>` from the video poster URL.
In addition, sort the scraper URLs and split in two groups.
> AMAMultimedia: Higher resolution images, sort URLs

- scrapers/ThePornDB.yml
Fixes the tags when you use the scrape with (scene query functionality)
Tags were removed from the `parser` endpoint so we need to get them from the `scenes` endpoint instead
Uses a subscraper to get the tags from the scene api page
Concat and then Split is needed since `subScraper` returns only a single result
> Fix tags for ThePornDB json scraper

- scrapers/SARJ-LLC.py
- scrapers/SARJ-LLC.yml
Replace the JSON based scraper for the SARJ LLC websites with a more
elabore script.
The scripts supports the same features. Including remapping site ids to
their respective names, supporting the same sites, mapping the same
fields etc.. But also supports some additional features, which are
scraping performers by URL, and scraping scenes and galleries by their
fragments based on name and date. This thus allows to fill in the title
and date for a scene, applying the scraper, and all other information
will automatically be scraped. When scraping information the URL is also
automatically updated. So for example when scraping a scene released by
Viv Thomas but using the metartnetwork.com URL the URL will
automatically be replaced by the URL on vivthomas.com.
Using this script based scraper …
> replace scraper for SARJ LLC with a script

- SCRAPERS-LIST.md
- scrapers/Fit18.yml
Requested from #73 
Non members area is very limited. For the url of the scene search using google or try to use something like `https://www.fit18.com/models/performer-name/scene1` adjusting the performer-name and scene number.
> Add Fit18 xPath scene scraper

- scrapers/data18.yml
Fix #572
Example content [**NSFW**]: `http://www.data18.com/content/394108`
> data18: support day-less dates

- scrapers/AmateurAllure.yml
When a video is recommended below the current scene, performers from that video are scraped instead of the scene's one.
This fixes it.
> Fix Performers on SwallowSalon

- SCRAPERS-LIST.md
- scrapers/VelvetVeronica.yml
- scrapers/velvetveronica.yml
Xpath scraper for velvetveronica.com
Date scraping is a bit iffy. For most videos the year and month of upload can be retrieved from image filename, but not the day. This PR therefore uses 1 for the day.
There are a limited number of old videos on the site that do have full date information in the image filename, but I don't see how to retrieve both forms in an xpath scraper.
> Velvetveronica

- scrapers/LetsDoeIt.yml
An extra test is appended after the title of every video. This removes it.
> LetsDoeIt - Remove extra text in title

- SCRAPERS-LIST.md
- scrapers/PornDB.yml
Update: Thanks to the PornDB team CDP is no longer needed.
~~It _sometimes_ panics on the first scrape with `Could not find node with given id (-32000)`,
and sometimes does not panic, just fails to scrape anything.
But in any case, it seems that consistently the first scrape does not work.
The panic issue might be a race condition in the way clicks are coded in, @bnkai, this might be more up your alley?
`https://github.com/chromedp/chromedp/issues/762#issuecomment-788836126`~~
~~\!\[image](https://user-images.githubusercontent.com/66393006/122960418-0d7b5200-d38c-11eb-894e-0cdd38da9235.png)~~
> PornDB (URL): Remove CDP

- scrapers/multiscrape.py
- scrapers/multiscrape.yml
This will connect back to the stash graphql api and call scrapers in the preferred order for each field.
Specify your preferred scraper in the python file.
> Adding multiscrape python based scraper.

- scrapers/ThePornDB.yml
Entries from theporndb use the parent not the site id.
Scenes have a site specific performer id and this is usually linked to a performer id.
These can be different when a performer uses different names over time or some sites use stupid alias's and only use the first name for example.
You should return the canonical name of that performer.
> Update ThePornDB to use the parent not the site name

- scrapers/IAFD.py
The old xpath would retrieve the wrong performer url if there were links to other performers in the comments section.
> Update IAFD.py performer url xpath

- scrapers/AdultimeAPI.py
- scrapers/AdultimeAPI.yml
If **CONFIG_PATH** is None, `os.path.isfile` would trigger a error.
> Fix bug Adultime API

- scrapers/SARJ-LLC.py
- scrapers/SARJ-LLC.yml
Adds some logging using the new logging infrastructure of Stash.
(And secretly also fixes an issue which meant that fragment based scraping (based on name and date) didn't work unless a URL was set. Never noticed this issue as I was running a slightly modified version containing some logging and apparently this fix which I never made in the repository tracked version)
> Update SARJ-LLC scraper to use new logging

- scrapers/MindGeekAPI.py
- scrapers/MindGeekAPI.yml
For the search, it will use the site present in `MindGeekAPI.ini`, if you want to only search from certain site:
- You can made a copy of this file. (e.g.: `MindGeekAPI_Search.ini`)
- set the variable `STOCKAGE_FILE_APIKEY_SEARCH`.
```py
STOCKAGE_FILE_APIKEY_SEARCH  = "MindGeekAPI_Search.ini"
```
- Remove site/section you don't want.
- The search will use this file instead of the `MindGeekAPI.ini`
You can also filter the site within the search with `{site}query`. Also can contains multiple if separate with comma
Exemple: 
- `{brazzers} Yoga`
- `{brazzers,mofos} Yoga`
Since Mindgeek hate many request, i would guess you can be blocked by doing a search. So using solution above can prevent it.
-----
The site = Section name
```ini
[brazzers] <---- section name
url = 
instance = 
date = 
```
> Update MindGeekAPI (SearchByName)

- scrapers/IAFD.py
Currently the IAFD scraper inconsistently scrapes the performer image, because sometimes the scraped page content around the performer headshot image looks like:
```<div id="headshot"><img title="Photo of ***" alt="Photo of *** data-cfsrc="https://www.iafd.com/graphics/headshots/***.jpg" style="display:none;visibility:hidden;"><noscript><img title="Photo of ***" alt="Photo of ***" src="https://www.iafd.com/graphics/headshots/***.jpg"></noscript></div>```
instead of the expected:
```<div id="headshot"><img title="Photo of ***" alt="Photo of ***" src="https://www.iafd.com/graphics/headshots/***.jpg"></div>```
This results in the image url not getting selected by the current xpath. This PR updates the xpath so it extracts the image url regardless of which html structure is returned which …
> Update IAFD performer image xpath

- SCRAPERS-LIST.md
- scrapers/AdultEmpireCash.yml
- scrapers/AdultEmpireNew.yml
fixes adultempire sites from #123
Removes filthykings, mypervyfamily and touchmywife from AdultEmpireCash and uses a new scraper for them with CDP
myfilthypov and manipulativemedia were removed altogether as they now redirect to other sites
> AdultEmpire fixes

- SCRAPERS-LIST.md
- scrapers/StripzVR.yml
For stripzvr.com. Can create scenes and movies.
* The info is limited due to their web page design.
* Their date format is not consistent. Some is like "1 Apr '21", some is like "1 April '21". And they use a special character: ’ (U+2019).
* Cannot find tags in the webpages.
> Add StripzVR.yml

- scrapers/multiscrape.py
- scrapers/multiscrape.yml
If I don't pass the URL I get an error about fragments not being supported instead of the results.
Example Query for the playground:
```query scrapePerformer($scraper_id: ID!, $performer: ScrapedPerformerInput!) {
scrapePerformer(scraper_id: $scraper_id, scraped_performer: $performer) {
name
url
gender
twitter
instagram
birthdate
ethnicity
country
eye_color
height
measurements
fake_tits
career_length
tattoos
piercings
aliases
images
}
}
```
Variables: 
```
{
"scraper_id": "Pornhub",
"performer": {"name": "Riley Reid", 
"url": "https://www.pornhub.com/pornstar/riley-reid"}
}
```
If you take the URL out it should fail.
> multiscrape: pass url to scrape_performer

- scrapers/IAFD.py
- scrapers/IAFD.yml
I found an IAFD profile that had a birthdate value of `??/??/2000` which is the value the scraper returned. If a valid YYYY-MM-DD birthdate can't be scraped, then it should not be returned since stash won't let you save invalid date values.
> Unset birthdate if it can't be parsed to YYYY-MM-DD

- scrapers/Pornhub.yml
Fixed PornHub fragment scene scraper not working with files that are JUST the video ID. e.g. "ph613244fcca3f8.mp4"
> Fixed PornHub fragment scene scraper

- scrapers/Babepedia.yml
Babepedia wraps certain ethnicities in an <a> now. Fixed the scraper to account for that change. First time doing XPath scraping so maybe look over my work again :P
> Update Babepedia scraper (Ethnicity missing)

- SCRAPERS-LIST.md
- scrapers/WAPdB.py
- scrapers/WAPdB.yml
Adds a scraper for warashi asian pornstars (WAPdB).
Notes:
- Tested on over 100 female profiles and a dozen male ones.
- French/Japanese return partial data as some data is in raw `<p>` tags which were processed in English.
- I could only find one mini profile that had AV activity listed and it was unknown so it isn't supported.
- Characteristics like piercing and tattoos are checked twice as they are sometimes present only in the "distinctive physical characteristics" field or tags
- Some pages will return the default picture. These pictures use the same URL path as the normal ones and there's no way to tell which ones these are. My guess is these were manually changed.
- Some performers have multiple twitter handles listed. This scraper returns the first one.
- Tested on python 3.10 but …
> Add WAPdB python scraper

- scrapers/JavLibrary_python.py
- scrapers/JavLibrary_python.yml
R18 now return 404s for `/searchword={code}` and require search URLs to be formatted as `/searchword={code}/`.
> Fix R18 search in JavLibrary_python fragment scraper

- scrapers/dc-onlyfans.py
- scrapers/dc-onlyfans.yml
This is a fragment based scraper that uses sqlite databases left behind after running the DIGITALCRIMINAL onlyfans scraper https://github.com/DIGITALCRIMINAL/OnlyFans
This script needs python and requests.
This script connects back to stash to find the current path of the video.
If your instance has a password you need to edit the script to include the api key by removing the # and adding it there.
Once it has the path it looks for user_data.db and returns the metadata from there.
> Adding an onlyfans scraper using the DIGITALCRIMINAL onlyfans tool

- SCRAPERS-LIST.md
- scrapers/AnimeCharactersDatabase.py
- scrapers/AnimeCharactersDatabase.yml
- scrapers/DarkRoomVR.yml
This seems to be the first Anime focused performer scraper. It uses Python.
AnimeCharactersDatabase includes characters from:
Anime, Hentai, (Mobile) Games, Eroge, Virtual Idols/YouTubers, Vocaloid
These fields will be populated if available:
Name, Gender, Birthdate, Country, Hair Color, Eye Color, Height, Measurements, URL, Details, Tags, Image
A bunch of additional details and tags can be configured in the .py
> Add AnimeCharactersDatabase

- SCRAPERS-LIST.md
- scrapers/AdultFilmIndex.yml
Hello, we are building a new adult filmography database on AdultFilmIndex.com. We combine the metadata from multiple adult film sources to make a new, comprehensive adult DVD index and database.
We have made a stash-specific API endpoints for scraping the metadata for movies and scenes. The API is in beta, and we have included a key for accessing it, this key is available for all stash users.
This PR includes the parsers for scenes and movies using AdultFilmIndex API. We have tested the parser locally and have determined it working.
> Add AdultFilmIndex parser

- SCRAPERS-LIST.md
- scrapers/Boobpedia.yml
tweaked withoutpant's original scraper from a stash's pull request
requested in #73
- The search functionality is limited by the way the boobpedia api treats white spaces (we cant urlreplace in byName queries in stash so nothing can be done about it atm) and also some results may not be performers. Any search query that  has spaces needs them replaced with `+`. If for example you need to search for `First Last` then use `First+Last`
- boobpedia doesnt seem to have a fixed order for the meta that has to do with metric sizes eg kg/lb, m/feet. I adjusted the regexes to work despite that, let me know if it doesnt work in some cases
- details keeps just the `<p>` part of the descriptions(should be the first paragraph actually), again there are too many variations and i thought that was the …
> Add Boobpedia xPath performer scraper

- scrapers/AdultFilmIndex.yml
Direct scene urls are not picked up by stash parser, since `sceneByUrl` looks for `/api` urls. Updated so that a direct scene url can be used and parsed.
> Fix AdultFilmIndex direct scene urls

- SCRAPERS-LIST.md
- scrapers/CopyToGallery.py
- scrapers/CopyToGallery.yml
For anyone looking for an easier way to tag their galleries. Here is a scrapper I wrote to copy scene metadata to associated galleries. If no gallery is associated with the scene, setting `find_gallery` to true will enable the scrapper to look for gallery zips found within the scene's directory and associate the gallery to the scene as well as tag the gallery with the scene's data. Do not enable `find_gallery` if scenes don't exist in their own directory.
> Scrapper to copy scene data to gallery

- SCRAPERS-LIST.md
- scrapers/SARJ-LLC.py
- scrapers/SARJ-LLC.yml
The API returned links to covers that didn't exist.  This checks if they exist before passing the image link onwards.
> Fix issue with missing scene covers in SARJ scraper

- scrapers/ExploitedX.yml
Fixes the details for excogi (for example `https://exploitedcollegegirls.com/site/trailers/naomi.html` )
Didnt notice anything with the other sites and the fix doesn't seem to break them.
> Fix excogi details (ExploitedX.yml)

- scrapers/xbvrdb.py
- scrapers/xbvrdb.yml
xvbr database has dates in local time instead of UTC. This causes the dates to be one day off if timezone offset is positive.
Parse release date using localtime to fix the issue.
> Fix xbvrdb date parsing

- scrapers/VNAGirls.yml
Spot-checked a few linked sites to verify they have seemingly migrated to a `tag1,tag2` format vs `tag1, tag2`.
Also, something I spent a lot of time debugging but ultimately couldn't solve is the Performer Name parsing. It appears common/normal for these sites to have the performer names formatted as `First1 Last1,&nbsp;First2 Last2`, which, with the split set to `","`, causes them to get parsed as:
* `First1 Last1`
* `&nbsp;First2 Last2`
Nothing I tried (`normalize-space`, trying to use regex to rip out `nbsp;`s) worked. Is there something I'm missing, or is the inconsistent formatting of the site too much for the relatively strict XPath (and/or Stash's use of it) to play nice with?
> Update tag and performer parsing for VNAGirls site

- scrapers/ModelMediaUS.yml
I couldn't find any active /videos/ urls still around but their site's real slow so I didn't really give myself a _ton_ of time to poke around. Figured there's little harm in keeping the /videos/ path around.
> Update Model Media US scraper to support /trailers/ urls

- scrapers/Algolia.py
- scrapers/Algolia_21Naturals.yml
- scrapers/Algolia_21Sextreme.yml
- scrapers/Algolia_21Sextury.yml
- scrapers/Algolia_AddictedToGirls.yml
- scrapers/Algolia_Adultime.yml
- scrapers/Algolia_AllGirlMassage.yml
- scrapers/Algolia_Biphoria.yml
- scrapers/Algolia_BurningAngel.yml
- scrapers/Algolia_ClubInfernoDungeon.yml
- scrapers/Algolia_DevilsFilm.yml
- scrapers/Algolia_FantasyMassage.yml
- scrapers/Algolia_Girlsway.yml
- scrapers/Algolia_PureTaboo.yml
- scrapers/Algolia_RoccoSiffredi.yml
- scrapers/Algolia_disruptivefilms.yml
- scrapers/Algolia_filthykings.yml
- scrapers/Algolia_mypervyfamily.yml
- scrapers/Algolia_touchmywife.yml
- scrapers/Algolia_zerotolerancefilms.yml
I couldn't find an explanation in https://github.com/stashapp/CommunityScrapers/pull/793 nor the git history of Algolia.py as to why this is behaving this way. On the few PureTaboo pages I tested against, it seemed capable of retrieving the male performers just fine.
As far as updating dates, should I update all of the `Algolia_*.yml` configs to reflect this change, since they all depend on this file? Alternatively/additionally, it appears [the Scraper Checker Plugin](https://github.com/stashapp/CommunityScripts/blob/main/plugins/GHScraper_Checker/GHScraper_Checker.py) will only fetch .yml files, so if the main reason we'd want to update the dates is for that script, changing those dates would seemingly just cause unnecessary fetches.
> Add option to scrape all performers in Algolia API scenes, not just females

- scrapers/RealityKingsOL.yml
lesbea & bellesa (and perhaps others) are including trailing commas in the content of the HTML element for the tag - so you end up with a parsed tag like "Socks,". This strips them out and hopefully shouldn't be destructive for any sites that aren't doing this.
> Strip commas from tags

- scrapers/MindGeekAPI.py
- scrapers/MindGeekAPI.yml
updates the MindGeekAPI script to use log.py so that not all log items are received as errors like:
> [Python] update MindGeekAPI to use log.py

- SCRAPERS-LIST.md
- scrapers/DLsite.yml
- scrapers/dlsite.yml
Adds an xpath scraper for dlsite.com. I've only supported Japanese and English but Chinese and Korean should have partial data. The reason I've used text selectors is because the main table can omit/add information so ordinal paths won't be consistent.
> Add dlsite scraper

- scrapers/Xhamster.yml
xHamster added an extra `<nav>` element around the information about channel, performers and tags.
> xHamster: fix studio, tags and performers extracting

- scrapers/data18.yml
Tweaks the duration selector mentioned in #123 and fixes a typo in the details pp.
For movies that have a `proper` duration that is used and we then fallback to the plain  text to catch cases like `120 min`
Sample movies `https://www.data18.com/movies/1225101-raw-43` , `https://www.data18.com/movies/1231098-it-takes-three-6` mentioned in #123 work fine. Problematic movies `https://www.data18.com/movies/1239543-naughty-little-sister-6` also seem to work ok. If there is another case please mention a URL or the format used.
> Tweak data18 movie duration selector/pp

- scrapers/Pornhub.yml
Fixes to the pornhub scraper
- Now grabs the URL properly during scene scrapes
- No longer grabs the "description" / "details" because this always returns boilerplate text
> Pornhub fix

- scrapers/Pornhub.yml
As discussed on Discord, the latest Pornhub update removed the Details field because it's all boilerplate.
Turn out, this is only true for **most** scenes.
This update attempts to add scraping of description when it's available.
Used this scene for reference, could not find other examples.
`https://www.pornhub.com/view_video.php?viewkey=ph5acbe62b84b39`
> Pornhub - scrape description when available

- scrapers/ManyVids.yml
Was running into an issue with scenes like:
- https://www.manyvids.com/Video/306013/Fuck-Mommys-Ass/
- https://www.manyvids.com/Video/81196/deepthroating-university-police/
The previous selector pulled from the metadata property which would drop any `<br>` tags. This now pulls from the actual description section on the page. and concats the paragraphs with a double new line to preserve the original format.
Not many ManyVids creators use multiple paragraphs so it makes sense that this flew under the radar before.
> ensure descriptions keep their paragraph structure

- SCRAPERS-LIST.md
- scrapers/GayAdultEmpire.yml
This is almost identical to the AdultEmpire.yml, but it's far easier to clone that scraper than to modify it to handle a completely different base url sometimes.  (I mean, maybe someone else could do it, but I had no luck when I tried, and honestly, this was a quicky solution for a handful of movies I wanted to scrape that the main site didn't list)
> Clone of AdultEmpire, for the gay version of site

- scrapers/IAFD.py
- scrapers/IAFD.yml
When a scene in IAFD has no release date listed, the field will have the value `No Data`. When that field is scraped, the scraper tries to parse the string as a date value and then convert it to a Stash date format. That conversion fails when the value is `No Data`, but then the scraper just leaves the `date` field as `No Data` which Stash then rejects when you try to save the scene.
This change tweaks the logic, so if parsing of the scene's release date fails, we set the scene/movie date back to `None` so that Stash doesn't try to update it to an invalid value.
> Correctly handle missing scene/movie dates for IAFD scraper

- scrapers/rb_common/README.md
- scrapers/rb_common/configs/README.md
- scrapers/rb_common/configs/config_base.rb
- scrapers/rb_common/configs/stash_config.rb
- scrapers/rb_common/configs/stashdb_config.rb
- scrapers/rb_common/graphql/README.md
- scrapers/rb_common/graphql/graphql_base.rb
- scrapers/rb_common/graphql/stash.rb
- scrapers/rb_common/logger.rb
- scrapers/rb_common/rb_common.rb
This is my initial implementation of the rb_common shared interfaces similar to what we have available for python scrapers. I started with a 1:1 of the python design and the refactored from there to what I feel is a better long term design. Both the config and graphql have a base class so that different child classes (for example on configs I now have a separate one for Stash and StashDB, where previously there was just one for stash) can have a common API. This also worked will since `stash_graphql` is now a child class, and the base query method is in the base class so that other common api interface (maybe a stashdb one in the future) can share that method.
The graphql interface has a third party dependancy on the `faraday` gem which I have included in my PR that adds Ruby to stash …
> initial implementation of rb_common

- scrapers/ThePornDB.yml
Uses the  `small` image for searching and the `full` image when scraping as it was supposed to be (for some reason it was doing the reverse )
> Use full image for ThePornDB scraper

- scrapers/AdultPrime.yml
The images on the search results page are lazy loaded, and only 4 at a time. In order to use CDP to click through them, it takes a long time, so it's commented out by default.
Also fixed the scene scraper to correctly find the date, skip the image if it's their placeholder and add the URL and details.
> [AdultPrime] Add search

- SCRAPERS-LIST.md
- scrapers/IFeelMyself.py
- scrapers/IFeelMyself.yml
Added a performer scraper to scrape the (limited) amount of data available.
Fixed issues with scene scraper not finding scene when the results from search with the default filename of artist-id+video-id where over mutliple pages.
It seems browser will not keep cookies coming from site over multiple site visits. So changed to directly set required cookies for search and go directly to search results.
Added the option to set the authentication cookie value to effectively have the browser logged in during scraping which results in being able to scrape more information from performers and some videos with certain tags which will not show up in search unless logged in. Requires an active subscription as far as I know to work.
Not sure if an option like that is wanted in a scraper?
> updated ifeelmyself scraper to include performer scraper and fix some issues with scene scraper

- scrapers/Xhamster.yml
- Add URL
xHamster scene id can be
either a sequence of digits
or a sequence of letters and digits (typically starting with xh)
yt-dlp save files in the format
`<title> [<id>].<ext>` by default.
This PR relies on this format to recover the id.
Example file names:
`The devil’s dice! (Hentai JOI) [xhW6bPm].mp4`
`TUSHY - Being Riley Chapter 2 [5056783].mp4`
> Update xHamster scraper

- scrapers/SpankBang.yml
- no performers found on the page anymore;
- meta description is bogus, actual details rarely but exist;
- ~~added date (independent from another PR)~~ merged with master to account for another PR;
- tags - previously existed markers plus searches that function as tags.
SpankBang scene id is a sequence of lowercase letters and digits,
no less than 4 characters long afaik.
yt-dlp save files in the format
`<title> [<id>].<ext>` by default.
This PR relies on this format to recover the id.
Example file names:
`Hell Is Where The Party Is [2bgur].mp4`
`Keep on Cumming [60my5].mp4`
> Update SpankBang scraper

- scrapers/JavLibrary_python.py
- scrapers/JavLibrary_python.yml
Changes:
- Add new field that recently added to Stash: Studio Code and Director
- Reorganize fields: move DVD code from Title to actual Code, move scene title from Details to actual Title
- Add option to strip (or not) DVD code from Title
- Disable Details parsing since there are no real details in JavLibrary
- Add Label and Performer name order. This features are not supported by Stash yet, but why not implement it in advance? JAV progress in Stash tracked in stashapp/stash#3065
- Reverse Performer name order only if explicitly selected. Set Western name order for Japanese performers is ~~always a silly idea~~ not always preferable, so it better to have option to control that.
> Add Studio Code and Director (and some more) to JavLibrary_python

- scrapers/Algolia.py
Closes #1188
``?format=webp`` missing in front image request. Without this parameter, image gets cropped at the top and bottom.
> Fix GammaEntertainment movie cropped images

- scrapers/BaDoink.yml
- scrapers/SexLikeReal.yml
- scrapers/VRBangers.yml
- scrapers/VirtualRealPorn.yml
Some studios have a filename descriptive enough that we can build the scrapping url from it and then use the existing scrape by url.
To use simply pick the scrapper either when identifying or from the dropdown in the scene editor
> Add scrapping by official filename to a few scrappers

- scrapers/JavLibrary_python.py
- scrapers/JavLibrary_python.yml
Some tags in JavLibrary aren't meanigless, but just obfuscated. Looking at their Japanese original name, we can guess what they really mean.
> JavLibrary_python: replace some obfuscated tags

- scrapers/Kink.yml
The existing scraper for kink.com parses the studio as `ts-seduction` for TS Seduction scenes. This is the correct studio, but needs to be mapped to the studio name as seen at stashdb: [TS Seduction](https://stashdb.org/studios/ad0ebf7c-a23e-4c62-a149-b1b99fa14b7c)
> map all Kink sub-studios

- SCRAPERS-LIST.md
- scrapers/FamilyTherapyXXX.yml
Adds analtherapyxxx.com to the existing FamilyTherapyXXX scraper.
It is another site under [RSGH Media](https://stashdb.org/studios/e42f2af3-d410-4bb4-bb5c-1b5fbbb07eae)
> add analtherapyxxx.com

- SCRAPERS-LIST.md
- scrapers/KBProductions.py
- scrapers/KBProductions.yml
Tested this against a few Inserted and Ricky's Room pages. Old Inserted URLs (with the /tour/ paths) are still parseable with this update (since those redirect to the new URL structure), so I figured I'd leave them around for now as opposed to breaking the scraping for them.
> Fix KBProductions Parsing and Start Parsing Ricky's Room

- scrapers/DreamTranny.yml
This adds an alternative xpath for the cover image which works with older scenes, e.g.
https://dreamtranny.com/update/164
Also, the URL for a scene is typically like https://dreamtranny.com/update/844/?nats=MC4wLjMuMTUuMC4wLjAuMC4w&step=2
The URL addition here will change the URL to remove the redundant query parameters, e.g. https://dreamtranny.com/update/844
> Improve dreamtranny

- SCRAPERS-LIST.md
- scrapers/GammaEntertainment.yml
- scrapers/TSPlayground.yml
The tsplayground.com site has been relaunched and the existing scraper in GammaEntertainment no longer works.
These changes move the site to its own scraper (sceneByURL and performerByURL)
Example studio scene URL: https://tsplayground.com/video/valentina-bittencourt-and-alex-1985.html
Example performer URL: https://tsplayground.com/models/valentina-bittencourt-380.html
> move tsplayground.com to its own scraper

- SCRAPERS-LIST.md
- scrapers/R18.dev.yml
This adds a scraper for https://r18.dev. R18.dev is a mirror of all the data that R18.com had, but with R18.com going down this site will be needed for future updates. I think they pull in new data too from DMM too, so it should be useful going forward. The R18 family of sites are especially good for translated titles/descriptions compared to the other JAV websites.
I've left some comments on some of the future enhancements that it can maybe support if the R18.dev website refactors their API a bit as well as some potential areas of cleanup during that same refactor.
> Add scraper for R18.dev

- scrapers/Hypnotube.yml
First time submitting a pull request, so apologies if I've made a hash of it.
I've made a change to the Hypnotube.yml scraper so that it pulls in the main thumbnail for the video (as seen on the front page/video list view). This thumbnail seems to be the best representation of videos from the site.
Tested on my own instance of Stash and validated via the validation script, which comes back clean.
> Update Hypnotube.yml to pull in main video thumbnail

- SCRAPERS-LIST.md
- scrapers/Iwara.yml
sceneByFragment relies on the default filename format from Iwara:
`<unix_timestamp>_<id>_<resolution>.<ext>`
Example file names:
`1543383579_G5mzkTeE5i7AJoe8_Source.mp4`
`1550374900_z028Qt4K7GIkyYbAD_540.mp4`
> Add scene scraper for (ecchi.)iwara.tv

- SCRAPERS-LIST.md
- scrapers/Algolia.py
- scrapers/Algolia_Adultime.yml
This adds the agentredgirl.com site to the existing Adulttime scraper using Algolia API
example scene URL: https://www.agentredgirl.com/en/video/agentredgirl/Amys-Big-Wish-Episode-2--3/176036
> add agentredgirl.com to Algolia_Adultime.yml

- scrapers/VRBangers.yml
This just changes the studio name scraping for VR Bangers and its network sites, as currently it is incorrectly scraping network sites (e.g. vrbtrans.com) as "VR Bangers".
Here are example studio scene URLs, for each of the scraper's domains, that have been tested as now working correctly:
- https://vrbangers.com/video/anal-virginity/
- https://vrbgay.com/video/feeding-frenzy/
- https://vrbtrans.com/video/the-heartbreaker/
- https://vrconk.com/video/thor-love-and-thunder-a-xxx-parody/
> fix studio scraping for VR Bangers (and network sites)

- scrapers/Algolia.py
- scrapers/Algolia_Biphoria.yml
In some sites eg biphoria the `sitename` isn't populated so search results end up without a URL and thus can not be selected.
For those cases as a quickfix the `SITE` from the argument given to the script is used instead.
Ideally and if more cases like this are reported we should map studios/sites to sitenames
> Fix algolia search

- scrapers/Algolia.py
The galleryByURL scraping is not working (JSON marshalling error). This change fixes it.
Example gallery URLs:
- https://www.evilangel.com/en/photo/Isabela-Fontaneli-Lara-Lopes-TS---TS/101070
- https://www.transgressivexxx.com/en/photo/TS-Isa-%2B-TS-Lara-%2B-Stud--Anal-3-Way/101646
Also, the scraped URL was being created as the _video_ scene URL, which means any subsequent scrapes of the gallery (e.g. for updated info) will not work. The actually gallery URL is scraped by creating it in the form that is seen on the sites.
> fix gallery scraping via algolia

- scrapers/Oldje.yml
In the Oldje scene scraper the performer names were not being picked up and the image was not being loaded.
Performers using a new layout so added fix, and fixed the image not being loaded by removing redundant brackets
> Fix Oldje scene performers selector

- scrapers/VRBangers.yml
It looks like VRBangers and/or VRBTrans altered the CSS styling so the class names are a little different here and there.
This tweaks the scraper to work with the updated CSS on vrbtrans.com scenes, e.g.:
- https://vrbtrans.com/video/date-night/
and the scraper works with other sites in the scraper, e.g.:
- https://vrbangers.com/video/my-milfshake-is-better-than-yours/
I've chosen to extend the existing scraped properties in case some sites/scenes use the older styling.
> fix VRBangers script for vrbtrans.com

- scrapers/FilthyFamily.yml
filthyfamily.com appears to now be fully behind a paywall, so existing stashdb scenes such as https://stashdb.org/scenes/08a9c8ad-87c8-49ce-9b8a-88400b32e7ce with studio URL https://filthyfamily.com/video3409033/julz-the-virgin-fucks-her-step-parents end up redirecting to https://filthyfamily.com/?warning=false where all the clickable links are /join URLs
HOWEVER... the mobile.filthyfamily.com site is still at least partially browsable, like you can see a list of videos at https://mobile.filthyfamily.com/videos and a second page at https://mobile.filthyfamily.com/videos/2
each of the listed scenes can be clicked to go to that scene, e.g. https://mobile.filthyfamily.com/video3407991/squirter-and-stepmom-worship-a-cock
and that is what I have rewritten this scraper to scrape, the mobile …
> make filthyfamily scraper work with the mobile site

- scrapers/Arx.py
- scrapers/Arx.yml
The API results gives scenes with two date properties, `createdAt` and `availableAt`. The former is currently the one being scraped and is presumably the recorded or possibly final edit date. The latter is the published date that we are interested in. This change picks the correct date.
The rest of the changes are just to reduce the number of python warnings around casing, overrides of built-ins , etc.
> Use `availableAt` instead of `createdAt` for date in Arx scraper

- scrapers/LetsDoeIt.yml
This adds another xpath matcher for Tags so that it works on transbella.com
E.g. https://transbella.com/watch/5536/gorgeous-latina-tranny-gets-pleased-by-two-cocks-in-wild-italian-threesome.en.html
> xpath, improvement: add tags/categories scraping to LetsDoeIt.yml

- SCRAPERS-LIST.md
- scrapers/WoodmancastingX.yml
After learning about the differences between the Woodman studios in [one of my edits](https://stashdb.org/edits/469bb3a0-8bb6-4714-ac10-f30e3eb4e03e) I figured I'd codify the correct behavior in the community scraper.
Woodman is split into three studios on StashDB:
[Woodman Casting X](https://stashdb.org/studios/cad7ddf0-c24c-4125-a2a3-af4287849364) - Casting scenes, both Soft and Hard. This also includes the older STHUF series of castings, of which there are only 37 and whose separate domain has expired.
[Pierre Woodman](https://stashdb.org/studios/f61bcdb2-1f43-4dd8-98ab-0b46e27e3dcb) - Everything else: stand-alone scenes, BTS content, live show recordings
[Wake Up n Fuck](https://stashdb.org/studios/c130a312-6144-40b7-a76b-cedad9e46707) - Separate series, handled by a separate scraper: …
> Improve studio matching for WoodmanCastingX

- scrapers/IFeelMyself.py
Scraping scenes where the description contains any tags (most notably `<i>`, `<b>`, `<strong>`) currently results in string concatenation without any spaces.
For example [this scene](https://ifeelmyself.com/public/main.php?page=flash_player&out=bkg&media_id=21833&artist_id=f15831) has the HTML `No one really <i>likes</i> doing chores [...]` which was turned into "No one reallylikesdoing chores [...]"
Telling `get_text` to use a space as the separator fixes this issue and produces "No one really likes doing chores [...]"
> IFeelMyself: fix styled text in description missing spaces

- SCRAPERS-LIST.md
- scrapers/MindGeek.yml
This improves the MindGeek.yml scraper to add scene Studio Code and scene Movies to the `sceneByURL`  scraper.
Not all scenes have a corresponding movie. Example scene URLs that can now scrape the scene's studio code and corresponding movie:
- https://www.doghousedigital.com/scene/8735141/teen-anal-scene-2
- https://www.iconmale.com/scene/8531671/hot-daddies-4-scene-3
- https://www.milehighmedia.com/scene/8694661/cream-pie-virgins-8-scene-4-not-so-innocent
- https://www.noirmale.com/scene/4392840/gym-rat
- https://www.realityjunkies.com/scene/8636861/big-boob-babysitters-scene-3-adult-playdate
- https://www.sweetheartvideo.com/scene/8696661/lesbian-beauties-22-interracial-scene-4-interracial-love
- https://www.sweetsinner.com/scene/8735271/the-seductress-4-scene-4-seduce-me
- …
> add Movies and Code to sceneByURL in MindGeek.yml; add more sites to movieByURL

- SCRAPERS-LIST.md
- scrapers/DreamTranny.yml
The dreamtranny.com site doesn't have a gallery section in the non-member preview/tour of the site.
This change allows a photo set to be scraped from the corresponding video scene page, e.g.
https://dreamtranny.com/update/626/
Performers can now be scraped, e.g. https://dreamtranny.com/models/325/
Additionally, the studio code can be scraped from the URL, so I have added that to the scene scraper.
> add gallery and performer scraper to dreamtranny.com

- SCRAPERS-LIST.md
- scrapers/GroobyClub.yml
- scrapers/GroobyNetwork-Partial.yml
Grooby sites appear to have recently added tags to their scenes.
This change adds tag scraping.
It also adds support for additional Grooby network sites.
Tested as working for scenes at various sites. Have not been able to confirm the gallery scraping with tags is working or not, as galleries seem to be not accessible in the free/preview/tour view of the sites.
> xpath, improvement: Add tags to Grooby

- SCRAPERS-LIST.md
- scrapers/UnderHentai.yml
Store this file in the ~/stash/scrapers/UnderHentai.yml (If the scrapers directory is not there it needs to be created).
The scene Scraper by Fragment is the best option in case the file name is the name of the anime.
Scenes that were not found can easily be found by the name scraper.
Don't put the episode number otherwise it won't find it.
It is also possible to scrape individually with the anime URL.
The scraper doesn't recognize the episode number, I recommend changing it manually at the end.
> Add scene scraping for underhentai.net

- scrapers/ThisVid.yml
* Now uses video id for Studio Code (as mentioned in the [original PR](https://github.com/stashapp/CommunityScrapers/pull/1274))
* Adds performerByURL scraper for fetching name, photo, country, birthdate and gender from a member page if available.
I'm well aware that the majority of ThisVid members simply upload videos they've found on other platforms, but for any actual content creators on there I'd figured we should be able to scrape them.
> Improve ThisVid scraper

- scrapers/MenAtPlay.yml
Seems that MenAtPlay has two different formats for the description block the scraper uses for details: one `<p></p>` per paragraph, and one big `<p></p>` with paragraphs split by `<br><br>`. The current scraper only worked for the former; all paragraph breaks get dropped with the latter. This change to the scraper makes it preserve paragraph breaks with both.
> MenAtPlay: Fix line breaks in details

- scrapers/RandyBlue.yml
Updates the xpath scraper to work with the new site layout
Example URLs:
- https://www.randyblue.com/scenes/orlando_vids.html
- https://www.randyblue.com/scenes/ezra-finn-goes-bareback-and-lukas-valentine-takes-his-load_vids.html
- https://www.randyblue.com/scenes/dicks-everywhere-with-kurtis-wolfe-lance-alexander-roman-todd_vids.html
> Update RandyBlue for new site layout

- scrapers/MindGeek.yml
Some sub-studio domains now redirect to the network site homepage, e.g.
https://www.momsbangteens.com/scene/4411883/
is now
https://www.realitykings.com/scene/4411883/do-not-fuck-around-with-my-stepmom
on the latter, current page, the (sub) studio is show in the "Subsite" section of the page. This change adds the text of the substudio link to the existing xpath union/alternatives
> fix/improvement, xpath: use subsite (sub-studio) at realitykings.com

- SCRAPERS-LIST.md
- scrapers/MindGeek.yml
This adds `galleryByURL` for transsensual.com by using the (video) scene URL.
The video scenes at transsensual.com have corresponding photo sets, but the public/free/preview view of the website does not have gallery URLs. This change allows a gallery to be scraped by using the scene URL instead, as the data will be identical.
Example URL: https://www.transsensual.com/scene/4488881/when-the-mans-away-a-lady-shall-play
> xpath, improvement: Add gallery by url for transsensual

- scrapers/Mylf.yml
Currently the scraper only gets text from the matching `<div>`, so scenes like https://www.mylf.com/movies/concept-maid-in-heaven don't get the Details scraped as the text is in a child `<p>` tag within the `<div>`
this fix gets text from all elements within the div, see example scene URL HTML and try scraping with/without this fix to see it in action
> fix: mylf.com - get details/description text from all element in div

- scrapers/javdb.yml
Fixed javdb.yml scraper by changing javdb36.com to javdb.com for both regex and cookies
I tried using javdb but javdb36.com seems to be no longer accessible (atleast from Germany or USA/Luxembourg with VPN)
It works perfectly fine now on my stash instance even for FC2 files when paired with a login cookie.
> Updated javdb.yml

- scrapers/SexBabesVR.yml
The scraper appears to be for a layout that has now changed.
Example scene: https://sexbabesvr.com/video/the-best-plans
Note that the date presented on the scene pages is in "mmm dd" format without the year, so it doesn't look like the year can be determined from the scene page.
With these changes the date is scraped, e.g. 0000-03-25, so at least the day of the month and month are present and the person scraping can just replace with the correct year.
> fix: sexbabesvr - fix for updated layout

- scrapers/Hustler.yml
This adds another xpath selector for the existing Hustler.yaml scraper so that it can get the cover image for scene pages, e.g.
- https://www.hustler.com/model/charity-bangs/movie/20151116/black_cock_justice_pt__2
- https://www.hustler.com/model/madelyn-monroe/movie/20151123/black_cock_justice_pt__2
I left the existing selector in case there are different styles/layouts for scene pages where the existing selector will continue to work.
> xpath, improvement: add another xpath for image for Hustler

- scrapers/Transerotica.yml
The Date scraping does not currently work, as it selects the duration text. This change fixes the selector to grab the commented date text, and then extract the MM/DD/YYYY date.
The fixed studio name should be TransErotica, to match that on stashdb, so I've done that too.
> xpath, fix, improvement: transerotica.com - fixes the Date and Studio Name

- SCRAPERS-LIST.md
- scrapers/GroobyNetwork-Brazilian.yml
- scrapers/GroobyNetwork-Partial.yml
The brazilian-transsexuals.com and tgirlsfuck.com sites have changed their HTML layout code which now uses the same CSS classes as in the majority of other Grooby sites.
This change just moves the domains over. The braziltgirls.xxx site still uses the old layout style.
> fix: move brazilian-transsexuals.com and tgirlsfuck.com to other Grooby scraper

- SCRAPERS-LIST.md
- scrapers/Algolia.py
- scrapers/Algolia_Adultime.yml
This allows `galleryByFragment` to be added to any scraper yaml that uses Algolia.py script, to add `Scrape With...` option to the gallery to allow search by Title (Saved), e.g.:
- Caught In The Shower
gives https://www.oopsie.com/en/photo/Caught-In-The-Shower/92293, which _would_ be the gallery URL (by convention) if the oopsie.com site had a Pictures section, but it does not.
So this allows Studios without public/free/tour galleries, that have scene photosets, to be scraped from the Algolia API.
For reference, the gallery corresponds to scene:
- https://oopsie.com/en/video/oopsie/Caught-In-The-Shower/201547
Title (Saved): Love Is In Your Future
gives: https://www.asmrfantasy.com/en/photo/Love-Is-In-Your-Future/96680
(which is not public)
but is the photoset for …
> script, improvement: add galleryByFragment to Algolia.py / Algolia_Adulttime.yml

- scrapers/POVR.yml
Only tested the scraping part of #1377 but a helpful user on Discord mentioned that actually saving the images from the scraped URL wasn't working in Stash: this should fix that by using the image host for POVR itself no matter which subsite you scrape from
> Fix 403 unauthorized error when scraping from POVR subsites

- scrapers/Pornhub.yml
Before: https://regex101.com/r/8goDRc/1
After: https://regex101.com/r/pGrS9o/1
> Pornhub: Fix URLs no longer having `ph` before the ID

- scrapers/Redgifs.py
- scrapers/Redgifs.yml
- Redgifs videos do not have titles, so any search functions of this scraper are not real searches/only work with exact gif IDs or filenames
- It uses [Temporary tokens](https://github.com/Redgifs/api/wiki/Temporary-tokens) for the API, that do not require credentials. The user could run into rate limiting (maybe when identifying many scenes at once)
- Ignores gif description, because it is useless on 99,9% of gifs (mostly advertisement links)
> Add Redgifs Parser

- scrapers/Pornhub.yml
They seem to rehydrate data on the clientside instead of sending it as HTML like they used to, so we'll just grab the data from their JSON
> Fix Pornhub scene scraping

- scrapers/GroobyClub.yml
Noticed that the subsite scrapers weren't getting any metadata so I updated them for the new layout: they don't have the tags yet, so users might still want to scrape using the grooby.club URL instead. We can't use a subscraper to grab the tags either because subscrapers only work for single selectors ATM
I'll probably get around to rewriting this entire scraper in Python to solve the issue of tags but for now this will work
> Update GroobyClub for new layout

- scrapers/Algolia.py
- scrapers/Algolia_Adultime.yml
This tweak to the Algolia script scraper allows a gallery to be scraped from the (video) scene URL.
This is for situations where the studio site does not have (public/free) gallery URLs, but each scene has a photo set, e.g. transfixed.com consistently has 35 image photo sets for each scene
scene URL: https://www.transfixed.com/en/video/transfixed/Cater-Waiter-Quickie/230414
With this PR's changes, that scene URL can now be used to scrape the gallery for the photo set.
Also added accidentalgangbang.com to galleryByURL, as that site has public/free galleries, e.g.
https://www.accidentalgangbang.com/en/photo/In-Laws-In-Need/109962
is now scrapable.
> allow Algolia to scrape gallery from scene URL

- SCRAPERS-LIST.md
- scrapers/CamWhorestv.yml
A basic xpath scene scraper for camwhores.tv. This will even work on URLs to videos that have been made private by users as all the necessary HTML is still visible on the page.
Note that most videos on this site are uploaded by random users, so I decided not to bother using their username as studio.
You can grab any video off `https://www.camwhores.tv/latest-updates/` to test, even those marked private, otherwise here's a couple of sample URLs:
`https://www.camwhores.tv/videos/2329963/asiandreamx-oil-my-ass-in-private-premium-video-7ef0594b-6de4c6bd7b89daac/`
`https://www.camwhores.tv/videos/6940762/rorriegomez-june-09-2021/`
Also, I didn't bother adding a performerScraper because if you look at pretty much any model page (e.g. `https://www.camwhores.tv/models/rorriegomez/`) you can see …
> Added xpath scenescraper for camwhores.tv

- scrapers/EroProfile.yml
Noticed a bug in my EroProfile sceneScraper the other day where if a video has NO description but does have at least 1 user comment, the first comment will be scraped and parsed as the Details field because it will be the first `<p>` tag it finds after the title.
Simple fix by ensuring the scraper only looks for a **_following-sibling_** `<p>` tag after the title, rather than just the next `<p>` anywhere on the page.
URLs to the mobile version of video pages were unaffected.
The video I had this happen on seems to have deleted the comment now and it took me a while to find another video where I could show this bug occurring and my fixing of it, but here's one with no description but a comment:
`https://www.eroprofile.com/m/videos/view/Wife-beach-fucked-by-stranger-filmed-by-hubby-2018`
If …
> Fixed bug in EroProfile sceneScraper when a video has no description

- scrapers/ColbyKnox.yml
Colby Knox launched a new website design a couple weeks ago, and naturally that broke the scraper. This PR fixes it for the new website design. Checked it against content of various vintages, and it worked okay on all of them. A couple of the selectors are a little less futureproof than I'd like, but the new site design doesn't have a lot of semantic classes or ids, so here we are...
> Fix Colby Knox scraper for new website design

- scrapers/Algolia_ActiveDuty.yml
- scrapers/GammaEntertainment.yml
Active Duty is now using Algolia, so this creates an Algolia scraper for Active Duty and drops the Gamma scraper for that site
> Move Active Duty over to Algolia scraper

- scrapers/Rule34Video.yml
When using the scrapeByURL feature, after scraping a scene successfully one day, all subsequent scrapes fail to parse any info. This is most probably due to the popup dialog to accept cookies, or the way rule34 shows other scenes in a modal window instead of the full page.
Using CDP and setting some cookies allows the scraper to scrape more than one scene a day.
> fix: use cookies for rule34video.com

- .vscode/settings.json
- scrapers/IAFD.py
- scrapers/IAFD.yml
- scrapers/py_common/graphql.py
- scrapers/py_common/types.py
`Scraper` was just a fancy dictionary with some convoluted logic for JSON serialization so I replaced its useful methods (`set_value`, `set_stripped_value`, etc) with the helper function `maybe` and just used dictionaries instead
All of the `set_*` methods took an iterable of elements returned by the lxml xpath method and checked if their argument was truthy before performing some action on it and returning the result: usually returning the first result if it didn't match the regex `(?i)no data`
The `maybe` function does the same thing but also takes an optional function f that will be applied to the first element if it exists and does not match the regex `(?i)no data`: this just saves us another if-statement after getting the value
```python
p.height = p.set_value(performer_height)
if …
```
> Rewrite IAFD scraper

- scrapers/CorbinFisher.yml
This PR improves formatting in `CorbinFisher.yml`
- Changed scraper name to title case + spaces for better aesthetics in the UI
- Added space to studio name in scene scraper to match studio name in StashDB
- Removed trailing whitespace
> fix: :art: improve formatting for Corbin Fisher

- scrapers/Baberotica.yml
Studio name mapping was not working, the URL would appear as the Studio name when scraping.  
URLs under "- map:" need the trailing "/" in order for the mapping to the name to work.
> Fixed issue in Baberotica.yml with Studio name map

- SCRAPERS-LIST.md
- scrapers/BoyCrush.yml
This adds a scraper for the two main BoyCrush network sites that have public scene pages: boycrush.com and baretwinks.com.
Both sites have public pages for the scenes of all 5 sites under the BoyCrush network, so the scraper will read which site the video is supposed to be a part of and assign the proper studio. The other 3 sites do not have public scene pages, so URLs for them are not added to the scraper. I figure the idea will be if you want a public link for those sites, you will use the boycrush.com one, because that is the main network site at this point.
> Add BoyCrush network scraper

- SCRAPERS-LIST.md
- scrapers/ATKGirlfriends.py
- scrapers/ATKGirlfriends.yml
Rewrite of #812 with a filename-title-based python scraper. Could be improved by pulling the filename from the DB (or having it included in the input fragment) but this at least works for unmodified files.
> Add performer and scene scrapers for ATK Girlfriends

- scrapers/dc-onlyfans.py
This PR fixes the image scraping functionality of dc-onlyfans scraper.
Currently when the base64 image is returned, it does not appear in Stash when using the `image` key.
Returning as `images` seems to work, perhaps since `image` is due to be deprecated soon?
> fix: :bug: dc-onlyfans - fixed images not scraping

- SCRAPERS-LIST.md
- scrapers/NVGNetwork.yml
nvg is exclusively a paid site so if this doesn't belong I understand and we can just close it. I no longer have access to the site myself but this functioned as of about a month ago and they dont seem to update to often.
Not sure about the user-agent being a header here so if that seems wrong let me know and I can remove it, it does have to be in sync with the cookie though so I felt it was better to have here so if a user updates one seeing the other might remind them that they have to update both.
> add scraper for nvg network sites

- SCRAPERS-LIST.md
- scrapers/RedHotStraightBoys.yml
This PR adds a scraper for [RedHotStraightBoys](https://redhotstraightboys.com/)
Scraper supports:
- sceneByURL
- Title
- Performers
- Name
- URL
- Details
- Tags
- Image
- Studio (fixed: RedHotStraightBoys.com)
- performerByURL
- Name
- Gender (fixed: MALE)
- Image
> feat: add scraper for RedHotStraightBoys

- scrapers/IWantClips.yml
iwantclips.com appears to have changed xpaths that are scrapeable for Title, URL, and Image, so I have changed the xpaths in the scraper to accommodate.
Tested scraper with as many scenes as I could, the majority work fine, however some appear to only have an mp4 as the "image" for the scene and those cannot pull an image URL for stash.
> Fixed xpaths for Title, URL, and Image for IWantClips.yml

- SCRAPERS-LIST.md
- scrapers/StasyQVR.yml
VR sister site of existing StasyQ scraper, but the VR site has a totally different layout so couldn't reuse the other scraper. Tested on a few videos older and newer. Performer page on VR site has zero details and didn't seem worth scraping.
Site is light on video details so scraper should be fairly straightforward, but feedback is welcomed.
> Add StasyQVR XPath Scraper

- scrapers/Algolia.py
Fixing an error when you use the "Scrape with..." on a scene with the Algolia scraper.
For example, EvilAngel scene, the error you'd get: "[Scrape / EvilAngel] KeyError: 'file'".
The "file" field got deprecated, and is now used as "files", see this [link](https://github.com/stashapp/stash/blob/479e7163853bc7e9bd811a6fd0c3d2e905e6147c/graphql/schema/types/scene.graphql#L69). 
- file: SceneFileType! @deprecated(reason: "Use files")
> Fixed "Scrape with..." for Algolia API scraper

- SCRAPERS-LIST.md
- scrapers/RealJamVR.yml
Brand new site (September 2023) made by the RealJamVR folks which seems to have an identical page layout. Updated the Studio name to no longer be fixed and added the new URL, but otherwise seems to work great without any other adjustments from the handful of scenes I tested.
> Update RealJamVR to include PornCornVR

- scrapers/GammaEntertainment.yml
This was supposed to have been done in #1456, but was missed.
> Remove FalconStudios from Gamma scraper

- scrapers/AniDB.yml
Uses a character's unique shortlink to disambiguate performers. 
Some examples:
| character | url | disambiguation |
| -- | -- | -- |
| Pikachu | https://anidb.net/character/69 | ch69 |
| Aqua | https://anidb.net/character/78019 | ch78019 |
| Emilia | https://anidb.net/character/78943 | ch78943 |
| Emilia | https://anidb.net/character/133093 | ch133093 |
> Update AniDB.yml to use shortlink for disambiguating characters

- scrapers/IFeelMyself.py
This caused a None type to return. The video tag appears to be load right away and shares the same information need for the rest of the code to work correctly. Had to add a check to ensure there was a video tag. As some actress have galleries now and these are not lazy loaded and have no video tag.
> Fix for IfeelMyself lazy loading image tags

- scrapers/TheScoreGroup.yml
- Fixed: Description not getting scrapped from gallery pages
- Added the following supported sites
- scorevideos.com
- milftugs.com
> Updated TheScoreGroup scraper

- build_site.sh
Per https://github.com/stashapp/stash/pull/4313
Changes the script to generate dates in UTC, without timezone.
> Remove timezone from date

- scrapers/SARJ-LLC/SARJ-LLC.py
- scrapers/SARJ-LLC/SARJ-LLC.yml
URLs weren't getting populated for SARJ-LLC.py
Also fits new structure instead of deprecated one: https://github.com/stashapp/stash/blob/413311711fba25a67e6aa2f9eeeefef97e641567/pkg/scraper/gallery.go#L10
> URLs weren't getting populated for SARJ-LLC.py

- scrapers/AniDB.yml
Currently the scene scraper scrapes for performer names. This change also scrapes the performer urls, which makes it easier to use the performer scraper on the performer's page.
Example:
| Series | Series URL | Performers | Performer URLs |
| - | - | - | - | 
| Pocket Monsters | https://anidb.net/anime/230 | Pikachu (Satoshi), ... | https://anidb.net/character/8091, ... |
> Update AniDB.yml: scrape performer URL when scrapping scene URL

- scrapers/IWantClips.yml
Today IWC image scraper gets the image from a "poster" placeholder in the page. However, this placeholder can contain still images (jpg, png, ...), .gif, or .mp4 files resulting in the following behavior :
* still images => scraping OK
* gif => scrape an animated image that is against the guidelines
* mp4 => error while scraping (image doesn't show)
This PR updates the "poster" url to grab the cover that is displayed in the search results which results in :
* still images  => no change, scraping OK
* gif => scrape a jpg being the cover of the scene => OK
* mp4 => scraped a jpg sometimes, or gets an error (similar to previous behavior)
In essence, this PR improves the image scraping by avoiding GIF retrieval and some MP4 errors.
> Improve IWC cover scraping

- SCRAPERS-LIST.md
- scrapers/Vip4K.yml
Updated Vip4K scraper to work with all subsites.
Some subsites like [Ignore 4K](https://ignore4k.com/en/videos/769), don't have tags and a release date. 
Some subsites like [Hunt 4K](https://hunt4k.com/en/videos/745), don't have performers and a release date.
We can bypass this to replace the query url to vip4k.com, which has performers, tags, releasedate.
> Added Vip4K Subsites and Fixed Vip4K Scraper

- SCRAPERS-LIST.md
- scrapers/MFC.yml
Gallery scraper is a copy paste of the already working scene scraper. MFC shares can contain both videos and photos, but regardless of content the underlying HTML is identical.
sample URL: `https://share.myfreecams.com/a/pwghp8y6`
Performer scraper works on `profiles.myfreecams.com` URLs. It's self explanatory for the most part.
Image: gets their "main photo" if one is set, otherwise falls back to their avatar. Gets the full size image where possible.
Height/weight: MFC allows models to input values in either imperial or metric. But as was the issue with the PornHex scraper I wrote, since we cannot perform math in YAML files and/or handle cases for both imperial and metric I have chosen to only get height/weight data if metric values are found. I (or someone else) could update this …
> Update MFC.yml to add gallery and performer scrapers

- SCRAPERS-LIST.md
- scrapers/Reddit.yml
A basic xpath scraper for reddit, use for scenes or galleries. Intended use would be on "gonewild" type subreddits so the poster's username is used as performer name.
Scraper gets data from the `<shreddit-post>` tag but if not found (meaning the URL is old.reddit) will look for the normal HTML tags. Same markup for image or video content so doesn't matter what you test it on.
old.reddit still uses an "over 18?" redirect for NSFW content, hence a cookie needing to be set.
Sample URL taken from /r/gonewild just now that you can test:
normal: `https://www.reddit.com/r/gonewild/comments/18gx66j/think_i_may_be_on_the_naughty_list_this_year_f/`
old site: `https://old.reddit.com/r/gonewild/comments/18gx66j/think_i_may_be_on_the_naughty_list_this_year_f/`
A long time ago someone requested a …
> Add scene and gallery xpath scraper for reddit

- scrapers/IWantClips.yml
IWC has changed their page structure in the last 24 hours breaking the tags scraping.
This fixes it.
> Fix tags due to recent page structure change

- scrapers/AniDB.yml
This pull request adds several new features to the AniDB scraper. 
The url scene scraper has been separated into two scrapers:
- One to scrape by anime URL ( e.g., https://anidb.net/anime/230)
- One to scrape by episode URL (e.g., https://anidb.net/episode/3262)
The previous implementation of the scraper used only the anime URL. However, as a series usually contains multiple episodes, this made scene titles ambiguous. The new episode scraper sets the title, the air date, and the anime URL.
Consequently, the anime URL scraper no longer sets the title. (This can be re-enabled, however, by un-commenting the corresponding line.)
The anime URL scraper should still be used to set the performers, tags, artwork, etc. 
This scraper now effectively uses the movie page to group all episodes in the …
> AniDB.yml: scrape by episode URL, add movie scraper, improve regex

- SCRAPERS-LIST.md
- scrapers/MindGeek.yml
The site biempire.xml is part of the Aylo / Mindgeek network, and is compatible with the scene and performer scrapers in MindGeek.yml.
> Add biempire.com to MindGeek.yml

- scrapers/PMVHaven/PMVHaven.py
- scrapers/PMVHaven/PMVHaven.yml
On newer videos, the current meta tag is not present. This checks for a backup tag
> PmvHaven secure url

- scrapers/FreeonesCommunity.yml
Height and Weight were pulling imperial measurements before but looks like FreeOnesCommunity is now using metric.  Updates scraper to match.
> Fixed Height and Weight data extraction

- scrapers/PaperStreetMedia.yml
I was getting a 400 error when saving anything with an images scrapped from PaperStreat.  Added header data to scraper.
> Resolved 400 error when saving images scraped from PaperStreat

- scrapers/Babepedia.yml
Currently grabs the state instead of the country if state and country is set.
Example:
For https://www.babepedia.com/babe/Nova_Sky it sets country to Ohio instead of USA.
This fixes it by selecting only the link with "topbabespercountry", which should be set for countries.
> Fix country in babepedia scraper

- scrapers/PMVHaven/PMVHaven.py
- scrapers/PMVHaven/PMVHaven.yml
The old method using cloudscraper was heavy handed IMO, I have made these changes:
- New method takes video ID directly from input URL because that is the only valid video site URL format. Removed unnecessary imports
- Code deduplication (fail method)
- More helpful error logging
- Changed script layout to allow for possible future scrapeBy options
- More helpful var names
- Reverse search thumbnails as I found a case where a blank thumb was returned as it was a incompatible type for the video site, and this change will ensure the most recent thumb is pulled into stash
- Updated yml file to specify sceneByURL
> Refactor PMVHaven scraper

- scrapers/AssumeThePositionStudios.py
- scrapers/AssumeThePositionStudios.yml
Assume The Position Studios (and a handful of other studios) use the same API.  This adds support for Worst Behavior Productions to the Assume The Position Studios scraper.
I also wanted a scrapeByFragment that can use the filename (which is basically studiocode_studio_bitrate) to find the correct url and scrape it.  This adds a python scraper to do the parsing and then it turns around and does a scrapeSceneURL to call the yml scraper.
> Add support for Worst Behavior Productions to Assume the Position scraper

- scrapers/MindGeek.yml
The original has a map when doing a scene scrape but doesn't do the same map when doing a movie scrape.  Movie scrap would be "sweetsinner" but scene scrape would be "Sweet Sinner".  Made that consistent.
> Fix MovieScraper studio for Sweet Sinner

- scrapers/MindGeek.yml
Added ability to scrape Movie via "Series" for this site.  This ppart didn't require a separate config for Scene scraping, but that'd be needed if we wanted to get this logic into scene scrapes due to the DOM differences "Movie Info" vs. "Series Info".  I didn't want to un-wire that much of this for an edge feature like Movies, though.
> Support Family Sinners series mapping with Movie URL scraper

- scrapers/DMM.yml
this is scraper designed to scraper metadata from DMM.co.jp in JAPANESE language with official release IMAGE
Please make sure scrape through a JAPAN based VPN, visit from IP outside of JAPAN may being blocked by this website.
Here is my thoughts regarding metadata language: 
since quality of all translated text from JAV japanese title or description may vary due to the tool or person, and AI driven tool are more intelligent, to keep soruce language text maybe is a better choice, so you can translate to any language properly at any time moving forward.
> Add DMM.co.jp scraper

- scrapers/Minnano-AV/Minnano-AV.py
- scrapers/Minnano-AV/Minnano-AV.yml
Fix for https://www.minnano-av.com/actress967297.html returning "3" as career start because of this block of text:
```
顔出し！女子大生限定 マジックミラー号 寝取り！嫉妬！羞恥からの興奮と快感！！ Wデート中の大学生カップル◆初めての同室スワッピング！！3 in池袋（2015年06月 06日）
```
I've just set the the regex to look for exactly 4 digits. If we find an occurence of double-digit years let's revise it further.
> Minanno-AV: Account for edge case in determining career start

- scrapers/HelixStudios.yml
This applies a couple of fixes to the Helix scraper needed due to recent site changes:
* The HTML title for scene pages is now what a regular person looking at the scene page would call the scene subtitle. This changes the scraper to pull the title that appears in the largest font on the scene page, which has historically been the scene title (which, prior to this site change, matched the HTML title).
* Helix added performer links to the scene description a while back, and the XPath query didn't account for them, omitting the text and adding spurious line breaks. This changes the scraper to use the entire contents of all non-empty `<p>` blocks.
> Title and description fixes for Helix

- scrapers/MindGeek.yml
When doing a scene scrape by URL, Movie wouldn't populate properly if the site releases as Series instead of as Movies.  Family Sinners is an example of Series, vs. Sweet Sinner being an example of Movies.  The result is that Series-based sites now get the Movie as the Series Name, instead of just copying the Scene Name to the Movie Name.
> Fix for MindGeek to scrape movie from sites that use "Series Info"

- SCRAPERS-LIST.md
- scrapers/KBProductions/KBProductions.py
- scrapers/KBProductions/KBProductions.yml
LucidFlix is a new site under the KB Productions umbrella.  It has some unique characteristics, but with some small modifications the existing KBProductions scraper works just fine with it.
Modified SCRAPERS-LIST.md for the new URL
Modified KBProductions.yml file to add LucidFlix URLs for scenes and models
Modified KBProductions.py to account for unique characteristics of LucidFlix
> Update KBProductions scraper to include LucidFlix

- scrapers/CopyToGallery/CopyToGallery.py
As described in Issue #1632 plugin CopyToGallery as unexpected behavior when scenes do not have galleries linked
> Issue #1632 - Plugin CopyToGallery

- scrapers/ManyVids/ManyVids.py
Manyvids API made some changes to how tags are represented. This fixes it.
> Fix Manyvids renamed "tags" key 

- scrapers/YesGirlz.yml
Yes Girlz revamped their website, as result the scraper no longer works.
They recycled most of the dates of the older scenes.
Now also grabs tags.
> Updated YesGirlz scraper

- scrapers/WikiData.yml
- scrapers/wikidata.yml
wikidata is the database behind wikipedia and can be used to power info boxes on wikipedia pages. Fixes #103
This database can have a lot of useful info such as height, weight, country, twitter handles etc.
Currently this is a WIP.
I might rewrite the processing performer with a python script as entries are easier to process.
> Adding initial support for a wikidata based scraper.

- scrapers/WhisparrWDTV.py
- scrapers/WhisparrWDTV.yml
To aid integration of Whisparr and Stash
Setup Whisparr to create the WDTV.xml files along side your video files (same name but .xml)
Make sure you copy the py_common directory along with the `WhisparrWDTV.py` `WhisparrWDTV.yml` into your `stash/config/scrapers` directory
Thanks to the code from the [kodi .nfo pr](https://github.com/stashapp/CommunityScrapers/pull/689) I borrowed heavily from this.
No image handling. 
This is not intended for generic WDTV xml handling, but specifically the format that came out of Whisparr.
> Scraper for WDTV xml files generated by Whisparr

- scrapers/MissaX/MissaX.py
Per discussion on Discord, fixed the logging for `Performers` and `Tags` to be compatible with the version of Python in the Docker image.  Also added a fix to prune `www.` from the URL before setting `Studio`.
> Logging fix and fix for www-prefix URL's

- scrapers/Wtfpass.yml
Currently there is no scraping of the studio codes of the WTFPass sites. The adjusted scraper will include the numerical code from their sites. The studo-related code is not present for every scene
> add scrape of numerical studio codes from Wtfpass sites

- scrapers/Timestamp.trade.yml
This is a scraper for my site timestamp.trade.
It should work for scenes urls as https://timestamp.trade/scene/f24937cb-c942-4f8c-a7cf-f628107ee097
It should also work for galleries on the scene url https://timestamp.trade/scene/f24937cb-c942-4f8c-a7cf-f628107ee097 or the gallery url such as https://timestamp.trade/gallery/aad4b3e3-23e2-4a8c-9758-297088434db8
There is also a zip hash lookup.
Use the timestamp.trade plugin to contribute to the database.
> Adding a scraper for my site timestamp.trade

- scrapers/Arx/Arx.py
- scrapers/Arx/Arx.yml
- scrapers/py_common/graphql.py
The GraphQL API has changed slightly in one of the query field names, and the response structure is one level less for errors.
This fixes those issues by using the changed field name `legacyScene` instead of `scene`, and using the first level `errors` instead of second level.
A general GraphQL introspection query variable `GRAPHQL_INTROSPECTION` is added that can be used again in future to discover API fields, queries, etc. This was used temporarily this time to find the changed field name.
Studio code scraping is now added, using the scene's `id` field.
> fix: adjust Arx scraper to updated graphql API

- scrapers/GEVI/GEVI.py
Seems like the label on GEVI got changed to upper case for "Dick Size", which prevents the scraper from parsing correctly.
> fix: fixes GEVI penis_length data scraping

- SCRAPERS-LIST.md
- scrapers/EmoNetwork.yml
New scene scraper for EmoNetwork (emonetwork.com) and their sub-studios.
While the sub studios each have their own URLs it seems that the scene data is only available from the emonetwork.com site.  Their sub-studio URLs all lead to a "join" page when clicking on a scene.
> Add scene scraper for EmoNetwork (emonetwork.com)

- scrapers/CarnalPlus.yml
Added channel https://cumdumpsluts.com/ from https://barebackplus.com/ to the main network scrapper Carnal+.
> Add studio Cum Dump Sluts to Carnal+ Network scrapper

- SCRAPERS-LIST.md
Changed scraper names for Algolia_* scrapers to their new name, after verifying that the sites are listed in the appropriate YML files.
One entry (nextdoorebony) deleted as that URL now redirects to parent studio site.
> Clean SCRAPERS-LIST.md, renaming Algolia_* files to their new names

- scrapers/SpankBang.yml
Added a User-Agent header, as SpankBang appears to require such, otherwise the scraper will fail with a 403-Forbidden response.
> Spank bang add user agent

- SCRAPERS-LIST.md
- scrapers/DEMedia.yml
New YML scene scraper for DE Media sites blackpayback.com and radicaljizzlam.com.
These sites are owned by the same company that operates the AdultDoorway network, but these two sites use a very different layout.  Instead of complicating the AdultDoorway scraper I've elected to give them their own.
> Add scraper for DE Media sites

- SCRAPERS-LIST.md
- scrapers/PaperStreetMedia.yml
SayUncle is essentially the gay version of the TeamSkeet network, and while the SayUncle sites are marked as owned by "Charged Media" instead of "Paper Street Media" the layouts are 100% compatible.  And while it's almost always better to find the site on SayUncle and scrape from there there may be some value in having individual URL scrapers for the sites that they provide (much like we have the TeamSkeet parent scraper, and this one for all the sub sites).
This update adds the following sites to the scraper:
blackgodz.com
bottomgames.com
boysatcamp.com
boysdoporn.com
brothercrush.com
bullyhim.com
dadcreep.com
doctortapes.com
latinleche.com
militarydick.com
missionaryboys.com
stayhomebro.com
therapydick.com
twinktrade.com
varsitygrip.com
yesfather.com
youngperps.com
> Add say uncle studio sites to paper street media scraper

- scrapers/PornDudeCasting.yml
- support `/models/` path, since /casting/CODE redirects
- fix:
- Performer name
- Tags
Fixed date parsing to use `article:published_time` which does match with all other metdata, rather than the rounded `Cast: MONTH YYYY`
- Requests 4K preview images from the server, 8K 404s but 1080p is still available
> update PornDudeCasting to pull new and moved values

- scrapers/Hitzefrei.yml
The studio has several sub-studios / series for their content, each with a subdomain URL from hitzefrei.com, and one of which at this time is present in StashDB as a sub-studio of Hitzefrei.  This change adds a studio map to the scraper which will provide the series name as the studio when scraping from the series' URLs.  The content is also available from the hitzefrei.com URL and use the 'tour' subdomain, but unfortunately there is at present no indication of the series when viewed this way.  Thus scenes scraped directly from hitzefrei.com will be given the Hitzefrei studio.
Studio map:
citycheck: City Check
cuffemall: Cuff 'em All
familyaffairs: Family Affairs
fanalarm: Fanalarm
fuckonarrival: Fuck On Arrival
milfhunters: Milf Hunters
pattisanals: Milf Hunters
tour: Hitzefrei …
> Add studio map for Hitzefrei.yml

- SCRAPERS-LIST.md
- scrapers/CJXXX.yml
New URL YML scene scraper for sites in the CJXXX network.
Added URLs to scrapers list for sites in the CJXXX network, using the CJXXX.yml scraper.  This is too many URLs to insert manually, so a sort of the URL list was performed.  Some reordering of existing URLs will be present in this checkin.
URLs added:
80gays.com
asiaboy.net
asiantwinknetwork.com
auntiebob.com
barebackeu.com
barebacklatinoz.com
barebackmedaddy.com
barebacktwinkz.com
brazilianstudz.com
daddysasians.com
defiantboyz.com
doctortwink.com
cjxxx.com
gayamateurpass.com
gayasiancamz.com
gayasianpiss.com
gayasiantwinkz.com
gaybarebackpass.com
gaylatinpass.com
gaytwinkcamz.com
germancumpigz.com
gloryholehookups.com
hammerboysxxx.com
hotboyusa.com
iomacho.com
laughingasians.com
otbboyz.com
pragueboyz.com
ramjetvideo.com …
> Add cjxxx network scraper

- scrapers/RandyBlue.yml
Scraper adds url field to "/", fixed that by getting url from different field.
> Fix blank url at RandyBlue.yml

- scrapers/XConfessions.yml
The previous scraper had issues with some scenes, where it would suggest an image that's not related to the scene being scraped.  This change modifies the image selector to attempt several methods to find a suitable picture:
- First, look in the script for a cover_title_picture value.   
- If that's not present, look for two consecutive images with UIDs in the URL.  The first is the movie poster, the second is the scene image. 
- If that's not present, look for a time stamp followed closely by two images.  Again the first is the movie version, the second is the image. 
- If we still don't have a match, look for a confession_cover_image value.  These are pretty good, but won't have the scene name. 
- Finally, if nothing matches, try the last image in the script.  It's often the right one. …
> Update x confessions image selectors

- SCRAPERS-LIST.md
- scrapers/superbemodels.yml
Rewrite of the SuperbeModels scraper for the latest layout of the site.
Scene scraper attempts to populate as much Performer information as possible by use of subScrapers.
Added performer and gallery URL scrapers.
Note:  While this site shares much of the formatting used by LetsDoeIt sites, the performer section has quite different information.  With the number of subScrape required to handle both formats, and for the sake of fastest scraping, keeping this site scraper separate from LetsDoeIt sites seems appropriate at this time.
> Update superbe models

- SCRAPERS-LIST.md
- scrapers/AVMoo.xml
For avmoo.online as mentioned in [Issue 73](https://github.com/stashapp/CommunityScrapers/issues/73).  Included avsox.click, as that site uses the same layout.
New URL scene scraper for avmoo.online and avsox.click.
New URL movie and performer scrapers for avmoo.online.
avsox.click shares the same format as avmoo.online, except it doesn't appear to have longer length clips that would justify creating movies, nor does it appear that performer details are available at avsox.click (at least for those sampled when writing this scraper).
Anyone with more familiarity with the studios present on these sites are welcome to create studio maps for those with Japanese names, if such is desired.
Tested with the English versions of the URLs.
> Add scrapers for AVMoo and AVSox

- SCRAPERS-LIST.md
- scrapers/TwistedFactory.yml
For twistedfactory.com, as requested in [Issue 73](https://github.com/stashapp/CommunityScrapers/issues/73).
New scraper for TwistedFactory, based on a combination of the Kink.yml and KinkMen.yml scrapers, with extensive additions to the performer scraper.
Added entry for twistedfactory.com, using TwistedFactory.yml.
This is a site under the Kink.com umbrella, and shares the same layout as kink.com and kinkmen.com.  This scraper was built first using kink.yml as the base, but pulling in the simpler performer and studio selectors from kinkmen.yml.  There is likely an opportunity to merge all three scrapers into one large scraper for the entire family of sites.  While that may be possible, for the benefit of those waiting on a scraper for this site, it was decided to build a dedicated one. …
> New scraper for twisted factory

- SCRAPERS-LIST.md
- scrapers/JavDatabase.yml
For one of the sites mentioned in [Issue 73](https://github.com/stashapp/CommunityScrapers/issues/73)
New YML URL scene, performer and movie scraper for JavDatabase (javdatabase.com).
Updated scrapers list for javdatabase.com, using JavDatabase.yml.
> Add scraper for JavDatabase (javdatabase.com)

- scrapers/Kink.yml
- scrapers/KinkMen.yml
Kink, KinkMen and TwistedFactory are all networks under the same umbrella and use the same format for performers.  When the scraper for TwistedFactory was written, new selectors were used to gather more information on performers.  
This change updates the performer scrapers for Kink.com and KinkMen.com to use the new performer scrapers developed for the TwistedFactory scraper.
> Update performer scrapers for kink.yml and kink men.yml

- SCRAPERS-LIST.md
- scrapers/KBProductions/KBProductions.py
- scrapers/KBProductions/KBProductions.yml
For nyseedxxx.com (NYSeed), as mentioned in [Issue 73](https://github.com/stashapp/CommunityScrapers/issues/73).
NYSeed is a KBProductions site, but uses a different format than those already handled by the scraper.  
Added a new JSON processing routine for the "video" element that's in use by this studio where previous studios used "content".  As this is the first site known to use this format this routine may be under a great deal of flux as additional sites are found that use the "video" element instead of "content".
Renamed existing JSON processing routine to reflect that it's fed from the "content" element.
Added nyseedxxx.com to screne URLs in YML.
Added api.nyseedxxx.com to Python studio map.
Added nyseedxxx.com to Scrapers List, referencing KBProductions.yml.
> Add NYSeed to KBProductions scraper

- scrapers/Kink.yml
Just noticed an error in the stash logs after scraping a kink [scene](https://www.kink.com/shoot/106108):
`Warning Error compiling regex '?.*$': error parsing regexp: missing argument to repetition operator: ?`
Which leads to not stripping the text after the ? in the image url, thus downsizing the scene image:
`[0][Image] = https://imgopt02.kink.com/imagedb/106087/indexImage/106087_indeximage_003_full.png?w=1200&s=b3086e3563ff916b0d6224e3ed65477f043f9ad148d34ead068f1eaf0941a31e`
Small fix so it strips out the part after ?:
`[0][Image] = https://imgopt02.kink.com/imagedb/106087/indexImage/106087_indeximage_003_full.png`
> Fix for kink.yml scene image scraping

- scrapers/Algolia/Algolia.py
Fix for the problem mentioned in [Issue 1701](https://github.com/stashapp/CommunityScrapers/issues/1701)
Added "Evil Angel" to SITES_USING_SITENAME_AS_STUDIO_FOR_SCENE list, so that the studio name is scraped instead of the "serie_name" value.
> Grab correct "studio" value for Evil Angel scenes scraped by Algolia scraper.

- scrapers/Adultime/Adultime.yml
- scrapers/Vivid.yml
The Vivid network is now under the Adultime family, and the vivid.com scenes scrapable by the Adultime scraper.  This change moves the vivid.com URL Scene Scraper from the Vivid.yml scraper and adds it to Adultime.yml.
While all the remaining URLs in the Vivid.yml scraper now redirect to vivid.com, links to individual scenes (as found on StashDB) are still serving data and are scrapable by Vivid.yml.  As such Vivid.yml will remain behind with those URLs until scraping breaks.
> Move vivid.com to Adultime scraper

- scrapers/Algolia/Algolia.py
- scrapers/Biphoria/Biphoria.yml
This change allows for scraping of movies from the Biphoria studio:
- URL movie scraping from the "movies" page
- Creating / linking movie during a scene URL scrape when the scene is determined as belonging to a movie.
> Add movie scraping support for Biphoria (biphoria.com)

- scrapers/YT-dlp/YT-dlp.py
- scrapers/YT-dlp/YT-dlp.yml
To address [Issue 1685](https://github.com/stashapp/CommunityScrapers/issues/1685).
[yt-dlp](https://github.com/yt-dlp/yt-dlp) is a maintained fork of abandoned project [youtube-dl](https://github.com/ytdl-org/youtube-dl). It supports downloads from the [most popular porn sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md), including pornhub, xhamster, xnxx, xvideos, and many more. If you pass the --write-info-json option when downloading, it will scrape the download site and save all of the metadata in a JSON file.
This Python scraper will look for a file with the same name as the media file being scraped, but with a .json extension.  This .json file must reside in the same directory as the media file, or in an alternate directory indicated in the script.  Use of the …
> Add scraper for JSON files created by yt-dlp

- SCRAPERS-LIST.md
- scrapers/LetsDoeIt.yml
Added support for gallery and performer URL scraping for sites in the LetsDoeIt network scraper.
Removed URLs for sites that no longer host their own content.
Updated scrapers list to indicate that the scraper supports gallery and performer scraping.
> Add performer and gallery scrapers to LetsDoeIt network scraper

- scrapers/MyNakedDolls.yml
Unfortunately I had to skip scraping performer URLs and item dates.
Performer URLs are only provided for single performer galleries/scenes, also the link is hidden and not clickable on the website, doesn't seem reliable at all.
Dates are only provided on the performer's portfolio and are nowhere to be found on the detail-view of the gallery/scene.
I might try to implement a subScraper to get to the dates with a second request in the future.
> Adds gallery and scene parsing for MyNakedDolls (mndmag.com, mynakeddolls.com)

- SCRAPERS-LIST.md
- scrapers/KBProductions/KBProductions.py
- scrapers/KBProductions/KBProductions.yml
Added new sites to studio and performer scrapers and scrapers list:
jizzaddiction.com
joeschmoevideos.com
machofactory.com
Removed "scrapes these sites" comment from YML file, as it is becoming cumbersome and provided little utility that can't be gleaned from the URL lists.
Updated performer scraper to account for sites that provide the performer JSON with lowercase key names.  Added more performer values to performer scrapes, including male-specific items.
Added some utility routines to convert imperial measures to metric.
> New sites and performer scrapers for KBProductions

- SCRAPERS-LIST.md
- scrapers/Andomark.yml
The sites in the Domingo network are compatible with the Andomark URL scene scraper.  The following sites have been added to the Andomark scraper, and entries in the scrapers list created:
- charmmodels.net
- domingoview.com
- feelmevr.com
- letstryhard.com
- test-shoots.com
> Add Domingo Network sites to Andomark scraper

- SCRAPERS-LIST.md
- scrapers/Andomark.yml
Added sites from the Trix family of sites, as well as a couple others that use the template, to the Andomark URL scene scraper.  
Added to selector for studio to accommodate new site.
Reaphabetized the scene URL list in Andomark.yml.
Updated scrapers list.
Sites added:
boxofporn.info
dallasdiamondz.com
dixiestrailerpark.com
grannycumshere.com
msparisandfriends.com
suburbantaboo.com
swingingbicouples
tampahousewives.com
whorebaithals.com
> Add Trix Video sites (and a couple of others) to Andomark scraper

- scrapers/Pornhub.yml
The pornstar anchors no longer seem to have a `data-mxptext` attribute. Replace this with the `text()` value(s) of anchors which have the `data-label="pornstar"` attribute and value.
> Replace data-mxptext in Pornhub.yml

- scrapers/LadyboyGold.yml
This fixes the tsraw.com scene image scraping, to both handle the additional single quotes around the URI path, and to use the corresponding hostname.
This also adds Studio Code scraping in scenes.
Example scene URLs:
- https://www.tsraw.com/show_video.php?galid=24043&section=1609&nats=MC4wLjIzLjExOS4wLjAuMC4wLjA
- https://ladyboygold.com/tour/show_video.php?galid=22318&section=1552&nats=MC4wLjYuNi4wLjAuMC4wLjA
- https://ladyboygold.com/tour/show_video.php?galid=20981&section=1552&nats=MC4wLjYuNi4wLjAuMC4wLjA
> fix TSRaw.com image scraping

- scrapers/Algolia/Algolia.py
Some tags are now only in content_tags (gay, trans, etc) but only in some sites. 
This adds those tags to tags.
> Add content_tags to Algolia

- SCRAPERS-LIST.md
- scrapers/PPVNetwork.yml
New URL scene scraper for sites using the "PPVNetwork 2.0" template:
- bearboxxx.com
- butchbear.tv
- darkalleyxt.com
- rawandrough.com
- rawnastyfuckers.com
- rawtop.tv
- treasureislandmedia.tv
Added sites to scrapers list using PPVNetwork.yml.
Scraper requires CDP and a simple cookie to pass consent verification.  All sites host exclusively gay content.
> Add URL scene scraper for sites in PPVNetwork

- scrapers/vixenNetwork/vixenNetwork.py
Added in mechanism where default tags for specific sites will be added to scene scrapes:
- Tushy, TushyRaw: Anal Sex
- Blacked, BlackedRaw: Black Male
- Slayed: Lesbian Sex
- Milfy: MILF
These are implemented as lists to make it easier to adapt should a future site have multiple tags that would be appropriate as defaults.
The inclusion of the default tags can be disabled by use of the USE_STUDIO_DEFAULT_TAGS variable set at the top of the script where other configuration values are set.
> Add default studio tags for Vixen Network sites.

- scrapers/SARJ-LLC/SARJ-LLC.py
For issue [1844](https://github.com/stashapp/CommunityScrapers/issues/1844)
Fixed typo that caused SexArt scenes to scrape the "still photographer" as and additional director.  
Created a list for sites like SexArt that don't use the "crew" values for directors to make it more obvious and more easily extendable should future sites behave in the same manner.
> Fix director field for SexArt scenes when scraped

- SCRAPERS-LIST.md
- scrapers/BoyFun.yml
Updated BoyFun.yml:
- Added cookies necessary to allow scraping.
- Added jawked.com as supported site.
- Modified for latest layout, and to allow for small differences that jawked uses.
- Added performer URL scraper.
Updated Scrapers-list.md:
- Added performer check for boyfun.com.
- Added jawked.com, using BoyFun.com.
> Update boy fun.yml

- SCRAPERS-LIST.md
- scrapers/Czechav.yml
Additional sites from this network added to scraper:
- czechcabins.com
- czechexperiment.com
- czechpawnshop.com
- czechpool.com
- czechsauna.com
- czechsnooper.com
Updated scrapers list for the above sites.
Made an obvious change to the scrapers list entry for chzechshemale.com
> New sites for Czechav.yml scraper

- SCRAPERS-LIST.md
- scrapers/TeenDreams.yml
Added sister site 'teen-depot' to URL scrapers.
Updated title, studio and image selectors to match current site layout, compatible with both sites.
Updated details section to ignore poorly coded pages that would throw a "Deprecated" error.
Added teen-depot to scrapers list, using TeenDreams.yml.
> Update TeenDreams.yml for new site and latest layout

- scrapers/PaperStreetMedia.yml
- scrapers/Teamskeet/TeamskeetAPI.py
Modified scraped studio values for several studios under TeamSkeet / MYLF / SayUncle (served by TeamskeetAPI and PaperStreetMedia) to match the values used in StashDB.
> Modify studio mapping for TeamskeetAPI and PaperStreetMedia to match StashDB

- scrapers/Mofos/Mofos.yml
Replace `publicagent.com` with `publicpickups.com` in `Mofos.yml`. Public Agent is a FakeHub studio and is already in `FakeHub.yml`. Public Pickups is a Mofos studio.
Replace `Pubic Pickups` with `Public Pickups` in `Mofos.yml`. Public Pickups is a Mofos studio. **Pubic** Pickups is *probably* not a studio.
> Fix `publicagent.com` --> `publicpickups.com` for Mofos scraper

- scrapers/AyloAPI/scrape.py
I noticed the AyloAPI scraper is not returning scene details in some cases (url scraping).
For example,  this [scene](https://www.brazzers.com/video/9408131/brazzers-house-4-episode-7) returns empty details, although the details exist in the json response, but under the ``parent`` key.
Added in a check, that if the default details is empty, lookup the details under the ``parent`` key.
Second, added html.**unescape** to convert all named and numeric character references (e.g. ``&gt;``, ``&amp;``) in the string to the corresponding Unicode characters, for example, this [scene](https://www.brazzers.com/video/3972491/a-wild-ride-before-the-wedding)
The **html** is already part of Standard Library that comes with Python 3.x, so it shouldn't cause any problems.
Third, added a small tweak, to …
> Fix for AyloAPI not returning scene details in some cases

- scrapers/GirlsOutWest.yml
Girls Out West has changed their layout, meaning a rewrite of the scraper is needed.
Scene and Performer URL scrapers have been modified to scrape the new layout.
It appears that their galleries are now behind a paywall, so it is not possible to scrape those.  I'd be happy to be proven wrong and return gallery scraping if a public URL can be provided.
> Update GirlsOutWest.yml for latest site layout

- scrapers/RawFuckClub.yml
The Raw Fuck Club scraper wasn't functioning well with the changes to the site, especially the parts enabling independent creators to create channels.  Based on the direction from stash on having parent studios (and based on how the site is laid out), this scraper is now far more functional.
Changes:
- Added performerByName, sceneByFragment
- Corrected performers linkage
- Corrected issue where title was picking up "screenshots"
- Corrected legacy image location to modern site design
- Performer scrape now works
- Corrected new consent screen
- Sub-studies now function correctly (channels on RFC = sub-studios)
Note: There doesn't appear to be a way to get the parent studio linked on creation. 
Open to suggestions or anything to make this better.  Please note the long xPaths appear to be …
> Update RawFuckClub For Channels and Added performerByName, sceneByFragment

- scrapers/bibian-av.yml
Is Stash 0.26 this doesn't work anymore. Apparently, JavaScript engine is more strict in this version.
> bibian-av.yml: Fix javascript variable declaration

- scrapers/Teamskeet/TeamskeetAPI.py
MYLF.com has changed their high resolution scene image URLs.  Image mapping routine added to get the best possible scene image resolution for TeamSkeet, SayUncle and MYLF URLs.
- SayUncle - use the default image from the scrape (it's high res to begin with) 
- TeamSkeet - use the original mapping that was in the previous version of the scraper 
- MYLF - Use new "bio_big" mapping that is new and unique to MYLF.
> Fix image mapping for MYLF.com, add discrete image URL mapping for all TeamskeetAPI studios.

- README.md
supercedes #1114 
This has the advantage of not needing a container built and it removes itself afterwards
Explanation:  
`-v` mounts the current directory (CommunityScrapers) to the docker container at `/app`
`--rm` removes the container once it exits  
`/bin/sh -c` takes us out of node-cli into a shell  
`cd /app/validator` moves us to the validator directory to install the dependencies  
`yarn install --silent` installs the dependencies needed for the validator  
`cd ..` takes us back out of the validator directory into `/app`
`node validate.js --ci` runs the validator
> add docker validator

- SCRAPERS-LIST.md
- scrapers/Spizoo.yml
Adds support for `mrluckylife.com` to the Spizoo scraper. Adds an additional case for capturing scene titles in order to avoid scraping title as `MORE MR.LUCKY LIFE VIDEOS` for all scenes. Verified that titles still are scraped correctly for other Spizoo sites that I can test.
> Add support for mrluckylife.com and parsing its titles

- scrapers/IFeelMyself/IFeelMyself.py
Added an if statement to check for the video tag instead of img. And fall back to img for older actors. IFM is now using JS for img tags which is the cause of the error
> Fix for actor scraper on IFM scraper

- SCRAPERS-LIST.md
- scrapers/VirtualRealPorn.yml
Site layout has been updated on all network sites:
- virtualrealamateurporn.com
- virtualrealgay.com
- virtualrealjapan.com
- virtualrealpassion.com
- virtualrealporn.com
- virtualrealtrans.com
The existing `sceneScraper` has been adjusted to match.
- https://virtualrealamateurporn.com/vr-amateur-porn-video/hot-visit/
- https://virtualrealgay.com/vr-gay-porn-video/summer-ends/
- https://virtualrealjapan.com/vr-japanese-video/%e3%80%90part03%e3%80%91hq60fps-close-up-best-210min/
- https://virtualrealpassion.com/vr-female-pov-porn-video/polysex/
- https://virtualrealporn.com/vr-porn-video/massage-courses/
- https://virtualrealtrans.com/vr-trans-porn-video/garden-of-eden/
Added `performerByURL` scraper
- https://virtualrealgay.com/vr-models/andy-star/
- …
> fix/improve VirtualReal network scraper

- scrapers/GroobyNetwork-Partial.yml
This adjusts the `Details` selector Xpath to include nested `span` tags within the `p` in order to get the paragraphs following the first one.
- https://www.groobyvr.com/tour/trailers/I-Spent-My-Sugardaddys-Allowance.html
- https://www.groobyvr.com/tour/trailers/I-Just-Fucked-Fernanda-Moraes.html
- https://www.groobyvr.com/tour/trailers/I-Like-It-In-My-Butt.html
- https://www.groobyvr.com/tour/trailers/Reach-Out-And-Take-The-Cherry.html
> Fix GroobyVR scene description scraping

- scrapers/10Musume-JP.yml
- scrapers/AVE-JP.yml
- scrapers/Caribbeancom-JP.yml
- scrapers/H0930_C0930_H4610-JP.yml
- scrapers/Heydouga-JP.yml
- scrapers/Heyzo-JP.yml
- scrapers/Paco-JP.yml
- scrapers/S1.yml
- scrapers/arzon.jp.yml
- scrapers/duga.jp.yml
- scrapers/fc2.yml
- scrapers/jade-net-home.yml
- scrapers/unkotare.com.yml
All filenames of the scrape scripts containing '-JP' are associated with the Japanese version of metadata. Meanwhile, it's possible that these websites also offer an English version. The scrape scripts for the English version may or may not have already been created.
> Add several JAV scraper, all from official websites

- scrapers/PremiumBukkake/PremiumBukkake.py
- scrapers/PremiumBukkake/PremiumBukkake.yml
Premium Bukkake has 2 sites, free version - https://free.premiumbukkake.com/  and paywalled - https://premiumbukkake.com/tour2. The current scraper uses the free versions URL and extracts some details, then modifies the URL and scrapes image, tags and performer from the paywalled site. The image has not worked correctly for a while picking up the model image not the scene cover after changes to the site. More recent updates to the paywalled site have also caused the scraper not to work in some scenes as it no longer follows assumptions made in scraper, https://free.premiumbukkake.com/updates/Rocio-1-Bukkake.html is a good example, as she does not have a performers section in her scene, the scraper fails on performer and tags. So have refactored for reliability.
Changes
1. Get cover image …
> Improve Premium Bukkake

- scrapers/Watch4Beauty.yml
It appears that the site uses a new CDN for their poster images.  This change modifies the image selectors for the new CDN.
> Update Watch4Beauty.yml for new image CDN

- scrapers/Putalocura.yml
The details in the scenes on Putalocura usually include links to the performer and other scenes, so the current scraper using the text() function will stop parsing the contents of the details in the <p> tag when a link tag <a> is hit. Fix is to remove the text() specifier to allow the complete <p> tag to be automatically parsed. Issue can be seen with this link https://www.putalocura.com/en/spanish-glory-hole/his-first-glory-hole-la-sadica-vive
> Fix Putalocura Details

- scrapers/Oldje.yml
Oldje used to have 2 types of scene cover, the montage and the poster, the poster was large, portrait and made up of multiple pictures, whereas the montage is normal size and landscape all in one jpg. 99% of Oldje scenes on StashDB use the montage card format. Oldje have now dropped the poster and gone for a screen cap, but the montage is still used. This change will automatically pick up the montage in keeping with StashDB covers. Montage cover is same format with movie- removed from URL
Example
Screen cap : https://www.oldje.com/sets/898/movie-morning-exercise.jpg 
Montage : https://www.oldje.com/sets/898/morning-exercise.jpg
> Get correct Oldje scene cover

- scrapers/Oldje.yml
Studio codes for Oldje and Oldje-3some are contained in the image URLs, these have been extracted and set into format Ennn where nnn is studio code (e.g E872), it is prefixed with E as the studio download filenames follow this format and 99% of the StashDB studio codes are also in this format.
> Add studio code for Oldje and Oldje-3some

- scrapers/Oldje.yml
Looks like the website structure has changed at some point as scraping the title using first `<h1>` tag now just returns "Warning: explicit content for adults only", fixed to pickup on the breadcrumb_last class span which is always the title.
Can be tested with - https://www.oldje-3some.com/videos/set/a-workout-to-remember
> Fix Oldje-3Some title

- scrapers/GloryHoleSwallow.yml
Modify the Gloryhole Swallow scraper to add the sister site of Cumpsters.com. This uses same layout, so scraper modified to scrape both sites.
> Add Cumpsters.com scraper

- scrapers/GloryHoleSwallow.yml
Add support for the other 2 sister sites of Gloryhole Swallow, SpyTug and CumClinic. This scraper now supports all 4 Titan Media Inc sites. Also added modification to ensure images from older scenes were being picked up correctly.
> Add Spytug.com and CumClinic.com

- scrapers/Spizoo.yml
Mr. LuckyLIFE doesn't show tags when the user is logged out, but does show them to members. In the interest of scraping tags, this change:
* Adds a place to set a logged-in cookie.
* Modifies some selectors to handle the page structure of the Mr. LuckyLIFE members' site.
* Adds a mapping for studio name `mrluckylife: Mr. LuckyLIFE`. This is technically unrelated, but ought to be fixed.
* Has been tested to not break support for the logged-out case on Mr. LuckyLIFE and all other Spizoo network sites.
> Support scraping Mr. LuckyLIFE members' pages

- scrapers/hanime.yml
the current regex tries to match group 1 greedily which causes the resolution of the file to be appended to the url mistakenly.
`15-bishoujo-hyouryuuki-1-720p.mp4` -> https://hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1-720p
this patch makes the first group lazy to correctly build the desired url, which should work for the both files with or without the resolution.
`15-bishoujo-hyouryuuki-1.mp4` -> https://hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1
`15-bishoujo-hyouryuuki-1-720p.mp4` -> https://hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1
> Fix hanime scraping

- scrapers/Rule34Video.yml
Fixed an issue where the video description would miss line breaks and would read wrong elements when the description is empty.  Would've wanted to insert correct line break ammount for mirroring the correct formating off of the site (e.g. multiple line breaks directly after one-and-other), but my skills are too limited for that
> Rule34Video: Fix video description sometimes not getting read properly

- SCRAPERS-LIST.md
- scrapers/MindControlTheatre.yml
* Add URL and fragment scraper for MindControlTheatre.com
* Added new entry to SCRAPERS-LIST
* Test for in-line HTML handling:  https://mindcontroltheatre.com/movie/truhyp2
* Test for no director (default/fallback):  https://mindcontroltheatre.com/movie/r-word-mct
* Test for Henri (main director):  https://mindcontroltheatre.com/movie/friend-request
* Test for Electra (2nd director):  https://mindcontroltheatre.com/movie/laurel-before-3-mct
* Latest video:  https://mindcontroltheatre.com/movie/long-tail-mct
Added scraper for niche fetish video site for all things mind control (including hypnosis, drugging, devices, mental powers, the supernatural, etc).
The site is run by the primary writer & director themselves. As …
> Add scraper for MindControlTheatre.com

- scrapers/PureMedia.yml
[Scene URL](https://www.pure-bbw.com/tour/trailers/HOT-threesome-with-Samantha-38g-and-Karen-Fisher-tagteaming-a-lucky-cock.html)
[Scene URL](https://pure-ts.com/tour/trailers/post-cheating-threesome.html)
[Scene URL](https://www.pure-xxx.com/tour/trailers/bringing-her-trans-girlfriend-home-for-some-fun.html)
[Scene URL](https://sissypov.com/tour/trailers/crossdressing-girlfriends-get-down-on-a-big-dick.html)
Fixed scraping scenes with multiple performers. Previously it scraped both performers as one, eg ``performer1 performer2``
Simplified the regex for the image
> Fix scraping scenes with multiple performers Pure Media

- .vscode/settings.json
- scrapers/Spizoo.yml
Apparently I either didn't test RawAttack as closely as I'd thought before [this PR](https://github.com/stashapp/CommunityScrapers/pull/1954), or their page formatting is inconsistent, because the updated performer name selector does not always work on RawAttack pages.
This change re-adds the original `$scene_info//a[contains(@href,"/model")]/@title` selector for performer names as a secondary alternative / fallback to the  newer performer name selector.
> Fix RawAttack, and possibly other Spizoo sites, performer name scraping.

- scrapers/PremiumBukkake/PremiumBukkake.py
- scrapers/PremiumBukkake/PremiumBukkake.yml
[Scene URL](https://free.premiumbukkake.com/updates/Bambola-1-Bukkake.html)
- Added py_common.log to have more control over logging
- Added in checks in case scene is removed
- Added in checks in case slugs are different from the [free](https://free.premiumbukkake.com) compared to the [paywalled site](https://premiumbukkake.com/tour2)
- Scraping correct scene details with linebreaks
- Scraping performer image on performer create now works
- Scraping correct performer bio on performer create with linebreaks
- Using requests session for making multiple requests
- Now adds the scene url from the [paywalled](https://premiumbukkake.com/tour2) site, to the list of urls
- Removed additional text from performer measurements like ``(Cup C)``
Kudos to @jersprin for #1925
> Updated PremiumBukkake scraper

- scrapers/Algolia/Algolia.py
Added small fix to remove leading/trailing/double whitespaces in the scene description. 
Since StashDB already removes leading/trailing whitespaces, it's bugging the hell out of me why the description is different, only to find out later it was a trailing whitespace.
[scene url](https://tabooheat.com/en/video/tabooheat/Cory-Chase-in-Caught-During-the-Storm-with-Step-Mom/216240)
[scene url](https://tabooheat.com/en/video/tabooheat/Cory-Chase-in-BBC-Championship-Season---Gym-Motivation/227915)
[scene url](https://tabooheat.com/en/video/tabooheat/Ivy-Andrews-in-BBC-Championship-Season---Horny-Step-Daughter-Part-2/251761)
> Fix for Algolia scraper scene details

- scrapers/Pornhub.yml
Pornhub changed their top level domain to `.org` - `.com` still works too.
> Add '.org' TLD support to Pornhub

- scrapers/data18.yml
I did not make changes to what can be scrapped.  I only updated RegEx to remove the "#" inserted in movie titles that aren't typically included in other sites.
Example: My Neighbor Is A Sexy MILF 6
URL: https://www.lethalhardcore.com/en/movie/title/120401
Scene from data18 would extract movie title "My Neighbor is a Sexy Milf #6" 
URL: https://www.data18.com/scenes/3124736
Alternate source AdultEmpire Example URL: https://www.adultempire.com/4676320/my-neighbor-is-a-sexy-milf-6-porn-videos.html
> Data18 movie name tweak

- scrapers/Private.yml
[scene url](https://www.private.com/scene/marie-berger-and-catherine-knight-get-horny-in-an-anal-threesome/26724)
When scraping scene urls, scraper returns date as ``2023-12-29T00:00:00+01:00``
Small fix so it returns ``2023-12-29``
> Fix Private date parsing

- scrapers/KBProductions/KBProductions.py
- scrapers/KBProductions/KBProductions.yml
https://dickhddaily.com/videos/nerdy-booty
https://dickhddaily.com/videos/baddie-taming-extended
https://dickhddaily.com/videos/big-ass-to-take-extended
Added dickhddaily.com (DickHDDaily) to KBProductions URL scene scraper and studio map.
> Add DickHDDaily to KBProductions URL scene scraper

- scrapers/MissAV_en.yml
Website replaced `span` field with `time` which broke release date scrape
> Fixing MissAV_en time fetch

- scrapers/Arx/Arx.py
- scrapers/Arx/Arx.yml
- sceneByURL
- https://transmidnight.com/scenes/3313/skinny-trans-dolly-rotten-enjoys-deep-raw-anal-and-big-facial
- https://transdaylight.com/scenes/3316/blonde-trans-olivia-would-fucks-thicc-rubie-hellia
Adds `sceneByURL` scraping for the following sites:
- transmidnight.com
- transdaylight.com
> add working sceneByURL for transdaylight.com and transmidnight.com

- scrapers/BaDoink.yml
NSFW
https://18vr.com/vrpornvideo/feed_the_need-325692/
https://babevr.com/vrpornvideo/sybil_101-325713/
https://badoinkvr.com/vrpornvideo/a_little_miss_conduct-326572/
https://vrcosplayx.com/cosplaypornvideo/euphoria_maddy_a_xxx_parody-326303/
Fixed the image xpath for the badoink scraper
> Fix cover image xpath in badoink scaper

- scrapers/AlexLegend/AlexLegend.yml
- scrapers/VNAGirls.yml
Adds a sceneByURL xPathScraper for AlexLegend.com
[Recent Scene](https://alexlegend.com/video/skylar-snow-black-lingerie-surprise-sex-behind-the-scenes-1074.html)
[Popular Scene](https://alexlegend.com/video/bg-caitlin-bell-xmas-roommates-740.html)
[Old Scene](https://alexlegend.com/video/alex-grey-first-ir-dp-gangbang-288.html)
Break out alexlegend.com from VNAGirls scraper. New site design that does not conform to VNA template.
> Add AlexLegend Scraper

- scrapers/Boundhoneys.yml
- scrapers/Dickdrainers.yml
- scrapers/FreeonesCommunity.yml
- scrapers/Mandyflores.yml
- scrapers/Pornhub.yml
changes from https://github.com/stashapp/CommunityScrapers/pull/2014
- `[normalize-space(.)]` transforms the text, in some cases transforming it from the studio name
- FreeOnesCommunity updated with new selector
- PornHub now with video-actions-tab common, split up for readability
> removed text normalize-space, add PornHub videoActions common

- scrapers/PervCity.yml
[Scene url](https://upherasshole.com/trailers/alt-babes-bonnie-rotten-juelz-ventura-get-nasty.html) (Up Her Asshole)
[Scene url](https://analoverdose.com/trailers/taboo-anal-sex-three-way-part-2.html) (Anal Overdose)
[Scene url](https://www.dpdiva.com/trailers/Stunning-Latina-Vanessa-Sky-Intense-DP.html) (DP Diva)
- Tags for scenes
Tags can only be grabbed on the pervcity.com website, not on the individual subsites.
The slug is the same for a scene, so I used queryURLReplace to replace domain to pervcity.com to grab the tags.
- Updated regex for dates 
Dates for scenes are only displayed on the pervcity.com website, when searching for a scene.
So searching for exact title that has a ``’`` or ``,`` would return more than 1 scene, and most of the time the wrong one.
- Map the studio to …
> Update PervCity scraper

- scrapers/SARJ-LLC-JSON.yml
- scrapers/metart.yml
Supercedes https://github.com/stashapp/CommunityScrapers/pull/1878
naming to remain consistent with existing script scraper
> Add SARJ-LLC JSON scraper

- scrapers/MilkyCat/MilkyCat.yml
- scrapers/MilkyCat/scraper.py
* FB-17
* https://www.milky-cat.com/movie/indexe.php?fb17
* https://www.milky-cat.com/movie/indexe.php?dmc01
Basic scraper to the Milky Cat website which provides some informations about releases, namely title, image and details.
This script uses `beautifulsoup4` and `requests` but I'm not sure if is a problem ?
> feat: Milky Cat scraper

- scrapers/Teamskeet/TeamskeetAPI.py
| path | note | resolution | test URLs |
|---|---|---|---|
| members/full | TeamSkeet | 1600x900 | [1](https://www.teamskeet.com/movies/breed-me-daddy) |
| bio_big | MYLF | 1500x844 | [2](https://www.mylf.com/movies/i-cant-resist-my-stepmom-needs-a-young-mans-seed) [7](https://www.mylf.com/movies/dirty-principal-lets-me-free-use-her-to-avoid-suspension) |
| shared/hi |  | 1280x720 | [4](https://www.mylf.com/movies/my-anal-lover) [6](https://www.teamskeet.com/movies/for-the-good-of-the-team) |
| tour/pics/shared/hi | MYLF | 1280x720 | [3](https://www.mylf.com/movies/the-mature-anal-queen-next-door) |
| shared/med | SayUncle | 1600x900 | [5](https://www.sayuncle.com/movies/threesome-for-breakfast) |
| shared/med | default | 765x430 |  |
> Handle new TeamSkeet image paths

- scrapers/Teamskeet/TeamskeetAPI.py
[scene url](https://teamskeet.com/movies/my-trick-or-treat-fembot)
[scene url](https://teamskeet.com/movies/laundry-day-surprise)
Small fix to remove ending newline, and since StashDB already removes leading/ending whitespaces, it's hard to notice the ending newline when rescraping from StashDB.
> Teamskeet remove trailing newline scene details

- scrapers/Freshmen.yml
- Updated the URL pattern from freshmen.net/content/ to club.freshmen.net/secure/
- Added extraction for the Date field, using XPath selectors to locate and format the date
- Removed the definitions for the Performers and Image fields from the contentTab
- Changed the XPath selector for the Image field from //*[@id="videoPlayer"]/@poster to the more concise //video/@poster
- Added the Tags field to extract label information
- Updated the location of the Performers field, now extracting actor names from actors_list__actor
- Updated the last updated date of the configuration file to October 1, 2024
> Update the Freshmen.yml scraper configuration, adding more data extraction fields

- scrapers/IAFD/IAFD.py
IAFD scraper wasn't correctly pulling in performers careerlength, when performers are new or when IAFD is missing the ``(Started around xx years old)`` code
Small fix so it correctly grabs the careerlength the same way it grabs it from StashDB. It now grabs the text after ``Years Active`` since that is always listed on IAFD
[IAFD url](https://www.iafd.com/person.rme/id=1ac7507f-a610-47fd-84ef-42a7d32e196f) new performer lacking the ``(Started around xx years old)``
[IAFD url](https://www.iafd.com/person.rme/id=3659f3a2-2fad-4880-b20a-517b94b8cfd6) performer with multiple ``Years Active`` (when they're also directing)
> IAFD fix careerlength performer

- scrapers/SmutPuppet.yml
[scene url](https://porn-uk.com/update/2256/)
[scene url](https://dothewife.com/update/81/)
Updated Smut Puppet scraper
- Added sub-sites that were missing. 
Removed smutpuppet.com/update from the urls, it always re-directs to porngutter.com/tour, no matter what.
- Grab studio name by searching for scene at networksite porngutter.com, found out it's the most reliable way. 
For example, https://dothewife.com/update/81/ or https://smutmerchants.com/update/81/ both give you the same scene, but different studio when you scrape it. The search always gives you the correct studio.
- Grab date for scene from networksite porngutter.com. Not all subsites have a date for their scenes.
For example, this scene https://smutmerchants.com/update/1487/ from Smut Merchants, doesn't have a date, but …
> SmutPuppet scraper update

- scrapers/CopyToGallery/CopyToGallery.py
- scrapers/CopyToGallery/CopyToGallery.yml
Copies scene info to the images as well as gallery, saves clicking into the gallery and using the CopyToImages scraper there. 
Also added an optional gender filter for copying to images. Useful if the gallery has a lot of single performer glamour shots. Disabled by default.
> Merged CopyToGallery and CopyToImages scrapers.

- scrapers/torrent/torrent.py
bencoder.pyx is troublesome since it needs to be built from scratch, fastbencode is a drop-in replacement and performs much better than bencoder.pyx
```benchmark.py
import timeit
file_handle = open("target.torrent", "rb")
file_data = file_handle.read()
from bencoder import bdecode as bdecode_pyx
from fastbencode import bdecode as bdecode_fastbencode
from bencodepy import bdecode as bdecode_bencodepy
def bencode_pyx():
bdecode_pyx(file_data)
def bencode_fastbencode():
bdecode_fastbencode(file_data)
def bencode_bencodepy():
bdecode_bencodepy(file_data)
def check():
print(bdecode_pyx(file_data)[b"metadata"][b"taglist"])
print(bdecode_fastbencode(file_data)[b"metadata"][b"taglist"])
print(bdecode_bencodepy(file_data)[b"metadata"][b"taglist"])
check()
def benchmark(): …
```
> replace bencoder.pyx with fastbencode

- scrapers/Ersties/Ersties.py
- scrapers/Ersties/Ersties.yml
- scrapers/py_common/util.py
Performer: https://ersties.com/profile/1488
Scene: https://ersties.com/profile/1488#play-8165-comments
Movie: https://ersties.com/profile/2702
Created a URL scraper for ersties.com using python. Requires py_common and auth headers to be set in the .py file.
I also updated util.py to add "united states" = USA.
Related to issue 1819 - https://github.com/stashapp/CommunityScrapers/issues/1819
> Ersties.com URL Scraper

- scrapers/sensuallovexxx.yml
https://www.sensuallove.xxx/exploring-depth-2/
https://www.sensuallove.xxx/girls-with-a-lust-for-lovemaking-2/
https://www.sensuallove.xxx/girlfriend-intimacy-2/
Adds a new scene scraper for sensuallove.xxx
This is a 'tour' site, which is separate from the members site which is https://sensual.love/members
> Add sensuallove.xxx scraper

- scrapers/ModelMediaAsia.yml
Scrapers for a new site.
Scene example: https://modelmediaasia.com/zh-CN/videos/MD-0182
Performer example: https://modelmediaasia.com/zh-CN/models/11
I have used it for several scenes and things seem to work as expected so far.
The only thing I couldn't figure out is the way how performer URL should be added when a new performer is scraped with the scene scraper. See what I do with "Details" under "Performer" for the scene scraper. I am putting the URL there for the ease of use. For some unknown reason, if I directly set URL for performer, nothing will be set in the URL field for a newly created performer. I hope someone can take a look at that and see if it's a bug or something.
This should close #2068
> Add scene and performer scrapers for ModelMediaAsia

- scrapers/IFeelMyself/IFeelMyself.py
The imf_prefs cookie needed updating adds `s:11:"search_type";s:7:"content";` to the cookie string. Also changed the debug prompts to unify the code format. Also very old videos have only 2 digits for the media-id. The regex wouldn't find it as it specified for three. 
No bugs apparent
> Fix Ifeelmyself scraper imf_prefs cookie

- scrapers/IAFD/IAFD.py
Small fix for IAFD performer scraper. 
- IAFD changed the html code for performer aliases.
For example performer [Nicole Love](https://www.iafd.com/person.rme/id=68808ce4-9045-4ab1-8c4d-e6225893bacb)
Currently, the scraper returns aliases as a list with multiple elements (previously it returned a list with 1 element):
``['\r\n\t\tDenisa (czechcasting.com)', 'Nicol Love (wetandpuffy.com)', 'Nicola Love', 'Nicole', 'Nicole Melone', 'Nykol (czechhitchhikers.com)\r\n\r\n']``
Fixed it so it iterates over the all the elements of the list, and fixed xpath expression, so when value is ``No known aliases``, it returns empty list. Performer to test with no aliases [Gia Derza](https://www.iafd.com/person.rme/id=3ea548d3-7c73-4bbf-ba9b-eb94000eb5cb)
- Added xpath expression for eye color, skip if …
> Fix IAFD scrape performer aliases

- scrapers/PMVHaven/PMVHaven.py
Restores functionality to the PMVHaven scraper.
The latest update to the scraper removed the Music from the description. Music is an essential part of PMVs, unfortunately Stash does not have a dedicated field for it.
So, restoring the feature: Music is appended to the description.
> Update PMVHaven Scraper

- scrapers/JacquieEtMichelTV/JacquieEtMichelTV.py
- scrapers/JacquieEtMichelTV/JacquieEtMichelTV.yml
[Jacquie et Michel ELITE](https://www.jacquieetmicheltv.net/en/content/63622bcf89913bab983fcb86/stella-gives-in-to-temptation)
[Jacquie et Michel TV - EN](https://www.jacquieetmicheltv.net/en/content/673664c8cb1b833b0e313268/giulia-plays-with-georgia-in-the-most-naughty-way)
[Jacquie et Michel TV - FR](https://www.jacquieetmicheltv.net/fr/content/673664c8cb1b833b0e313268/giulia-joue-avec-georgia-de-la-plus-coquine-des-manieres)
Refactor script to use on-page JSON as primary data source.
- Refactor script
- New URLs
- Remove missing fragment support
- Remove language preference
> Fix broken Jacquie et Michel TV sceneByURL script scraper

- scrapers/GroobyNetwork-Partial.yml
- https://www.tgirlx.com/tour/models/Eva-Maxim.html
- https://www.tgirlx.com/tour/trailers/The-Muse.html
Adds scene and performer URL scraping for tgirlx.com to the existing Grooby scraper
> Add tgirlx.com to Grooby scraper

- scrapers/PornoLab/pornolab.py
- scrapers/PornoLab/pornolab.yml
https://pornolab.net/forum/viewtopic.php?t=3129435
https://pornolab.net/forum/viewtopic.php?t=2482653
https://pornolab.net/forum/viewtopic.php?t=2746513
Adds a new scene scraper for pornolab.net
This is the largest torrent tracker of adult content in Russia
> Add PornoLab scrapper

- scrapers/VRBangers.yml
- https://blowvr.com/model/lexi-luna/
- https://vrbangers.com/model/violet-myers/
- https://vrbgay.com/model/dante-colle/
- https://vrbtrans.com/model/isabella-fiorella/
- https://vrconk.com/model/harley-haze/
- https://blowvr.com/video/hottest-blowjob-with-vanna-bardot/
- https://vrbangers.com/video/sexy-soaking/
- https://vrbgay.com/video/restricted-area/
- https://vrbtrans.com/video/a-tour-to-remember/
- https://vrconk.com/video/addams-stepfamily-values-a-porn-parody/
The scene photo sets are on the same page as the video, so you can use the URLs above for `sceneByURL` as the URL to scrape for a gallery.
- Adds `performerByURL` scraper (note that birthdate is scraped from the birthday, it is up to the user to supply the year)
- Adds `galleryByURL` scraper
- Improves `sceneByURL` …
> add galleryByURL and performerByURL; improve sceneByURL for VRBangers

- scrapers/IAFD/IAFD.py
[Movie](https://www.iafd.com/title.rme/id=b83c0afb-b45e-40e0-aac2-78cf51e28563)
[Movie](https://www.iafd.com/title.rme/id=c763342b-1b1e-445e-975c-079236171577)
Newline and whitespace characters in IAFD title element (date fallback) are not matched by existing scraper.
- Fix matching extra whitespace in element text
- Don't return title if date not found
> IAFD Fix Group Date Fallback

- scrapers/ThePornDBJAV.yml
- scrapers/ThePornDBMovies.yml
Yui Hatano:
Adds a performer scraper for the two metadata scrapers for "theporndb.net".
> Add thePornDB.net performer scraper

- scrapers/FileMetadata/FileMetadata.py
- scrapers/FileMetadata/FileMetadata.yml
ffmpeg and ffprobe use [this](https://ffmpeg.org/ffmpeg-utils.html#Date) syntax for dates and times. [fromisoformat](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) should be able to parse any form that ffprobe can produce.
> Parse different datetime formats

- scrapers/IAFD/IAFD.py
- scrapers/IAFD/IAFD.yml
[Movie](https://www.iafd.com/title.rme/id=5a4cdc10-3aa7-429a-a6da-067b40244bf1)
[Scene](https://www.iafd.com/title.rme/id=c70927e3-eac7-42b6-875d-c8eddb386181)
- Fix group director selector
- Fix group Studio selector
- Unify shared selectors
> Fix IAFD groupByURL Script Director, Studio Fields

- scrapers/IAFD/IAFD.py
I noticed IAFD changed the layout when a performer is also active as director. As a result, the IAFD scraper didn't grab the alias
For example [Jules Jordan](https://www.iafd.com/person.rme/id=d5d8c2da-efe7-41ef-99a3-46a1aebccd07) or [Dana DeArmond](https://www.iafd.com/person.rme/id=3659f3a2-2fad-4880-b20a-517b94b8cfd6)
When also active as director, IAFD changed ``Performer AKA`` to ``AKA``
Plus a small fix for performer urls
> Iafd alias fix

- scrapers/WowNetworkVenus/WowNetworkVenus.py
- scrapers/WowNetworkVenus/WowNetworkVenus.yml
- added filename schema parsing for files downloaded via the normal download buttons (still works with filenames, that do not fit the schema)
- results sorted by similarity taking performers into account if they could be determined from the filename, instead of the useless default sorting of the scraped search results
- fix no result issue, if there is a number in the scene name (removes numbers from search scraping request)
- added sceneByFragment/Scene Identify capabilities
It is unlikely, that I will find the time to implement changes the maintaners may want, It works for my usecases so basically I am leaving this here for anyone that wants to use it, or for anybody that has the time to upstream it. I may miss notifications, as this is obvsiously a throwaway account.
Potential …
> Improve WowNetworkVenus

- scrapers/MrDeepFakes.yml
A couple hot takes in here since it doesn&rsquo;t seem like there&rsquo;s any prior art regarding deepfakes. In general, I&rsquo;ve opted for over&#x2010;scraping so curators can just ignore what they don&rsquo;t want.
- Both the faked celebrity faces and original pornstars are scraped as performers without distinction.
If it&rsquo;s acceptable to add a `deepfake` tag to the deepfaked performers, that would be an easy workaround, but there&rsquo;s definitely potential for false positives with that approach.
- Verified uploaders, which I&rsquo;m interpreting as the closest thing to content creators here, are scraped as studios.
If there&rsquo;s an XPath way to do gallery search by name, that should be easy to add as it&rsquo;s analogous to scene search.
Also, I can&rsquo;t tell whether or …
> Add support for MrDeepFakes

- scrapers/Iwara/Iwara.py
Sometimes the thumbnail index is 0 which Python was treating as False instead of 0 causing the condition to fail.
> Fixes cases where thumbnail is indexed at 0

- scrapers/PMVHaven/PMVHaven.py
Fix for https://github.com/stashapp/CommunityScrapers/commit/4767d20c3eae62755ea0c20567120e66d69cd1e9
The new version did not return a valid JSON format for Stash fixes:
- Description is renamed to "details"
- Tags are returned in the models.ScrapedTag format
> PMVHaven Scraper bugfix

- scrapers/Coomer/Coomer.py
> fix: Coomer.su sceneByFragment failing if file path contains any non english characters

- scrapers/VRPorn.yml
- https://vrporn.com/trans-the-personal-touch/
- https://vrporn.com/hot-blonde-teen-dylan-is-multi-orgasmic/
This removes the size variant from the filename, e.g.
https://mcdn.vrporn.com/files/20241122080315/Trans-The-Personal-Touch-VRBTrans-vr-porn-video-1000x562.jpg
becomes
https://mcdn.vrporn.com/files/20241122080315/Trans-The-Personal-Touch-VRBTrans-vr-porn-video.jpg
with the latter being 1300x731. This size varies with studio and scene, but appears to be consistently higher than the one presented as the video cover image on the scene page, e.g.
https://mcdn.vrporn.com/files/20250106180526/Hot-blonde-teen-Dylan-is-multi-orgasmic-Dylan-Moore-LethalHardcoreVR-vr-porn-video-1000x667.jpg
becomes
https://mcdn.vrporn.com/files/20250106180526/Hot-blonde-teen-Dylan-is-multi-orgasmic-Dylan-Moor …
> get highest resolution cover image

- scrapers/RealJamVR.yml
- https://porncornvr.com/actor/lexi-lore/
- https://realjamvr.com/actor/valentina-nappi/
- https://porncornvr.com/actor/charlie-forde/
- https://porncornvr.com/scene/threesome-passion-compilation/
- https://realjamvr.com/scene/hot-orgies-compilation-3/
- https://realjamvr.com/scene/threesome-ex-knows-best/
- https://realjamvr.com/scene/anal-satisfaction/
The scene photo sets look like they are on the same page as the video content of the scene, so you should be able to use the example URLs above
- sceneByURL
- fix: details selector updated
- improvement: studio code added
- improvement: "Virtual Reality" fixed tag added to scraped tags
- galleryByURL 
- (inherited) fix: details selector updated
- (inherited) improvement: "Virtual Reality" fixed tag added to scraped tags
- performerByURL
- …
> Fix RealJamVR

- scrapers/VRPorn.yml
- https://vrporn.com/trans-the-best-teen-compilation/
Though #2159 was an improvement to get higher resolution images, there is an edge case where the filename includes more than one WxH occurrence, e.g.
https://vrporn.com/trans-the-best-teen-compilation/
has
https://mcdn.vrporn.com/files/20240925170921/The-Best-Teen-Compilation_Hard_slider-2000x1000-1-1000x562.jpg
which needs to only remove the -WxH at the end to become
https://mcdn.vrporn.com/files/20240925170921/The-Best-Teen-Compilation_Hard_slider-2000x1000-1.jpg
which exists
This regex replace adjustment achieves this.
> fix: adjust regex replace to match WxH only at end of filename (vrporn.com)

- scrapers/RealJamVR.yml
- https://realjamvr.com/scene/matty-mila-perez-tries-anal/ (date is "Sept. 2, 2024")
- https://realjamvr.com/scene/threesome-ex-knows-best/ (date is "Jan. 7, 2025")
- https://realjamvr.com/scene/sweet-trio/ (date is "April 26, 2017")
This lets the date parsing handle the date format variants used on the site as shown above
> fix date parsing to handle month strings between 3 characters and full

- scrapers/ReflectiveDesire.yml
- https://reflectivedesire.com/performers/mbot/
- https://reflectivedesire.com/photos/awlivv-in-black/
- https://reflectivedesire.com/videos/catch-and-release/
Fix scene scraper and add gallery scraper for https://reflectivedesire.com/.
> ReflectiveDesire: fix scene scraper, add gallery scraper

- scrapers/LadyboyGold.yml
- scrapers/LadyboyGold/LadyboyGold.yml
- scrapers/LadyboyGold/TSRaw.py
- https://www.tsraw.com/model/stefany-santos
- https://www.tsraw.com/model/sheila-wandergirlt
- Bareback Sandwiching Between 2 Hung Tgirls
- Itty Bitty Titties & Armpit Lick Creampie
Adds performer scraping. Note that the birthdate parsing assumes that the age is current. This is only true if the performer has been added to the site in the last 12 months, otherwise the age will be wrong and therefore the year in the calculated birthdate value will also be wrong. It is better than a static year value or no year value at all, and the person scraping can decide what to do with the birthdate value (which will have the correct month and date-of-the-month values)
Scene preview URLs no longer appear to work at tsraw.com, but the data is still there. API searches work and can provide matching …
> improvement: add performerByURL, sceneByName|Fragment|QueryFragment for tsraw.com

- scrapers/AShemaleTube/AShemaleTube.py
- scrapers/AShemaleTube/AShemaleTube.yml
- https://www.ashemaletube.com/model/domino-presley-796-m9nr/
- https://www.ashemaletube.com/model/bailey-jay-308-m0xx/
- https://www.ashemaletube.com/model/daisy-taylor-5700-m1h4/
The ashemaletube.com site now has cloudflare protection. This refactor to Python makes use of `cloudscraper` to bypass the protection, and `FreeProxy` to improve the success chance of fetching the page successfully.
Each time a request is made via cloudscraper with a proxy, if a non-200 http status code is retrieved (i.e. usually 403 due to blocking) then another random proxy is used and the request re-attempted, until the response is a 200, or the max retries is reached. When the page is fetched successfully, the proxy used is used again to resolve any outgoing social media links (which are ashemaletube.com …
> Fix ashemaletube performerByURL

- scrapers/MissAV_en.yml
- scrapers/MissAV_jp.yml
Describe the general changes
The old MissAV site is blocked, so this update replaces the base URL with the new one to ensure continued access. No other changes are made.
> Update new base URL for MissAV

- scrapers/Motherless.yml
- `https://motherless.com/E7A2B24`
- `https://motherless.com/2353D19`
- Reduce likelihood of false positives by only matching hexadecimal strings.
- Match 6-8 char strings, as some (older) Motherless media appear to have 6-character IDs.
> Improved Motherless ID matching regex

- scrapers/PremiumBukkake/PremiumBukkake.py
- scrapers/PremiumBukkake/PremiumBukkake.yml
A member site first camera angle - prevoiusly not scrapable as no entry on free site 
https://members.premiumbukkake.com/scenes/Daruma-Rai-2-Bukkake-First-Camera_vids.html
Free site link to scene but with incorrect title and cover, replaced with correct ones from main site.
https://free.premiumbukkake.com/updates/Athenea-Rose-3-Bukkake.html
Scene which is same on all sites
https://premiumbukkake.com/tour2/updates/Georgia-Koneva-1-Bukkake-Behind-The-Scenes.html
There are 3 PremiumBukkake sites, a free site, a paywalled site(not protected)  and a members site(protected). The free site is published after the other sites and not all scenes have are published, the First & Second camera scenes and some of the BTS and Interviews never make it to this free site. The free site title is not always …
> Allow PremiumBukkake to scrape all scenes types 

- scrapers/Teamskeet/TeamskeetAPI.py
- https://app.teamskeet.com/movies/27092
- https://app.teamskeet.com/movies/27078
- https://app.teamskeet.com/movies/23868
Discovered that TeamSkeet recently changed their API path, breaking the app.teamskeet.com scraper. 
Checked the corresponding fetch GET call made in the live site and found this new format works as a drop-in replacement to the previous behavior.
Before, the called API would be `https://ma-store.teamskeet.com/ts_movies/_doc/27092`. This now 404s. The new format is now `https://ma-store.teamskeet.com/ts_index/_doc/movie-27092`, where `27092` is the scene ID
> Update app.teamskeet.com API_BASE

- scrapers/Kink.yml
- scrapers/KinkMen.yml
- scrapers/KinkTrans.yml
Narrowed the regex for scraping details
For some scenes the details were incomplete, regex stopped after ``\",`` while the details continued
Scrape the url below to see this behaviour
Updated the regex for details, to remove any left-over whitespaces before a newline character
https://www.kink.com/shoot/36182
> Fix for Kink scraping details

- scrapers/JacquieEtMichelTV/JacquieEtMichelTV.py
- scrapers/JacquieEtMichelTV/JacquieEtMichelTV.yml
Added python's unescape() to convert html character references to their unicode characters, for example ``&amp;`` to ``&``
Strip trailing newline character in details
https://www.jacquieetmicheltv.net/en/content/6352b7338b4552ba57ee3947/mary-jane-is-enjoying-herself-again
> Fix JacquieEtMichelTV details

- scrapers/Pornhub.yml
`Title` and `URL` need two slashes like `Image` and `Studio`
> Fix xPathScrapers sceneSearch selectors for Pornhub

- scrapers/HobbyPorn.yml
- scrapers/Pornhub.yml
`https://hobby.porn/` contains also the original Pornhub URL in the embedded video player.
Due to stashapp/stash#5677 it's possible to receive the HobbyPorn and Pornhub URL now.
> Extend HobbyPorn with multiple URLs

- scrapers/AniDB.yml
(examples are intentionally SFW, as NSFW requires account, but tags work the same)
* https://anidb.net/anime/17617
* https://anidb.net/anime/17870
The AniDB scraper was pulling the scene tags from a small box on the left, which only had a few preselected tags. This pulls tags from the big tag box towards that bottom, which is much more detailed.
the scene tags returned must fulfill some conditions:
* either no level (grey star), or at least 1 star (is just a XPath filter on the weight attribute)
* is from group indicators, elements, fetishes (ignoring stuff like technical aspects, origins, setting, themes)
> AniDB scraper pulls scene tags from complete tag box

- scrapers/TheScoreGroup/TheScoreGroup.py
- scrapers/TheScoreGroup/TheScoreGroup.yml
- https://www.scoreland.com/big-boob-videos/Danniella-Levy/50022/
- https://www.18eighteen.com/xxx-teen-videos/Alyssa-Star/12003/
- https://www.18eighteen.com/xxx-teen-videos/Olivia-Zlota/78187/?nats=MTAwNC45LjMuMy43MDMuMC4wLjAuMA
- https://www.18eighteen.com/xxx-teen-videos/Emma-Bugg/71841/
- https://www.18eighteen.com/xxx-teen-videos/Julissa-Delor/11628/
- https://www.xlgirls.com/bbw-videos/Ashlinx/78137/
- https://www.50plusmilfs.com/xxx-milf-videos/Jazmyn-James/78619
- https://www.40somethingmag.com/xxx-mature-videos/Harlow-Wilde/78282/
- https://www.naughtymag.com/amateur-videos/Vixi-Rafi/77273/
The YAML xpaths for sceneByURL have been migrated to Python to make use of the highest resolution image available logic provided by @feederbox826 's in …
> fix: migrate sceneByURL for TheScoreGroup to Python

- scrapers/Motherless.yml
The following example URLs are valid as of right now, if they (at a later date) just show a regular date, go look on https://motherless.com/videos/recent for videos with hours/days offset
This scene _currently_ shows "23h ago"
- https://motherless.com/F70400A
and correctly scrapers to 2025-03-31 (compared to right now, today on 2025-04-01 18:33)
scene _currently_ shows "1d ago"
- https://motherless.com/8193902
- https://motherless.com/7E70E2D
This uses inline JS to parse relative hours, and the native subtractDays feature (as suggested in https://github.com/stashapp/CommunityScrapers/issues/2201#issuecomment-2686796935)
Fixes #2201
> handle relative hours/days at motherless

- scrapers/AniDB.yml
(examples are intentionally SFW, as NSFW requires account, but tags work the same)
* https://anidb.net/anime/17617
* https://anidb.net/anime/17870
The previous version submitted in #2247 worked fine in XPath extensions in browser, but did not match all tags it should in stashapp itself, most likely due to difference in XPath engine behavior when in comes to attribute number string comparisons like `@data-anidb-weight>="200"`. Actually doing a numeric comparison `number(@data-anidb-weight)>=200` seems to work in both.
My apologies for not testing enough in the actual application, I got mislead by the Browser extension matching everything as expected.
> AniDB scraper tag pull fix of previous PR #2247

- scrapers/Sheer.yml
The comment prior to the updated code is pretty self-explanatory for why this commit is required.
> Sheer: Doing the 2025 annual update required for date scraping

- scrapers/Redgifs/Redgifs.py
```
majesticnormalrodent
https://www.redgifs.com/watch/majesticnormalrodent
Redhead [majesticnormalrodent]
MajesticNormalRodent
https://www.redgifs.com/watch/MajesticNormalRodent
Redhead [MajesticNormalRodent]
```
Updates the redgifs scraper to always use the lowercase form of the ID when hitting the API (even if a gif is named `MysteriousFancyPants`, the API will return the metadata at (only) the lowercase form `mysteriousfancypants`).
> Make the Redgifs API lookup case-insensitive

- scrapers/vixenNetwork/vixenNetwork.py
- scrapers/vixenNetwork/vixenNetwork.yml
Add Wifey (wifey.com) to Vixen Newtork scraper.
https://www.wifey.com/videos/victoria-and-leo-cute-blonde-hotwife-gets-fucked-doggystyle
vixenNetwork.yml:  
Added wifey.com to sceneByURL scraper.
vixenNetwork.py:
Added Wifey to the studios dictionary.
Changed "isValidURL" processing to use split instead of lstrip and rstrip, as the previous implementation was coded under a wrong assumption on how the strip functions work, which resulted in the 'w' from wifey from being stripped.  The new implementation splits on '.' and takes the second element, so www dot wifey dot com becomes "wifey" instead of "ifey".
I've only tested scrape by URL.  Someone more comfortable with the other methods that this scarper supports should test those out (sceneByName, sceneByQueryFragment and sceneByFragment).
> Add wifey to vixen network

- scrapers/KBProductions/KBProductions.py
- scrapers/KBProductions/KBProductions.yml
Added gogoworldporn (GoGo World Porn) to KBProductions Scene by URL and Performer by URL scrapers.
Added gogoworldporn.com to studio map in KBProductions python script.
Performer URL: https://gogoworldporn.com/models/cali-caliente
Scene URL: https://gogoworldporn.com/videos/gogo-xtreme-creampie
> Add GoGo World Porn to KB Productions URL scrapers (scene and performer)

- scrapers/TheScoreGroup/TheScoreGroup.py
- scrapers/TheScoreGroup/TheScoreGroup.yml
Add latinacoochies.com to TheScoreGroup scraper.
Performer URL:
https://www.latinacoochies.com/latina-porn-stars/Gabriela-Lopez/9115/
Scene URLs:
https://www.latinacoochies.com/latina-porn-videos/Gabriela-Lopez/78263/
https://www.latinacoochies.com/latina-porn-videos/Charlotte-Queen/78264
The Score Group has created Latina Coochies (latinacoochies.com), with URLs that scrape perfectly with the existing Score Group scraper.  This change adds the URL to the scrapers list, and adds the studio to the studios map in the YML and PY files.
It appears that the current Latina Coochies content is made up of scenes that already exist in other studios within The Score Group network, so using a latinacoochies.com URLs is likely to return the studio name for the scene's original studio.  This is pretty …
> Add Latina Coochies to TheScoreGroup

- scrapers/TGirlNetwork.yml
- https://www.tgirl-network.com/tour/show_video.php?galid=8000&section=255&tview=new
- https://www.tgirl-network.com/tour/show_video.php?galid=13683&section=484&tview=new
- https://www.tgirl-network.com/tour/show_video.php?galid=13399&section=1284&tview=new
- https://www.tgirl-network.com/tour/show_gal.php?galid=13396&section=1283&tview=new
- https://www.tgirl-network.com/tour/show_gal.php?galid=13671&section=485&tview=new
This adds tgirl-network.com. The studio for each scene or gallery tends to be the same as the performer name, as the sub-studios of TGirl Network generally are.
There doesn't seem to be a way to get the date from the TGirl Network pages, but some studios have tour pages with the most recent scenes with dates, e.g. https://www.ts-baileyjay.com/nwtour2, so those studios …
> add tgirl-network.com (network) and ts-baileyjay.com (sub-studio)

- scrapers/xbvrdb.py
- scrapers/xbvrdb.yml
This version queries the xbvr api for matched scenes when XBVR_HOST is set to the ip and port of the instance. If XBVR_HOST=None it will query xbvr.db as before
> Updating the xbvr scraper

- scrapers/scene-cover-in-dir.py
- scrapers/scene-cover-in-dir.yml
Allows you to set any image with a particular naming pattern (cover, fanart, poster, etc.) inside the directory of the video file.
Could still use a few improvements though:
1. It should be using the GraphQL API to get the file path of the scene's video file instead of SQLite reading.
2. Should be allowed to set any directory you like as a base path for the search (maybe image files are in another folder but still named correctly)
> Added scraper for cover/fanart/poster images in the directory of the video file

- scrapers/Nubiles.yml
Simplified Image selector to use the "poster" attribute from the "video" tag.
https://youngermommy.com/video/watch/182474/stepmom-and-i-go-shopping-s3e7
https://nubilefilms.com/video/watch/217292/april-2025-fantasy-of-the-month
Studio changed their layout so that the previous Image selector no longer worked (it was adding an additional "https" protocol to the URL.  Looking at some sample pages it appears that a simpler image value can be used.
> Fix Nubiles image not scraping issue

- scrapers/VirtualRealPorn.yml
- https://virtualrealporn.com/vr-porn-video/anime-girl/
- https://virtualrealporn.com/vr-porn-video/dress-code/
Currently the wrong element on the page is selected for scraping, e.g. "VR180 3D" as it is a fixed index of an array. As the regex pattern is reasonably robust to work for the whole div text, this change just concats the whole div to let the regex pick out the date string to parse.
> fix date scraping in virtualrealporn scraper

- scrapers/Baberotica.yml
New site from this network (Hamezo) added to scraper.
Scene from new studio:  https://hamezo.com/eri-mizuno-01/
Performer from new studio:  https://hamezo.com/pornstar/eri-mizuno/
Performer from older studio, with "Measurements" information:  https://suckmevr.com/pornstar/karina-king/
Added (mostly) compatible site to scraper.  The new site is a member of the same network as the rest handled by this scraper.  It uses a different method for the performer and tags, but everything else works fine.  Implemented as a "alternateSceneScraper", using most of the selectors from the existing scraper.
Added "Measurements" selector that Hamezo (and at least on other studio) covered by this scraper uses.
Added "Japanese Name" as a possible alias.
> Add Hamezo to Baberotica.yml

- scrapers/JacquieEtMichelElite.yml
Scene: https://www.jacquieetmichelelite.com/en/porn-scene-elite/show/8066/an-orgy-to-honor-the-guests.html
Movie: https://www.jacquieetmichelelite.com/en/porn-movie/elite/8058/sweet-cousins.html
Movie: https://www.jacquieetmichelelite.com/en/porn-movie/elite/14976/paparazza.html
Added new path to Movie FrontImage selector to match the poster image used in at least some of their releases.
Added new path to Scene Image selector to match the poster image used in at least some of their releases.
Old paths remain in the FrontImage and Image selectors as a defensive measure.  I've not seen those paths in my testing, but my search is far from exhaustive.
> Update Movie and Studio Image Selectors for J&M Elite

- scrapers/EvilAngel/EvilAngel.py
- https://www.evilangel.com/en/video/evilangel/Cream-Of-Cleavage-Sofis-Natural-Jugs/126145
The lewood.com uses AdultEmpireCash so the scene IDs and URLs are completely different
e.g. corresponding scene URL: https://www.lewood.com/508940/lewood-black-haired-babe-uses-a-vibrating-wand-and-enjoys-a-big-dick-streaming-scene-video.html
> fix lewood.com URL scraping via evilangel

- scrapers/GroobyNetwork-Partial.yml
* https://www.transnificent.com/tour/trailers/Felix-Raunchy-Job-Interview.html
* https://www.realtgirls.com/tour/trailers/Probation-Officer-Jenna-Jaden-Gets-Attitude-Adjustment-From-Smash-Thompson.html
For several sites covered by this scraper, when there are multiple performers, the scene title will include the performer names (linked to the performer page) and then the title. This causes the xpath to just result in a title of `&`. I think what's happening here is when there are 2 or more performers, the `&` between the performer names is getting captured as a `text()` value and being picked up as the scene title.
To fix this, I've adjusted the xpath query to only take the *last* text element when matching the `trailer_toptitle_left` element. I manually tested these changes against all …
> Update GroobyNetwork-Partial.yml to handle performer names in titles

- scrapers/GroobyNetwork-Partial.yml
https://www.joeystransfeetgirls.com/tour/trailers/Billies-Over-The-Shoulder-Footjob.html
https://www.kellyquellxxx.com/tour/trailers/Daisy-Gets-Railed-by-Kelly-for-the-First-Time.html
https://www.joeystransfeetgirls.com/tour/models/Variety-Itsol.html
https://www.kellyquellxxx.com/tour/models/Neci-Archer.html
Added URL joeystransfeetgirls.com and kellyquellxxx.com to URL scene and performer scrapers.
Added additional Birthdate date parsers for different formats that have been observed in the performers pages, with an additional one as a defensive measure in case an existing or future site uses that format.
> New grooby network sites

- scrapers/AdultTime/AdultTime.py
- scrapers/AlgoliaAPI/AlgoliaAPI.py
- https://www.puretaboo.com/en/photo/Up-Close-with-Cubbi-Thompson/124309
- https://www.puretaboo.com/en/photo/Too-Many-Tops/127136
- https://www.puretaboo.com/en/photo/Office-Ms-Conduct/101153
This adds a few studio overrides to set the right studio when scraping scenes, galleries, and movies/groups.
Bonus feature: when scraping a gallery, the `picture` property is logged out as a full URL to give the photo set cover image. This can be used by a user to manually select and set the cover image for a photo set.
> Add a few more studio overrides to AdultTime

- scrapers/Blowpass/Blowpass.py
- scrapers/Blowpass/Blowpass.yml
- https://www.blowpass.com/en/video/blowpass/Maddy-OReillys-12-Guy-Blowbang/132228
- https://www.blowpass.com/en/video/blowpass/Jessie-And-Addison-Have-Young-Squirting-Pussies/77319
- https://www.blowpass.com/en/video/blowpass/Birthday-Goodies/75734
I checked through the Blowpass sub-studios and adjusted the studio matching slightly for the 3 scenarios above.
Bonus: added performer and gallery scraping for all sites.
> Improve studio matching in blowpass

- scrapers/AdultDvdMarketPlace.yml
Config update for all xPath scrapers.
[sceneByURL: Rough Love 3](https://www.adultdvdmarketplace.com/dvd_view_416507.html)
Add click on "ENTER" button when scraping.
Quick'n'dirty fix that adds unnecessary overhead, should move to a script in the future that calls "www.adultdvdmarketplace.com/xcart/adult_dvd/disclaimer.php?action=enter" once before scraping.
> AdultDVDMarketPlace CDP Age Prompt Click-through

- scrapers/Eporner.yml
https://www.eporner.com/video-jjeDsNksaKo/rosa-romano-ti-rompo-il-culo-2006-scene-3/
https://www.eporner.com/video-aWFaj0kfhN5/big-ass-blondie-girl-tries-hard-cocks/
- sceneByURL would throw: `scrapeSceneURL: input: scrapeSceneURL Internal system error. Error <runtime error: index out of range [0] with length 0>`
- And sceneByName showed no error, only the No Scenes Found toast and nothing in the logs.
> Fix Eporner (sceneByURL, sceneByName)

- scrapers/Wallhaven.yml
SFW because NSFW needs account and API token
https://wallhaven.cc/w/9dqojx
https://wallhaven.cc/w/yxd8jk
I know this a a REALLY niche use case, but I needed a scraper for Wallhaven wallpapers, so I figured I might as well share it, maybe someone else has a use for it. In my experience, Wallhaven has a huge amount of very well-tagged NSFW wallpapers.
Some key points:
* the title is cobbled together, roughly `Persons (Model, Pornstar, Character)` + `Producers (Brand, Phorographer, Artist)` + `all other tags`
* studio is either first company tag (to pick up studios like MetArt), first photographer tag (e.g. Hegre is just "Peter Hegre"), or first artist tag (for drawn / rendered content)
* Performers should be all tags from the categories Models, Pornstars or Characters, but some other tags …
> wallhaven.cc scraper

- scrapers/Xhamster.yml
https://xhamster.com/videos/horny-for-cock-gogo-fukme-paris-the-muse-destiny-mira-seduce-van-until-they-get-what-they-want-brazzers-xhRZgf3
https://xhamster.com/videos/stepmom-gives-a-good-blowjob-to-her-stepson-in-his-bed-xhDYAmQ
https://xhamster.com/videos/unplanned-sex-sharing-bed-between-stepson-and-his-stepmom-xhorEYJ
- Fix scraping title correctly.
- Add creators and users scraping to be used as performers and studios.
> Fix XHamster scene scraping

- scrapers/VRSpy.yml
Note that the scene pages don't show the cover image, the scraper gets the cover image that appears in scene lists.
- https://www.vrspy.com/video/pass-through-christina-sage-on-demand
- https://www.vrspy.com/video/lucky-visit
- https://www.vrspy.com/video/curious-roommates
- https://www.vrspy.com/star/alicia-williams
- https://www.vrspy.com/star/christina-sage
This adds scene and performer URL scraping for vrspy.com
> Add vrspy.com

- scrapers/EvilAngel/EvilAngel.py
- scrapers/EvilAngel/EvilAngel.yml
The site features scenes from other studios as well.
- https://www.latexplaytime.com/en/video/latexplaytime/Latex-Pawg-Plugged--Ploughed/232199
- https://www.latexplaytime.com/en/video/latexplaytime/TS-KASEY-KEI-Seduces-Coco-Lovelock/233037
- https://www.latexplaytime.com/en/video/latexplaytime/TOMMY--SUMMER-Lesbian-Anal-Nursing/231297
- https://www.latexplaytime.com/en/video/latexplaytime/GIA-DERZA-Latex-BJ--Anal-Submission/235156
- https://www.latexplaytime.com/en/video/latexplaytime/JEWELZ-BLU-Oil-Drenched-Anal-Hammering/253045
The site features galleries from other studios as well.
- https://www.latexplaytime.com/en/photo/JEWELZ-BLU-Oil-Drenched-Anal-Hammering/120197
- https://www.evilangel.com/en/photo/Lydia-Black-Latex-Deepthroat--Anal/97638
Adds sceneByURL for latexplaytime.com. …
> Add latexplaytime to evilangel

- scrapers/VirtualRealPorn.yml
- https://virtualrealtrans.com/vr-models/janny-costa/ (this is an example of when the hips and waist have been entered the wrong way round)
- https://virtualrealgay.com/vr-models/kristof-plachta/
Adds more VirtualRealPorn network sites for performerByURL scraping. The amateur and Japan sites do not appear to have performers listed per scene, nor listed by themselves.
> add virtualrealgay and virtualrealtrans sites for performerByURL

- scrapers/GirlsOutWest.yml
https://tour.girlsoutwest.com/trailers/Lexi-Ruby-Tuesday-Yard-Work.html
https://tour.girlsoutwest.com/trailers/Arcadia-Hunny-Love-Nest.html
After a change to the website's format, the current community scraper for Girls Out West incorrectly parses the paragraph scraping of the scene descriptions, merging multiple separate paragraphs into a single paragraph. This update fixes that problem.
> Fix Girls Out West description paragraph spacing

- scrapers/LadyboyGold/LadyboyGold.yml
- https://www.ladyboygold.com/index.php?section=1832&actorid=2033 (Age: 24, Birthday: November 5) should scrape 2000-11-05
- https://tsraw.com/model/aline-tavares (Age: 27, Birthday: May 20) should scrape 1998-05-20
This reuses the same Age + Month,DateOfMonth logic that was added for TSRaw. That code actually had a bug where it was adding the `extraYear` (for scenarios where the birthday is later in the current year), but it should actually be subtracted. That bug is fixed now.
For some reason I can't scrape a performer at tsraw.com, I think it might be some sort of JS lazily-loaded page as the `debug.printHTML: true` option doesn't show the same content as I can see in a browser even with:
```yaml
debug:
printHTML: true
driver:
useCDP: true
cookies:
- CookieURL: "https://tsraw.com" …
```
> add birthdate for ladyboygold performerByURL

- scrapers/Teamskeet/Teamskeet.yml
- scrapers/Teamskeet/TeamskeetAPI.py
Added freeuse.com to Teamskeet API scene by URL scraper.
Resolves #2402 
https://www.freeuse.com/movies/the-new-man-of-the-house
https://www.freeuse.com/movies/stock-market-fever
https://www.freeuse.com/movies/freeuse-me-all-day-long-lilys-fathers-day-gift
Added freeuse.com to scene by URL scraper.
Modified python to allow and handle scenes from freeuse.com.
Found a scene that has no tags that was returning the literal string "null" as a tag.  Added check to remove "null" in the returned tags.
Now dumping JSON returned from the API to the log to make it simpler to make possible future changes based on JSON structure.
Need to determine:  Is this implementation returning the highest possible resolution for the scene image.
> Add freeuse to teamskeet api

- scrapers/CorbinFisher.yml
See discussion on stashdb [here](https://stashdb.org/edits/ad26535c-391c-4330-9db3-2d80d30012e0)
The current corbinfisher scraper doesn't always scrape scene description consistently. The p element for descriptions contains a mix of text content and `<br/>` elements. This update should use both elements and properly replaces the br elements with line breaks accordingly.
- https://corbinfisher.com/tour/trailers/Mario-Fucks-Josh-remastered.html
The existing CF scraper flattens all the text with no line breaks. See a discussion at this stashdb edit [here](https://stashdb.org/edits/ad26535c-391c-4330-9db3-2d80d30012e0). This update will also preserve the `<br/>` …
> Update CorbinFisher.yml scene description scraping

- scrapers/PornPics.yml
https://www.pornpics.com/galleries/stunning-teen-lorena-b-showing-off-her-trimmed-bush-her-curvy-ass-66995558/
Added imagebyurl
> Added imagebyUrl

- scrapers/MyMemberSite/MyMemberSite.yml
https://yourfitcrush.com/videos/319-solo-naked-full-of-chokolad-on-my-body-play-with-toy
https://members.baebihel.com/videos/229-as-soon-as-im-home-from-school-all-i-want-to-do-is-masturbate
Added a `sceneByFragment` scraper to the existing MyMemberSite scraper. No changes are made to the scraper's python script as it simply uses the existing `sceneByURL` code. This change just allows it to be used in the scene tagger view instead of only being used on an individual scene, which was useful for me after bulk downloading videos.
> Add sceneByFragment scraper

- scrapers/LucasEntertainment.yml
Use `meta[@name='twitter:image']/@content` instead of scraping and parsing from script. Current implementation doesn't work when preview limit is reached. This PR addresses that.
> Update LucasEntertainment.yml scene cover scrape

- scrapers/GroobyNetwork-Partial.yml
- scrapers/GroobyVR.yml
- https://www.groobyvr.com/tour/trailers/Dicking-Down-Gigi-Ravine.html
- https://www.groobyvr.com/tour/trailers/A-Katt-In-Your-Lap.html
- katt
- lap
Note that when the search results have more than 1 scene, the list of performers is repeated for each scene. I'm not sure if there is a way around this? This only affects the searchByName results list, and the searchByQueryFragment just scrapes the individual scene page normally.
this uses scene URLs, so the sceneByURLs above
- https://www.groobyvr.com/tour/models/Cailey-Katts.html
This adds a scene search for groobyvr.com. As a scraper file appears to only support a single sceneByName queryURL (and seems to have no per-domain ability), it made sense to move this scraper out of the (rather messy) GroobyNetwork-Partial scraper into its own …
> move groobyvr to own scraper to allow scene search

- scrapers/GroobyVR.yml
- https://www.groobyvr.com/tour/models/Cailey-Katts.html
Picks the original image (with the -full suffix) rather than the 3x scaled (from default/cropped) image as suggested by @Maista6969 in #2434
> GroobyVR: pick original image for performer

- scrapers/AdultTime/AdultTime.py
- https://www.devilsfilm.com/en/video/devilsfilm/Things-Are-Looking-Upskirt---Madison-Morgan--Tommy-Pistol/259559
- https://www.devilsfilm.com/en/video/hairyundies/Things-Are-Looking-Upskirt---Pixie-Smalls--Axel-Haze/259558
- https://adulttime.com/en/video/devilsfilm/Things-Are-Looking-Upskirt---Madison-Morgan--Tommy-Pistol/259559
- https://www.futaworld.com/en/video/futaworld-at/Dicks-Diner/248782
Devils Film scenes seem to all have a "largest" image that is 960x544, but there is actually a 1920x1281 image available. This change picks the larger image out instead just for Devils Film, other AdultTime studios continue to use the "top" image which seems to always be 1920x1080.
> override largest image for devils film

- scrapers/Jellyfin/Jellyfin.py
Jellyfin 10.9 changed the Way Items can be referenced by URL. While the old pattern still works, it is deprecated now and will be removed in the future. Therefore the URL-Syntax has been updated to match the new Standard. Furthermore I implemented two configurable Options in the config.ini: If "Scene2Movie" is set to true, an Movie will be automatically created when scraping a new Scene. This is helpful if you have mainly Movies in Jellyfin and wants to create Movies in Stash accordingly. If "IgnoreSceneImage" ist set to true, the Primary Image for the Scene will not be pulled from Jellyfin. This is helpful if you have Coverart in Jellyfin for your Movies, but want to make sure that you only use it for movies, not for the Scenes
> Add some Improvements, Make Scraper compatible with JF 10.9+

- scrapers/DreamTranny.yml
- https://dreamtranny.com/update/1141/
- https://dreamtranny.com/update/1149/
The a tag now has another class part, so the exact match no longer works. The partial match using contains should now always work regardless of the other parts of the class string.
> fix performer xpath in dreamtranny.com

- scrapers/Babepedia.yml
Hayden Panettiere
Describe the general changes
Seems some performers on Babepedia have cup sizes in their measurements, so this just updates the regex to catch that
> Fix measurements regex on Babepedia

- scrapers/CorbinFisher.yml
Corbin Fisher does not provide tags on their site. However they recently have been releasing a remastered re-released series of videos- at least one per week. This tag can be inferred from the canonical url.
Tested against:
https://www.corbinfisher.com/tour/trailers/Ty-Fucks-Austin-REMASTERED.html
https://corbinfisher.com/tour/trailers/Josh-Fucks-Brody-remastered.html
Tested that it does _not_ incorrectly tag scenes without this regex in the url:
https://www.corbinfisher.com/tour/trailers/Double-Loading-Noahs-Arse.html
Autotag remastered/re-released scenes on CF
> CorbinFisher.yml- detect the `Re-Release` and `Remaster` tags based on the canonical url

- scrapers/GroobyVR.yml
- https://www.groobyvr.com/tour/trailers/Getting-Into-Lolas-Jeans.html
- https://www.groobyvr.com/tour/trailers/Waking-Up-With-Ariel.html
- https://www.groobyvr.com/tour/trailers/Embers-Long-Stretch.html
- https://www.groobyvr.com/tour/trailers/I-Fucked-Gabrielly-Ferraz.html
Someone recently pointed out that the "-1x" (or "-2x" or whatever number x) in the image URL can be changed to "-full" to get the largest version. This change does that
> GroobyVR: pick largest image

- scrapers/BigBootyTGirls.yml
- scrapers/Trans500.yml
- https://www.trans500.com/trailers/Lets-Go-MsRodrigues.html
- https://www.trans500.com/tour3/trailers/All-About-Allison.html
- https://bigbootytgirls.com/updates/A-Dani-Weekend.html
The photo sets are mentioned on the tour/trailer pages at bigbootytgirls.com, so it makes sense to scrape the same info as the sceneByURL.
The studio code is in the image URL, so that is now scraped
> Add gallery by url to bigbootytgirls; add studio code to Trans500 sites

- scrapers/ElseCinema.yml
https://elsecinema.com/movies/hey-siro
https://elsecinema.com/movies/naked-kitchen-ep-1
https://elsecinema.com/movies/private-dancer
https://elsecinema.com/movies/straight-man-porn
New URL  Scene Scraper for Else Cinema (elsecinema.com).  Loosely based on the similar site "Lust Cinema", but some selectors are distinct enough that an individual scraper makes sense.
> Add URL Scene Scraper for Else Cinema

- scrapers/FistingInferno/FistingInferno.yml
- scrapers/GammaEntertainment.yml
GammaEntertainment no longer supports fistingcentral.com, and no valid metadata can be retrieved.
example:
https://www.fistingcentral.com/en/movie/Maniacal/82278
https://www.fistinginferno.com/en/movie/Maniacal/82278
> Remove support for fistingcentral.com from GammaEntertainment to FistingInferno

- scrapers/GroobyNetwork-Partial.yml
- https://www.transexpov.com/tour/trailers/One-Perfect-Night.html
- https://www.transexpov.com/tour/trailers/Creampieing-The-New-Neighbor.html
The cover image did not have a matching xpath expression on the transexpov.com for at least some of the scenes. This change adds one, and also alters the image URL to pick the highest resolution available.
> add xpath for transexpov cover image

- scrapers/AlgoliaAPI/AlgoliaAPI.py
This now logs out the scene number in a movie
- https://www.evilangel.com/en/video/evilangel/TS-ANDYLYNN-PAYNE-Seduces-EMMA-ROSIE/283513
- https://www.tsfactor.com/en/video/evilangel/Grazyeli--Shakira-TS-Glam-Girls-Date/282633
One of the performers has a trailing space in the API which causes a mismatch, this is now fixed.
- https://www.evilangel.com/en/photo/Trans-Active-31/145312
- https://www.tsfactor.com/en/video/evilangel/Grazyeli--Shakira-TS-Glam-Girls-Date/282633
The logged gallery photo set cover image URL can now be viewed directly in a browser, it currently spawns a file download which is less convenient as the cover image has to be downloaded as a file and then opened.
- https://www.evilangel.com/en/photo/Trans-Active-31/145312
Some improvements to the AlgoliaAPI scraper and …
> Improve Algolia API

- scrapers/Perverformer.yml
- https://perverformer.com/en/video/two-beautiful-sadists-provoke-pleasure-and-pain
- https://perverformer.com/en/video/foursome-with-2-female-sadists-and-1-latex-doll
- https://perverformer.com/en/video/mistress-has-control-over-orgasms-and-breathing
- https://perverformer.com/en/video/the-harder-the-erection-the-stronger-the-distress
Added scene scraper for perverformer.com.
> Perverformer: add scene scraper

- scrapers/UKXXXPass/UKXXXPass.yml
- https://ukpornparty.xxx/movie/500/mackenzie-and-loula-enjoy-a-gangbang
- https://splatbukkake.xxx/movie/84/big-boobed-bukkake-with-talula-and-jordan-pryce
- https://sexyukpornstars.xxx/movie/3486/bar-anal
This is a new scraper for the UK XXX Pass sites, including SplatBukkake, UK Porn Party and Sexy UK Pornstars
I'm not sure if there's a way to extract the URL matched for the scraped query, i.e. if the URL is for https://splatbukkake.xxx/, then I can use that URL to fetch the correct studio name and image. At the moment, I'm using a pretty hacky workaround to construct the URL, so I'd be happy to hear if there's a better way to do this
> Adding UKXXXPass scraper for all their sites

- scrapers/RealjamVR/RealJamVR.yml
[List a few links/titles/names/filenames/codes to test]
https://realjamvr.com/scene/threesome-anal-teacher-for-stepsister/
https://realjamvr.com/scene/slutty-housewife-bunny-madison/
https://porncornvr.com/scene/latex-doll-ember-snow/
https://porncornvr.com/scene/threesome-passion-girls-prefer-anal-2/
I don't love this pull request. Nearly everything works for both RealJam and PornCorn with two exceptions which is why there are two scrapers. The URL extraction hard codes the base URL. This is really only used if you use Scene Search By Name.  As far as I can tell I can't have two "search by name" items listed in the same Yaml file (one for PornCorn one for RealJam) created in the drop down even though I'd use the same Python code.  I really feel like this could be better consolidated but …
> Performer now scraping from both RealJamVR and PornCornVR

- scrapers/AD4X.yml
- scrapers/FrancescoMalcom.yml
Refactor the AD4X scraper to enhance URL coverage and data extraction. Update the scene scraping logic to support additional URL paths, including 'ad4x.com/en/videos' and 'ad4x.com/videos'. Modify the XPath for 'Title' to target 'section-title' div for improved accuracy. Change the 'Date' selector to extract publication date from script tags and reformat it to 'YYYY-MM-DD'. Adjust 'Image' scraper to use the 'og:image' meta tag for better reliability. Update 'Performers' XPath to fetch names from 'model-thumb' associated elements. Add scraping for 'Code' using a new selector, parsing the ID from script tags. Update metadata with the latest modification date; enhances data integrity and adaptability.
> refactor: update AD4X scraper and improve data extraction
